SpecterOps/BloodHound

cmd/api/src/auth/bhsaml/provider.go
This updates the SAML API root constant to be mutable. Until we have a better way of negotiating the different URL paths for SAML from the old enterprise V1 API this is best-effort.
Unblock old SAML registrations in the enterprise build.
Local testing with Auth0.
=> fix: make saml login root a var so we can set it for each app context

docker-compose.yml, examples/docker-compose/docker-compose.yml
Docker healthcheck creates a new file in the neo4j docker every 10 seconds. To avoid filling the `/var/lib/neo4j` folder with thousands of files, the commit redirects the output of `wget` to `/dev/null`.
The docker containers was removed to trigger `docker compose up` and check if the docker is in the `healthy` status
-   [ …
=> Fix: Healthcheck neo4j don't keep output file of wget

cmd/api/src/api/marshalling.go, cmd/api/src/api/middleware/logging.go, cmd/api/src/api/middleware/middleware.go, cmd/api/src/api/middleware/middleware_internal_test.go, cmd/api/src/api/middleware/middleware_test.go, cmd/api/src/api/v2/pathfinding.go, cmd/api/src/ctx/ctx.go, cmd/api/src/queries/graph.go, cmd/api/src/queries/graph_test.go, packages/go/dawgs/graph/path.go, packages/go/dawgs/ops/ops.go
Remove a bunch of experimental machinery around controlling request context timeouts. This style of control leads to strange double-commit scenarios for the `http.Response` type and results in incorrect `504` responses where the client is behaving but behind a slow connection.
This changeset addresses https://github.com/SpecterOps/BloodHound/issues/13.
There's a long history of debug attempts related to the code being cleaned up here. To save everyone a long read, the gist is that this was an experiment in aggressively trying to preserve UX for multi-user, single-tenant instances that back BloodHound Enterprise.
Integration test passes to validate that request handling operates as expected. One negative test harness written in Python that won't be committed.
-   [ ] Chore (a change that …
=> fix: remove aggressive timeout context setting middleware

.env.example
Comment out non-default env option to make `.env-example` align with actual defaults
Discovered that the .env-example provided sets a non-default value by default
Just cleanup, no-op change
=> fix: env shouldn't use non-default options by default

cmd/ui/src/components/GraphEdgeEvents.tsx, cmd/ui/src/components/GraphEvents.tsx, cmd/ui/src/components/SigmaChart.tsx, cmd/ui/src/rendering/programs/edge.arrow.ts, cmd/ui/src/rendering/programs/edge.arrowHead.ts, cmd/ui/src/rendering/programs/edge.clamped.ts, cmd/ui/src/rendering/programs/edge.curvedArrow.ts, cmd/ui/src/rendering/programs/edge.curvedArrowHead.ts, cmd/ui/src/rendering/programs/node-hover.ts, cmd/ui/src/rendering/programs/node.glyphs.ts, cmd/ui/src/rendering/utils/utils.test.ts, cmd/ui/src/rendering/utils/utils.ts
The existing rendering programs have been updated to uniformly account for the zoom ratio when handling calculations involving node radii. 
Design choices made in the sigma repository cause node sizes to adjust to the zoom ratio so that nodes stay relatively the same size regardless of the zoom ratio. These size adaptations have undesired side effects for our use case such as edge arrowheads becoming hidden when zoomed in too close and so a factor is applied in this changeset to avoid such behavior.
A unit test was added for the `getNodeRadius` utility function. Zoom behavior was verified in a local instance. See the screen captures below
Previous undesired behavior
https://github.com/SpecterOps/BloodHound/assets/16910931/565da243-6c12-48ef-9078-aaac602c711c
Fixed behavior …
=> fix: adapt node radius size to account for zoom ratio in rendering programs

cmd/api/src/queries/graph.go, packages/go/cypher/frontend/format.go, packages/go/cypher/frontend/format_test.go, packages/go/cypher/frontend/parse.go, packages/go/dawgs/query/neo4j/neo4j.go
This changeset improves the openCypher front end by adding an emitter type that can contain output configuration information. This type is used to add a switch in the format functions for stripping literals when outputting openCypher from the query model.
Stripped literals are replaced with a parameter named `$STRIPPED`. This allows the query to remain syntactically correct while removing any sensitive information contained in the literal values.
Property names and other syntax elements are currently not considered sensitive.
```json
{"level":"info","query":"match p = ()-[:HasSession]->(n)-[]->() where n.pii = $STRIPPED return p","time":"2023-08-14T09:38:22.575719651-07:00","message":"Executing user cypher query"}
```
* Refactor the emitter type to output to the `io.Writer` type for …
=> feat: enable literal scrubbed user query logging

cmd/api/src/daemons/datapipe/azure_convertors.go, cmd/api/src/daemons/datapipe/ingest.go, packages/go/ein/azure.go
- update Container Registry & WebApp Role Assignments role assignments to not delete other relationships that are ready for ingest
Several Azure relationships were not being ingested into the dataset due to several logic errors.
=> fix: update role assignments to not delete existing relprops

packages/go/dawgs/drivers/neo4j/neo4j.go
This was ill-advised in implementation. We use timeouts for query quality control but not all paths expect a 15m timeout application. Instead we should resort to how the neo4j core library sets this value.
Seeing some transient failures occur for valid operations that take longer than 15m.
Integration tests.
-   [ ] My …
=> fix: remove blanket 15m timeout for transactions

packages/go/dawgs/traversal/id.go, packages/go/dawgs/traversal/traversal.go
In a parallel BFS traversal, it's possible that some workers are unable to start due to connection slots being unavailable. This can result in a situation where the traversal naturally finishes but because workers are locked into waiting for a connection slot, they surface the context cancellation as a failure.
Log noise and better behaved traversal.
-   [x] All new …
=> chore: do not log context timeouts from traversal workers

cmd/api/src/api/v2/cypher_search.go, cmd/api/src/api/v2/pathfinding.go, cmd/api/src/docs/json/definitions/graphs.json, cmd/api/src/docs/json/paths/v2/graphs.json, cmd/api/src/model/unified_graph.go, cmd/api/src/queries/graph.go, cmd/api/src/queries/graph_test.go, cmd/api/src/queries/mocks/graph.go, cmd/ui/src/components/GraphEdgeEvents.tsx, cmd/ui/src/utils.ts, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.test.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeObjectInformation.test.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeObjectInformation.tsx, cmd/ui/src/views/Explore/GraphView.tsx, cmd/ui/src/views/Explore/fragments.tsx, packages/go/slices/slices.go, packages/javascript/bh-shared-ui/src/components/Disable2FADialog/Disable2FADialog.test.tsx, packages/javascript/bh-shared-ui/src/providers/NotificationProvider/reducer.ts, packages/javascript/bh-shared-ui/src/store/edgeinfo/edgeSlice.ts, packages/javascript/js-client-library/src/client.ts
All of the edge information that is collected into BloodHound will now display in the Edge Info Pane under Relationship Information section when selecting an edge.
The changes here have enhanced the `api/v2/graphs/cypher/` endpoint to allow requesting full hydration of the properties for the nodes and edges returned from the results of the cypher query by passing a field in the JSON body for include_properties with a boolean value that defaults to false. This allows doing an internal cypher query for the selected edge's properties that are sure to be hydrated regardless of the data that was returned with the response for rendering the graph.
Since there are various ways to initiate rendering a graph in the UI and because different ways route through different endpoints, not all of the …
=> Relationship Information Properties

cmd/api/src/queries/graph.go, cmd/api/src/queries/graph_integration_test.go, cmd/api/src/test/integration/harnesses.go, packages/go/cypher/frontend/format.go, packages/go/cypher/test/cases/positive_tests.json, packages/go/dawgs/query/neo4j/neo4j_test.go
some of the built in groups were not searchable from the explore page because of the way the dawgs query was written in `queries.SearchNodesByName()`.  The dawgs query had a filter that excluded any nodes with a label of `:Group`, but there are cases when we want to return nodes with the labels `:Group:ADLocalGroup`.  This PR updates the dawgs query to express this logic
the equivalent cypher we want to express in dawgs is:
```MATCH (n) WHERE NOT (n:ADLocalGroup AND NOT n:Group)```
this query will match nodes like `(n:AdLocalGroup:Group)` but WON'T match `(n:Group)`
i also updated the query formatter in the cypher frontend package to wrap negation clauses in parens.  
the test suite for the cypher parser has been updated so that test cases with negation clauses are now correctly wrapped …
=> draft: built in groups get filtered out 

packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
- Under some conditions, two vertical scroll bars are visible in the results display for the new current search feature. This PR adjusts the height of our virtualization window to prevent the unintended overflow.
- This is a quick fix for an issue caused by [https://github.com/SpecterOps/BloodHound/pull/61](https://github.com/SpecterOps/BloodHound/pull/61)
-   [x] …
=> fix for extra scrollbar in current search results

cmd/api/src/database/migration/gorm.go, cmd/api/src/model/agi.go
MERGE AFTER https://github.com/SpecterOps/BloodHound/pull/90 IS RELEASED
This adds a uniqueness constraint on the `name` column in `AssetGroupSelectors` through GORM. This will be essential for newly spun up environments since these will not run the manual migrations created in https://github.com/SpecterOps/BloodHound/pull/90
-   [x] All new and existing tests …
=> DO NOT MERGE add gorm constraint on asset_group_selectors

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Update "Users" and "Groups with foreign domain group membership" Cypher queries to more accurately specify "domainsid" instead of "domain" in the WHERE clause. This resolves an issue where returned results incorrectly included non-foreign domain groups or users
`Groups with foreign domain group membership` and `Users with foreign domain group membership` can incorrectly return results that include domain local objects.
This changes the queries to specify `domainsid` rather than `domain`.
Tested in a BHCE dev environment and BHE environments.
-   [ X ] Chore (a change that does not modify the application functionality)
-   [ ] Breaking change (fix or feature that …
=> Improve Cypher queries for foreign groups and users

cmd/ui/src/components/Header.tsx, cmd/ui/src/components/LoginPage.tsx, cmd/ui/src/views/Explore/ExploreSearch/CypherInput.tsx
This changeset updates img src url's to use the root path.
The `src` attribute for some `img` tags were using a relative path instead of the root path which would point to the wrong location when moving to different pages, most notably pages within the administration page. 
Here is some documentation related to these resources that are held in the public folder:
https://vitejs.dev/guide/assets.html#the-public-directory
The cache was cleared and the outbound request was inspected to check that the image was pulling from the correct location.
-   [ ] Breaking change (fix or feature that would …
=> fix: use root path instead of relative path for img src

.env.example, docker-compose.dev.yml, docker-compose.testing.yml, examples/docker-compose/.env.example, examples/docker-compose/docker-compose.yml
In the current scripts a wrong environment variable is used for the postgres database and therefore the current variable has no influence on the name of the postgres database. When creating the postgres database, the default behavior of postgres is currently applied (username as database name).
The pull request simply replaces the incorrect variable `POSTGRES_DATABASE` with the correct `POSTGRES_DB` (See https://hub.docker.com/_/postgres) so that this functionality can be used correctly. 
A new container with a customized database name was created and verified within the container.
-   [ ] …
=> Fix environment variable for postgres database

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Adds Server 2012 to list of unsupported operating systems cypher query.
Server 2012 is EOL.
Tested query in dev environment.
n/a
-   [ X ] Chore (a change that does not modify the application functionality)
=> Update unsupported OS cypher query to include Server 2012

cmd/api/src/api/agi_test.go, cmd/api/src/api/registration/v2.go, cmd/api/src/api/v2/agi.go, cmd/api/src/database/agi.go, cmd/api/src/docs/json/definitions/models.json, cmd/api/src/docs/json/definitions/v2.json, cmd/api/src/docs/json/paths/v2/asset-isolation.json
- Adds the `POST /v2/asset-groups/{asset_group_id}/selectors` endpoint into BHCE
- Fixes a bug that caused this endpoint to always return empty lists of selectors
- Updates the documentation to reflect the correct request/response types for this endpoint
We are building a new asset group management page, which will need the ability to add and remove asset group selectors.
- This handler has existing tests that were ported over along with it
-   [x] Documentation updates are needed, and have been made …
=> Add "Update Asset Group Selectors" endpoint

cmd/api/src/analysis/ad/post.go, packages/cue/bh/ad/ad.cue, packages/go/analysis/ad/adcs.go, packages/go/analysis/ad/post.go, packages/go/graphschema/ad/ad.go, packages/javascript/bh-shared-ui/src/graphSchema.ts
The handlers that were created for post processing TrustedForNTAuth, IssuedSignedBy, and EnterpriseCAFor have been wired up to actually run during post processing.
This moves us closer to integrating all of the ADCS post processing logic.
Analysis was initiated on the dataset collected for the esc1 environment. No analysis errors were logged but we may need to insure the expected edges are being created.
-   [ ] I have added …
=> chore: wire up post processing for currently existing adcs handlers

cmd/api/src/api/v2/agi.go, cmd/api/src/api/v2/agi_internal_test.go, cmd/api/src/api/v2/agi_test.go
The /api/v2/asset-groups/:assetGroupId/members endpoint was returning an empty response in some environments due to a panic caused by type conversions of the form 
`somevar := someval.(string)` .  
The offending type conversions in the `GetAssetGroupNodes` function are covered by this PR
-   [ ] My changes include a database …
=> Better hygiene on asset group members endpoint

packages/cue/bh/ad/ad.cue, packages/go/ein/ad.go, packages/go/graphschema/ad/ad.go, packages/javascript/bh-shared-ui/src/graphSchema.ts, packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.test.ts, packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.ts
This PR alters the data we are storing for the Computer property `CertificateMappingMethods`. When implemented we were storing this as a string that contained the hexadecimal representation of the integer that is stored in the registry. This  format was difficult to work with in code, so we are making the change to store it as the raw integer instead.
We still want to be sure to display the hex value as that is a better representation of how the setting is used. I added some additional formatting to the Entity Panel formatting to display both the int value and hex value in special circumstances like this.
* Make the `CertificateMappingMethods` value more useful on the code side while still preserving the hex value in the Entity Panel
* Locally verified that the property is displaying …
=> Store raw CertificateMappingMethods integer value

packages/go/ein/ad.go
Handle when DC registry values do not exist.
It is possible that the registry values we want to collect do not exist. Sharphound will return -1 for integer values in this case.
We will store the value as is and make the user aware that the value does not exist: 
Uploaded positive int values, 0 values, and -1 values.
-   [ ] …
=> feat: handle dc reg values not existing

packages/javascript/bh-shared-ui/src/commonSearches.tsx
- Added '8' to match Windows 8.
- Added 'nt' to match Windows NT.
- "NT" is also seen in many community-made Cypher and PowerShell queries searching for unsupported OS.
- Added a space before the version number, to not match false-positives containing "nt" like "Windows 2022 Datacenter"
- Added a requirement of "Windows" before the version number to remove false positives, as some non-Windows OS will have a version number starting with 8, 7, etc.
- This may filter out true-positives of non-Windows OS versions with the years 2010, 2012, etc. These are most likely out of date too, for example "Mandriva Linux 2010". However, I believe this Cypher query was never thought to catch such guesswork cases.
- Windows 8, 8.1, and NT are EOL.
- I have before seen false-positives when using the query. …
=> Update unsupported OS cypher query to include Windows 8 and Windows NT, and remove false positives

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Several pre-saved Azure queries included poorly formatted Cypher, or would never match.
- Updated high-value roles variable to use regex to match queries
- Updated for consistent `AND m<>n`
- Fixed Cypher typo
Fix accuracy of provided queries
Tested in local environment and in hosted test.
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] My changes include a …
=> BED-3845 - Improve and fix Azure saved queries

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Fixed the cypher query for 'Shortest paths from Kerberoastable users', which was returning incorrect results.
Actually, it was the same as 'Shortest paths to systems trusted for unconstrained delegation'.
The query returned 'Shortest paths to systems trusted for unconstrained delegation' instead of 'Shortest paths from Kerberoastable users'.
Run the query and obtained expected results.
-   [ ] I have added and/or updated tests …
=> Fix query for 'Shortest paths from Kerberoastable users'

cmd/api/src/database/migration/stepwise.go
This will prevent the stepwise migrator from adding additional entries for the same version
Due to how the stepwise migrator runs, we were stamping a new version in the migrations database on every app restart, even if that version already existed. This change will ensure it only stamps the new version if the last migration and the current version aren't the same.
Validated locally with test harness
-   [ ] I have added and/or …
=> fix: stepwise was making new migrations on every restart

cmd/api/src/database/migration/migrations/v5.3.0.sql
This PR adds additional columns to the `ad_data_quality_stats` and `ad_data_quality_aggregations` tables to support collecting stats for new nodes being collected from ADCS. This migration is necessary as Gorm auto-migrations were removed as part of #159.
* These columns are used to store counts of the new node types that are now being collected for ADCS
* Verified the migration successfully adds the new columns.
-   [ ] I have …
=> Migrate data quality tables for new ADCS nodes

cmd/api/src/config/config.go, cmd/api/src/config/reflect.go, cmd/api/src/config/reflect_test.go
Fixes a bug that caused config keys with more than one underscore to not be parsed.
Regression tests have been added to avoid further issues
The previous env var fixes introduced a bug when attempting to find the end of a key when the key contains multiple underscores
Additional tests have been added and various configurations with varying numbers of underscores and path segments were reviewed to ensure we have coverage for variations of path sizes and variations of multiple underscores per key.
-   [ …
=> fix: disable_cypher_qc and other 3+ segment JSON keys

cmd/api/src/daemons/datapipe/convertors.go
Create the Contains edges from the ContainedBy property for the ADCS objects.
This aligns with BED-3177 ticket where the same was done with our existing node types.
We need this change to create Contains edges for ADCS objects.
Tested with my lab.
=> fix: Contains edges from DN for ADSC objects

packages/cue/bh/ad/ad.cue, packages/go/analysis/ad/post.go, packages/go/graphschema/ad/ad.go, packages/javascript/bh-shared-ui/src/graphSchema.ts
Removed all references to the not implemented yet ADCSESC2 edge.
We have decided not to create ESC2 as an edge as it is not abusable to compromise any principal on its own.
=> remove ADCSESC2

packages/javascript/bh-shared-ui/src/components/HelpTexts/DelegatedEnrollmentAgent/DelegatedEnrollmentAgent.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/DelegatedEnrollmentAgent/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/DelegatedEnrollmentAgent/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/DelegatedEnrollmentAgent/Opsec.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/DelegatedEnrollmentAgent/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/DelegatedEnrollmentAgent/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/EnrollOnBehalfOf/EnrollOnBehalfOf.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/EnrollOnBehalfOf/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/EnrollOnBehalfOf/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/EnrollOnBehalfOf/Opsec.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/EnrollOnBehalfOf/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/EnrollOnBehalfOf/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/GoldenCert.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/Opsec.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/HostsCAService/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/HostsCAService/HostsCAService.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/HostsCAService/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/HostsCAService/Opsec.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/HostsCAService/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/HostsCAService/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/utils.ts
Help text for the entity panel of the three ADCS edges:
- HostsCAService
- DelegatedEnrollmentAgent
- EnrollOnBehalfOf
- GoldenCert
Also fixed the display version of the new node type names so {typeFormat(sourceType)} return "certificate template" rather than "certtemplate".
We need help texts for all edges.
Ran it and checked it looked good.
-   [ ] All new and …
=> BED-3869: ADCS edges help text

cmd/api/src/daemons/datapipe/convertors.go, cmd/ui/src/ducks/entityinfo/types.ts, packages/cue/bh/ad/ad.cue, packages/go/ein/ad.go, packages/go/graphschema/ad/ad.go, packages/javascript/bh-shared-ui/src/graphSchema.ts
Add properties `IsUserSpecifiesSanEnabled` and `HasEnrollmentAgentRestrictions` to EnterpriseCA nodes.
We currently only store if these properties are collected, but not their values. We need these EnterpriseCA attributes as properties so we can check them in the post-processing logic for ESC3 and ESC6.
Ingested data from my lab with two EnterpriseCAs - one where these properties are collected and one where they are not.
-   [ ] …
=> Add EnterpriseCA registry properties

packages/go/ein/azure.go
Added function to check if a resource belongs to a scope either by full ID or inherited by resource group.
This check uses case-insensitive matching due to reasons explained below.
It also checks if the scope is at resource group level and will grant inherited relationship if the resource is prefixed with the scope.
When importing data from AzureHound, the virtual machine ID sometimes does not match the casing of the scope which results in relationships such as AZVMAdminLogin is not registered.
Additionally, relationships were only registered if a direct role assignment to the resource was added and ignored resource group inheritance.
From [docs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules):
> Resource and resource group names are …
=> Fix import of relationships with wrong casing

cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.test.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
Fallback to 0 for `EntityInfoDataTable` count when `countQuery` returns empty.
Previously when the count query returned empty for a given node, and that node was in a group of other Node Kinds, the sum of all counts return `NaN`. Preferably if a count is empty, it should be counted and displayed as 0 and not block other node counts from being summed.
Manual tests:
- empty `countQuery` response, 
- failed network requests, 
- countQuery returning results
Added integration test to cover the different states a node count can be in.
-   [ ] Breaking change (fix or feature that would cause …
=> Entity info count fallback

cmd/api/src/analysis/ad/post.go, cmd/api/src/api/middleware/middleware.go, cmd/api/src/api/registration/v2.go, cmd/api/src/api/router/router.go, cmd/api/src/daemons/datapipe/analysis.go, cmd/api/src/daemons/datapipe/convertors.go, cmd/api/src/daemons/datapipe/ingest.go, cmd/api/src/model/appcfg/flag.go, packages/go/analysis/ad/adcs.go
This PR creates a new feature flag for enabling ADCS related endpoints, ingest logic, and post-processing logic. The feature flag is disabled by default to enable limited testing for specific scenarios. This should prevent widespread errors if there are unknown bugs in the new feature code.
A new middleware was added to allow easy addition of feature flag checking logic to any endpoint in the BloodHound API. The middleware just needs to be added to the registration of the protected endpoints, passing in the flag that controls the behavior. If the flag is disabled, a 404 will be returned to the requester.
* This should help prevent breaking everyone's BloodHound instance if there are unknown bugs in the new ADCS code.
* Verified the feature flag is set to `enabled=false` on a fresh …
=> Create ADCS feature flag and wrap associated code

cmd/api/src/database/migration/migrations/schema.sql
Remove BHE schema from BHCE
When fixing Gorm automigrate, we accidentally included BHE specific schema in our main schema file. This resolves the issue and allows us to release the next BHCE version without making unnecessary tables for users
Migrations run correctly with the missing tables. Spot checked all references to the removed schema by hand.
-   [x] All new …
=> fix: remove BHE schema from schema file

packages/go/analysis/ad/adcs.go
This PR fixes a bug in ADCS post-processing that caused it to exit the loop after successfully post-processing the first `EnterpriseCA`.
* Fix the bug to allow all `EnterpriseCAs` to be post-processed.
=> Fix ADCS post-processing bug

cmd/ui/src/views/Users/Users.tsx, packages/javascript/bh-shared-ui/src/components/Disable2FADialog/Disable2FADialog.test.tsx, packages/javascript/bh-shared-ui/src/components/Disable2FADialog/Disable2FADialog.tsx
Adds a warning message as to potential vulnerabilities when MFA is disabled. This warning is **only** present in the `Disable2FADialog` found at admin -> Manage Users -> hamburger menu for users with MFA enabled -> disable MFA. Not present on the user's profile page when going to turn off MFA, however, we can add it there if necessary.
Sufficiently warn the admin before disabling a user's MFA.
Tested BHE, BHCE for the warning to be present from the admin perspective and NOT from the user profile perspective.
-   [ ] Breaking change (fix or feature that would cause existing functionality to …
=> Warning when disabling MFA

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Occasionally, casing will not get fully to-uppered during ingest. Modifying query to account for this.
Accuracy in use of default searches
Validated locally
=> BED-3924: Update Domain Users RDP searches for case sensitivity

cmd/api/src/daemons/datapipe/models.go
The collection methods available ADCS are being split a little more than originally defined. This changeset updates our collection method definitions in the API to reflect these updates.
It was desired to split out the collection methods for ADCS so that there is an option to isolate data retrieved from LDAP into it's own collection method, CertServices, rather than combining it into CA Registry Collection.
Associated changes made on the collector side are not available yet. 
-   [ ] Documentation …
=> chore: partition collection methods to split out ldap source in its own option

cmd/api/src/api/bloodhoundgraph/bloodhoundgraph.go, cmd/ui/src/ducks/entityinfo/types.ts, cmd/ui/src/ducks/searchbar/types.ts, cmd/ui/src/views/Explore/EntityInfo/EntityInfoContent.test.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoContent.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.test.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTableList.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoHeader.tsx, cmd/ui/src/views/Explore/ExploreSearchCombobox/ExploreSearchCombobox.test.tsx, cmd/ui/src/views/Explore/fragments.tsx, cmd/ui/src/views/Explore/utils.ts, cmd/ui/src/views/QA/index.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC1/Composition.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/Composition.tsx, packages/javascript/bh-shared-ui/src/components/HighlightedText/HighlightedText.test.tsx, packages/javascript/bh-shared-ui/src/components/VirtualizedNodeList.tsx, packages/javascript/bh-shared-ui/src/hooks/useDataQualityStats.tsx, packages/javascript/bh-shared-ui/src/utils/content.ts, packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.ts, packages/javascript/bh-shared-ui/src/utils/index.ts
This moves the content file for the entity info sections to the shared ui.
These views should be available in BHE and this changeset consolidates the content.
This is mostly code reorganization. The app builds and functions as before.
=> chore: move entity content file to shared ui and update icon colors in bh graph go file

cmd/api/src/database/migration/migrations/v5.3.0.sql
Remove unused indexes auto created by GORM.
Clean up extra constraints on `asset_group_selectors` and only use `asset_group_selectors_name_assetgroupid_key UNIQUE (name, asset_group_id)`
`just test -a`
-   [x] My changes include a database migration.
=> drop all unused keys

README.md, cmd/api/src/api/v2/saved_queries.go, cmd/api/src/api/v2/saved_queries_test.go, cmd/api/src/database/migration/migrations/v5.3.1.sql, cmd/ui/src/ducks/searchbar/reducer.ts, cmd/ui/src/views/Explore/ExploreSearch/EdgeFilteringDialog.test.tsx, cmd/ui/src/views/Explore/ExploreSearch/EdgeFilteringDialog.tsx, cmd/ui/src/views/Explore/fragments.tsx, packages/javascript/bh-shared-ui/src/commonSearches.tsx, packages/javascript/bh-shared-ui/src/components/Disable2FADialog/Disable2FADialog.test.tsx, packages/javascript/bh-shared-ui/src/components/Disable2FADialog/Disable2FADialog.tsx, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/index.ts
This PR moves the `edgeTypes` definitions out of version-specific UI code and into `bh-shared-ui`. They are the same in both versions of BloodHound.
* Desire to stop making the same updates in multiple places
* Updated tests where needed
* Verified in the UI that the correct edge types are showing in the Edge Filter
-   [ ] …
=> Move edgeTypes to shared UI

cmd/api/src/database/migration/migrations/v5.3.1.sql
A hotfix migration to add necessary indexes to `asset_group_collections` and `asset_group_collection_entries`, allowing them to scale to larger data sets. This migration will also truncate `asset_group_collection_entries` to reset table size in live environments.
We sometimes see these tables get large enough that operations on them slow way down due to lack of good indexes. This migration aims to add indexes for fields that are likely to be referenced during normal application operation.
Migrations were tested for expected results locally. This was done by spinning up local dev, removing the v5.3.1 entry (since it was created during development) and restarting the API (saving the file was enough to kick off a hot reload). Migration gave no errors and expected indexes and truncation …
=> fix: add necessary indexes for table optimization

cmd/api/src/model/jobs.go
The column names in the domain_collection_results table are set to be overridden.
Gorm uses snake case to relate structs to tables but our migration was not in that form so writing the data point resulted in an error. 
A collection was run with the updated changes and the error observed originally was no longer logging.
- …
=> fix: gorm override column names for domain_collection_results

cmd/api/src/api/v2/edge.go, cmd/api/src/docs/json/paths/v2/aiaca-entity.json, cmd/api/src/docs/json/paths/v2/certtemplate-entity.json, cmd/api/src/docs/json/paths/v2/enterpriseca-entity.json, cmd/api/src/docs/json/paths/v2/graphs.json, cmd/api/src/docs/json/paths/v2/jobs.json, cmd/api/src/docs/json/paths/v2/ntauthstore-entity.json, cmd/api/src/docs/json/paths/v2/rootca-entity.json
This PR makes some tweaks to the API docs around the new endpoints added to support ADCS nodes and edges. The major change is adding a notice to each of the new edges to signify they are in early access and the structure might change before full release. Also, API documentation was added for the `/api/v2/edge-composition` endpoint. A bug was also fixed when passing in an invalid `edge_type` to that endpoint. Lastly, some minor tweaks and improvements to documentation were made.
* Clearly communicate that the new API endpoints are subject to change.
* Fix bugs for readability and consistency.
* Verified the endpoints show the correct information on the API Explorer page.
-   [ ] Bug fix (non-breaking change which …
=> ADCS API Doc Updates

cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItem.test.tsx
Updates `AssetGroupMenuItem` tests to mock the PUT endpoint instead of the previous POST endpoint
POST `/api/v2/asset-groups/:assetGroupId/selectors` was deprecated and replaced with a PUT endpoint in this PR: https://github.com/SpecterOps/BloodHound/pull/268
Manual and automated tests
=> Asset group mock endpoint

cmd/api/src/analysis/ad/adcs_integration_test.go, packages/go/analysis/ad/adcs.go
Remove special requirements for CertTemplate of schema version 1 to get an EnrollOnBehalfOf edge to itself.
There are no specific requirements for CertTemplate of version 1 to have an EnrollOnBehalfOf edge to itself except that it has the enrollment agent EKU. We can remove the checks we have in place that prevent the creation of the edge to the same CertTemplate of version 1, and we can delete the code that checks for the specific scenario that we currently for this edge type. 
Tested with my lab data.
Getting the expected edges:
-   [ ] Breaking change (fix or feature that would cause …
=> fix: More EnrollOnBehalfOf to self scenarios

cmd/api/src/analysis/ad/post.go, cmd/api/src/analysis/analysis_integration_test.go, packages/go/analysis/ad/post.go
- Parameterizes the enforcement of URA during LocalGroup processing
BloodHound Enterprise and BloodHound Community edition have different requirements when assigning CanRDP edges. This change parameterizes LocalGroup processing and removes duplicate code thus reducing the chance of regression.
I have updated the existing integration tests to include testing this change.
-   [x] I have added and/or updated tests to cover my …
=> refactor: parameterize ura enforcement for CanRDP processing

packages/go/analysis/analysis.go, packages/go/analysis/analysis_test.go
If you add additional labels to the nodes after the import (e.g. for some advanced APOC queries), these are added at a random position within the label list. With Bloodhound, the last label in the list is always selected and displayed into the GUI, even if it cannot be rendered. 
Here is an example:
A node with the following labels
results in the following GUI node:
The change ensures that nodes can only be assigned to valid types so that they are subsequently rendered correctly in the GUI. 
A new container with a customized code was created and verified.
-   [ ] Breaking change (fix or …
=> Make sure that only valid labels are displayed

cmd/api/src/api/registration/v2.go, cmd/api/src/docs/json/paths/v2/jobs.json, packages/javascript/bh-shared-ui/src/commonSearches.tsx, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx
ESC3 is added to the filter options for pathfinding searches via the UI. Adding this checkbox also adds it to the default list of traversed edges during pathfinding. 
These options support ESC 3 edge incorporation. 
=> feat: incorporate esc3 in ui pathfinding default and add filter checkbox

cmd/api/src/api/registration/registration.go
This PR fixes the order middleware is initialized so that the request context can be accessed within the `LoggingMiddleware`. The `LoggingMiddleware` was previously initialized before `ContextMiddleware`, causing `request.Context()` to be empty inside of the log middleware.
Two of the log fields, `request_id` and `elapsed` relied on values in the request context to generate properly. With this fix these fields should now be populated in log lines.
* Ensure `request_id` and `elapsed` have correct values in the logs
* Make `request.Context()` accessible in `LoggingMiddleware` so it can be used for other calculations
* Verified that those two fields are correctly populated in my dev environment's logs
Before:
```
bh-api-1        | {"level":"info","remote_addr":"172.23.0.4:57916","proto":"HTTP …
```
=> Fix empty request_id and incorrect elapsed time in logs

cmd/api/src/database/audit.go, cmd/api/src/database/audit_test.go, cmd/api/src/database/saved_queries.go, cmd/api/src/database/saved_queries_test.go
Counts in a couple of paginated responses do not accurately respect filtering and instead return the count in the non-filtered case. This is present in:
- AuditLogs GET `/audit`
- SavedQueries GET `/saved-queries`
This fixes the above issue.
Two integration tests were added to verify filter counts were respected
-   [ ] My …
=> Bed 3859 - Fix inaccurate count strategy in paginated SQL queries

packages/go/analysis/ad/filters.go, packages/go/analysis/ad/filters_test.go
GPOs don’t apply to groups.  Groups can be used as filters for GPOs but you can’t take control over a group through a GPO.  Our entity panel for GPOs incorrectly shows Groups when expanding the affected objects accordion, then expanding Tier Zero objects.  The query for this should only account for the following objects: Domains, Users, Computers, OUs. 
Fix query to properly filter groups.
Before and after change was compared against local data that reproduced this behavior.
A unit test verifying logic paths was added.
-   [ ] Breaking change (fix or feature that would cause existing …
=> fix: Filter out group nodes from GPO affected T0 queries

dockerfiles/bloodhound.Dockerfile, tools/docker-compose/api.Dockerfile
This change makes SharpHound version 2.3.1 available for download via BloodHound Community Edition.
=> chore: bump available SharpHound version to 2.3.1

local-harnesses/build.config.json.template
https://github.com/SpecterOps/BloodHound/commit/7787b6baf17b54536411b626fd40ba517c27f023 breaks the development build (just bh-dev). 
The traefik proxy can't connect to the api when the service is only listening on localhost.
=> Revert ip bind to 0.0.0.0

.github/workflows/static-code-analysis.yml, .golangci.json, .vscode/settings.json, cmd/api/src/analysis/ad/adcs_integration_test.go, cmd/api/src/test/integration/harnesses/utils.go, docker-compose.watch.yml, justfile
- Adds a new static analysis pipeline to GitHub Actions to enforce our static analysis rules going forward
- Resets the static analysis config to sane defaults. This includes moving some ignored rules to warnings so they can eventually be tackled.
- Adds `just analyze` command using St Bernard. The results are filtered and prettified by `jq` for better local dev ergonomics (you can click the links to go directly to the line)
- Includes fixes for triggered error rules
No broken windows
- Local runs of the analyzer match expectations and complete as expected
- Pipeline tested several times to ensure consistent results
=> feat: static analysis plumbing for BHCE

cmd/api/src/api/v2/file_uploads.go, cmd/api/src/api/v2/file_uploads_test.go, cmd/api/src/daemons/datapipe/datapipe.go, cmd/api/src/daemons/datapipe/jobs.go, cmd/api/src/daemons/datapipe/mocks/mock.go, cmd/api/src/model/jobs.go, cmd/api/src/services/fileupload/file_upload.go, packages/javascript/bh-shared-ui/src/components/FinishedIngestLog/types.ts
This changeset removes several unnecessary components of the data pipeline. The original intent for the in-memory retention of completed file upload jobs was to trigger analysis immediately upon completion of file-upload. However, addition of configuration for the loop ticker and a clearer path for triggering a data pipeline loop run removes the need for this complexity.
This also removes a gap where a timed out file upload job could have its status overwritten later on during analysis.
The data pipeline is already complex enough, as-is. Let's not make it harder on ourselves to maintain this part of the system.
Updated unit tests.
-   [ ] New feature …
=> chore: remove unnecessary complexity in the data pipeline

cmd/api/src/analysis/ad/adcs_integration_test.go, cmd/api/src/test/integration/harnesses.go, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.tsx, cmd/ui/src/views/Explore/ExploreSearchCombobox/ExploreSearchCombobox.tsx, packages/go/analysis/ad/ad.go, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC6a/ADCSESC6a.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC6a/Composition.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/utils.ts
This changeset enables viewing the ESC6a edge composition from the edge information pane.
The current 6a edge information pane does not have the composition accordion implemented.
Integration tests have been updated to check for composition details.
=> feat: esc6a edge composition

cmd/api/src/daemons/datapipe/datapipe.go, cmd/api/src/daemons/datapipe/jobs.go, cmd/api/src/daemons/datapipe/jobs_test.go, cmd/api/src/services/fileupload/file_upload.go, packages/go/analysis/ad/adcs.go
This adds an ingest task lookup before transitioning file upload jobs from the `INGESTING` state to the `ANALYZING` state. There is a potential race where a job may transition into `INGESTING` after `ingestAvailableTasks(...)` is called. In this rare case, ingest tasks would remain until the next datapipe loop tick. Upon ingestion of the remaining tasks analysis would not be triggered, leaving the system in a inconsistent state until the next analysis run.
Additionally, this changeset contains a change in the ADCS post-processing logic that defers creation of a parallel operation context. The functions that previously ran between creation of the parallel operation context would spin up their own parallel operation contexts resulting in creation of 12+ concurrent connections to the …
=> Datapipe State Transition Hardening and ADCS Post Processing Fixes

cmd/api/src/analysis/ad/adcs_integration_test.go, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.tsx, packages/go/analysis/ad/ad.go, packages/go/analysis/ad/esc_shared.go, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10a/ADCSESC10a.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10a/Composition.tsx
Adds ESC10a Edge Composition
See description
Added a test to an existing harness to validate the logic and tested with lab data
=> ESC10a Edge Composition

packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx
Adds 10a and 10b escalation edges to pathfinding filter list and default list.
=> feat: add esc10 edges to path filter and default list

cmd/api/src/auth/role.go, cmd/api/src/auth/role_test.go
It was determined after https://github.com/SpecterOps/BloodHound/pull/343 was merged that the ReadOnly role lacks the ability to manage their own auth tokens.
The ReadOnly role should have access to manage own auth tokens.
A new integration test was added
=> fix: read only missing AuthCreateToken

cmd/api/src/api/registration/v2.go, cmd/api/src/api/v2/file_uploads_integration_test.go, cmd/api/src/daemons/datapipe/convertors.go, cmd/api/src/daemons/datapipe/ingest.go, cmd/api/src/model/appcfg/flag.go, cmd/api/src/test/integration/harnesses/harnessgen.py, packages/go/analysis/ad/adcs.go
Remove the ADCS feature flags in preparation for GA of ADCS
See description. The feature flag will still remain in play, but will only block upcoming ADCS work (B edges)
Existing tests continue to work, post processing is working as expected
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
=> Remove ADCS feature flag gates

cmd/api/src/api/auth.go, cmd/api/src/api/saml/saml.go, cmd/api/src/api/saml/saml_internal_test.go, cmd/api/src/auth/model.go, cmd/api/src/config/config.go, cmd/api/src/config/default.go
Support a new configuration parameter auth_session_ttl_hours and the corresponding environment variable BHE_AUTH_SESSION_TTL_HOURS for setting authenticated login session time to live values.
Allow the auth session TTL to be configurable.
=> feat: BED-4099 - Provide Configurable Auth Session TTL

cmd/api/src/api/middleware/middleware.go
This PR changes the logging level for a missing `X-Forwarded-For` to debug as it was proving to be a bit noisy. There was also a typo fix to another log line in the same area.
* Reduce unnecessary noise in the logs
* Verified the log only displays when debug logging is enabled
=> Reduce noise when X-Forwarded-For is missing

cmd/api/src/model/jobs.go
This adds a function to enumerate the intended visible job statuses for use when querying upload jobs for display purposes.
This will centralize usage of this sub-set of job statuses instead of having them replicated across different locations in the codebase.
=> chore: Add a Visible Job Status Function

packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/LinuxAbuse.tsx
There was a command missing in a couple of the linux abuse texts. Fixed that.
Also fixed a related command for granting DCSync a couple of places.
=> docs: missing linux clean up command

tools/docker-compose/pgadmin.Dockerfile
Currently the pgadmin does not properly insert the provided pw file into the pgadmin docker container so each time you reload the stack, you must manually provide the password.
I don't want to manually put the password in every time because I'm lazy.
Rebuild your docker container for pgadmin
Run `just bh-dev`
-   [ ] My …
=> fix: incorrect pgadmin dockerfile pw

cmd/api/src/database/migration/migrations/v5.6.0.sql
Add feature flag migration to v5.6.0 migration to remove ADCS feature flag.
Now that ADCS is released, the feature flag is no longer necessary.
Verified SQL against local db.
-   [] Bug fix (non-breaking change which fixes an issue)
-   [x] My changes include a database migration.
=> chore: add feature-flag migration to v5.6.0 migration

cmd/api/src/database/migration/migrations/v5.6.0.sql
The ADCS feature flag is defaulted to true in the migration, but needs to be defaulted to false
False is not true and we want it to be false.
Migration ran and it set the FF to false
-   [x] My changes include a database migration.
=> fix: feature flag default

cmd/api/src/api/agi.go, cmd/api/src/api/registration/v2.go, cmd/api/src/api/v2/agi.go, cmd/api/src/api/v2/agi_test.go, cmd/api/src/docs/json/definitions/v2.json, cmd/api/src/docs/json/paths/v2/asset-isolation.json
The group management page makes duplicate /members requests in order to get the total counts across primary kinds. This is resource intensive and redundant db hits for the same resources.
Decrease the DB load on neo4j as only 1 request needs to be made to obtain the group member counts
Tested against test db
Integration test added
-   [x] All new and existing tests …
=> feat: Add /count endpoint to /asset-group/:assetGroupId/members endpoint

cmd/ui/src/App.tsx, cmd/ui/src/components/AuthenticatedRoute/AuthenticatedRoute.tsx, cmd/ui/src/components/GraphButtons/GraphButtons.tsx, cmd/ui/src/components/GraphEdgeEvents.tsx, cmd/ui/src/components/GraphEvents.tsx, cmd/ui/src/components/Notifier.tsx, cmd/ui/src/store.ts, cmd/ui/src/views/Content.tsx, cmd/ui/src/views/ExpiredPassword.tsx, cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItem.tsx, cmd/ui/src/views/Explore/ContextMenu/ContextMenu.tsx, cmd/ui/src/views/Explore/ContextMenu/CopyMenuItem.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoCollapsibleSection.tsx, cmd/ui/src/views/Explore/ExploreSearch/CypherSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/EdgeFilter.tsx, cmd/ui/src/views/Explore/ExploreSearch/EdgeFilteringDialog.tsx, cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/NodeSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/PathfindingSwapButton.tsx, cmd/ui/src/views/Explore/GraphView.tsx, cmd/ui/src/views/Explore/Search/Menu/MenuContainer.tsx, cmd/ui/src/views/GroupManagement/GroupManagement.test.tsx, cmd/ui/src/views/GroupManagement/GroupManagement.tsx, cmd/ui/src/views/Login.tsx, cmd/ui/src/views/QA/QA.tsx, cmd/ui/src/views/Users/Users.tsx
This PR mostly improves types so that we dont have to specify `AppState` every time we use `useSelector`. There are a couple of changes to support the more accurate types but nothing that changes functionality.
Using `useAppSelector` instead of the generic `useSelector` reduces imports, slightly increases readability, and helps make sure we use types from the redux store. There are a couple places in the app where we use the `any` type for redux state which isnt ideal.
Regression testing any non type-only changes and updated unit tests.
=> useAppSelector

packages/go/dawgs/traversal/id.go
The count that coordinates exit of traversal workers must be decremented before a notification event is sent via the completion channel.
If this is done out of order it's possible for channel starvation to occur.
Local test with dataset.
=> fix: ID Traversal Critical Section in Wrong Order

cmd/api/src/api/registration/v2.go, cmd/api/src/api/v2/file_uploads.go, cmd/api/src/api/v2/file_uploads_test.go, cmd/api/src/docs/json/paths/v2/file_upload.json
This adds GET endpoint `/accepted-types` to /file-uploads for consumption by the UI to support MIME type validation.
In order to allow for UI side validation but not need to maintain multiple areas, we want to add an endpoint that returns supported types. 
Locally hit endpoint GET `api/v2/file-upload/accepted-types`
Added integration test as well
-   [x] All new and …
=> feat: add /accepted-types endpoint to file-uploads

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Many of the saved cypher queries used `system_tags = 'admin_tier_0'` which will break when the system_tags field contains multiple tags. Updating to use `CONTAINS` instead for accuracy.
Improve query accuracy
Tested in local env
=> Improved accuracy on saved queries for tags

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Updating to reflect that a group tag could contain the substring "admin_tier_0" and inaccurately match where unintended.
Accuracy of searches and results.
Tested in local environment
-   [X All new and existing tests passed.
=> Update for additional accuracy in Cypher searches

cmd/api/src/api/marshalling.go, cmd/api/src/api/marshalling_test.go, cmd/api/src/api/middleware/rate_limit.go, cmd/api/src/api/middleware/rate_limit_test.go
- Removed the context timeout check from inside the response marshalling utility functions
- Removed an incorrect error that occurred during rate limits
Response marshalling was dependent on the request context checking for deadline timeout which was causing race conditions between writing the JSON and the request context timing out. This sometimes resulted in an errant empty 200 response. 
While cleaning these up, the rate limit error middleware was returning an incorrect response that was both confusing and used the wrong status code.
Integration tests hopefully all passed but definitely want to soak this puppy to make sure I didn't miss any.
-   [ ] New …
=> refactor: remove context timeout check from response marshalling

packages/go/cypher/frontend/pattern.go, packages/go/cypher/frontend/query.go, packages/go/cypher/frontend/util.go, packages/go/cypher/test/cases/positive_tests.json
This change works around some minor deficiencies in the ANTLR generated parser for openCypher to correctly parse pattern ranges.
As written, the openCypher parser would incorrectly set the starting range index of a pattern when only an ending range index is specified.
This was discovered while attempting to perform ranged pattern matching: `match p = (:User)<-[*1..3]-(t:Base) where t.name = 'example' return p`.
The above query was being parsed and emitted as: `match p = (:User)<-[*3..]-(t:Base) where t.name = 'example' return p` which would then result in an unbounded traversal and crash Neo4j.
An additional test case was added to cover this.
-   [ ] New …
=> fix: cypher pattern range parsing

cmd/ui/src/views/GroupManagement/GroupManagement.test.tsx, cmd/ui/src/views/GroupManagement/GroupManagement.tsx, packages/javascript/bh-shared-ui/src/components/GroupManagementContent/GroupManagementContent.tsx
Fixes blank group management page when globalDomain is null. 
We should display something if globalDomain is null to give the appearance that things are not broken.
Manual test and added unit test
=> Fix: Missing Group Management Page (stage/v5.7.0)

cmd/api/src/api/v2/apiclient/agi.go, cmd/api/src/database/agi.go, cmd/api/src/database/db.go, cmd/api/src/database/mocks/db.go
This PR removes some database function (and the corresponding mock functions) that are no longer used across the code base for tidiness.
I also updated the `CreateAssetGroupSelector` API client function to use a `PUT` instead of a `POST` as the latter has been deprecated. While fixing this I noticed that the response body didn't match the struct we were trying to parse into, so I updated that to match as well.
* Clean code is happy code
* Existing tests still pass
-   [ ] Documentation updates are …
=> Remove unused agi code

cmd/api/src/analysis/azure/azure_integration_test.go, cmd/api/src/analysis/azure/base.go, packages/go/analysis/azure/application.go, packages/go/analysis/azure/automation_account.go, packages/go/analysis/azure/container_registry.go, packages/go/analysis/azure/db_ops.go, packages/go/analysis/azure/device.go, packages/go/analysis/azure/filters.go, packages/go/analysis/azure/function_app.go, packages/go/analysis/azure/group.go, packages/go/analysis/azure/key_vault.go, packages/go/analysis/azure/logic_app.go, packages/go/analysis/azure/managed_cluster.go, packages/go/analysis/azure/management_group.go, packages/go/analysis/azure/queries.go, packages/go/analysis/azure/resource_group.go, packages/go/analysis/azure/service_principal.go, packages/go/analysis/azure/subscription.go, packages/go/analysis/azure/tenant.go, packages/go/analysis/azure/user.go, packages/go/analysis/azure/vm.go, packages/go/analysis/azure/vm_scale_set.go, packages/go/analysis/azure/web_app.go
Added AZContains to the traversal strategy for both inbound and outbound control entities
Removed redundant `direction` argument from `FetchXEntityObjectControllers`
Removed unused `sortBy`  function in testing file
Currently AZContains is ignored by the inbound / outbound controllers making it appear as though some Azure entities have 0 inbound control entities when that is not the case. This fixes that bug.
Removal of the direction from the FetchXEntityObjectControllers functions IMO helps prevent an issue where a developer may call an OutboundController with a direction.Inbound resulting in a bugged response. I didn't see any of those instances but felt it best to prevent that going forward.
Tested locally as well as added to integration tests.
-   [ ] Chore (a change that does not …
=> fix: not including AZContains in inbound / outbound control traversal

cmd/api/src/api/error.go, cmd/api/src/api/v2/agi.go, cmd/api/src/api/v2/agi_test.go, cmd/api/src/daemons/datapipe/agi.go, cmd/api/src/database/agi.go, cmd/api/src/database/agi_test.go, cmd/api/src/database/audit.go, cmd/api/src/database/db.go, cmd/api/src/database/migration/agi_integration_test.go, cmd/api/src/database/mocks/db.go, cmd/api/src/queries/graph.go, cmd/api/src/services/agi/agi.go, cmd/api/src/services/agi/mocks/mock.go
Plumb context into gorm asset-group db methods
I also noticed there was a number of unused db methods related to the asset-groups so I removed those to keep things nice and clean. (I didn't check the rest of the methods, but I do think it would be beneficial to give them all a quick audit)
Look for the `500 …
=> fix: plumb ctx into asset-groups db methods

cmd/api/src/api/auth.go, cmd/api/src/database/auth.go
Plumb context into gorm client db methods
-   [x] Bug fix (non-breaking …
=> fix: plumb context into client db methods

cmd/api/src/api/v2/file_uploads_integration_test.go, cmd/api/src/api/v2/integration/ingest.go, cmd/api/src/daemons/datapipe/decoders.go, cmd/api/src/test/fixtures/fixtures/expected_ingest.go
Allocating a struct before the decoder loop leads to properties stacking on top of each other due to re-use of the struct
Tested locally
=> Fix ingest decoder bug

.vscode/extensions.json
Remove the TabNine extension from our recommended extensions list
TabNine has been underperforming, and the ability to engage local only processing has become hampered. It is no longer recommended to use TabNine for development.
No longer listed in extension suggestions
=> chore: remove tabnine from extension recommendations

cmd/api/src/api/v2/app_config.go, cmd/api/src/api/v2/app_config_test.go, cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/auth_test.go, cmd/api/src/database/app_config.go, cmd/api/src/database/db.go, cmd/api/src/database/mocks/db.go, cmd/api/src/model/appcfg/parameter.go, cmd/api/src/services/entrypoint.go
Plumb context into gorm config parameters db methods
-   [x] Bug fix …
=> fix: plumb context into config parameter db methods

cmd/api/src/api/v2/file_uploads.go, cmd/api/src/daemons/datapipe/datapipe.go, cmd/api/src/daemons/datapipe/jobs.go, cmd/api/src/daemons/datapipe/jobs_test.go, cmd/api/src/database/db.go, cmd/api/src/database/ingest.go, cmd/api/src/database/mocks/db.go, cmd/api/src/services/ingest/ingest.go
Plumb context into gorm ingest db methods
I also noticed that `GetUnfinishedIngestIDs` was an unused db methods related to the ingest so I removed it to keep things nice and clean.
Look for the `500 request timed out` after exceeding the timeout. (Note: the request will take as long as the sleep is set, it's not …
=> fix: plumb ctx into ingest db methods 

cmd/api/src/api/auth.go, cmd/api/src/api/saml/saml.go, cmd/api/src/api/saml/saml_internal_test.go, cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/auth_test.go, cmd/api/src/api/v2/auth/login.go, cmd/api/src/api/v2/auth/login_internal_test.go, cmd/api/src/api/v2/auth/login_test.go, cmd/api/src/database/auth.go, cmd/api/src/database/auth_test.go, cmd/api/src/database/db.go, cmd/api/src/database/mocks/db.go
Plumb context into gorm user db methods
-   [x] Bug fix (non-breaking change …
=> fix: plumb ctx into user db methods

cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/auth_test.go, cmd/api/src/database/auth.go, cmd/api/src/database/auth_test.go, cmd/api/src/database/db.go, cmd/api/src/database/mocks/db.go
Plumb context into gorm permission db methods
**I also removed the unused db method `CreatePermission`**
-   [ ] Chore (a change that does not modify the …
=> fix: plumb ctx into permission db methods

cmd/api/src/api/auth.go, cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/auth_test.go, cmd/api/src/bootstrap/server.go, cmd/api/src/database/auth.go, cmd/api/src/database/auth_test.go, cmd/api/src/database/db.go, cmd/api/src/database/mocks/db.go
Plumb context into gorm auth token / secrets  db methods
**There is quite a bit of cleanup in this PR, removed the following unused methods**
Db Methods
- ListUsersTokens
- InitializeSAMLAuth
Look for the `500 request timed out` after exceeding the timeout. (Note: the request will take as long as the sleep is …
=> fix: plumb ctx into auth token / secrets db methods 

cmd/api/src/api/v2/file_uploads.go, cmd/api/src/api/v2/file_uploads_test.go, cmd/api/src/daemons/datapipe/datapipe.go, cmd/api/src/daemons/datapipe/jobs.go, cmd/api/src/daemons/datapipe/jobs_test.go, cmd/api/src/database/db.go, cmd/api/src/database/file_upload.go, cmd/api/src/database/mocks/db.go, cmd/api/src/services/fileupload/file_upload.go, cmd/api/src/services/fileupload/mocks/mock.go
Plumb context into gorm file uploads  db methods
-   [x] Bug fix …
=> fix: plumb ctx into file uploads db methods

cmd/api/src/api/v2/saved_queries.go, cmd/api/src/api/v2/saved_queries_test.go, cmd/api/src/database/db.go, cmd/api/src/database/mocks/db.go, cmd/api/src/database/saved_queries.go, cmd/api/src/database/saved_queries_test.go
Plumb context into gorm saved queries db methods
-   [x] Bug fix …
=> fix: plumb ctx into saved queries db methods 

cmd/api/src/api/v2/integration/api.go, cmd/api/src/bootstrap/initializer.go, cmd/api/src/bootstrap/server.go, cmd/api/src/database/agi_test.go, cmd/api/src/database/audit_test.go, cmd/api/src/database/auth.go, cmd/api/src/database/auth_test.go, cmd/api/src/database/db.go, cmd/api/src/database/migration/agi_integration_test.go, cmd/api/src/database/mocks/db.go, cmd/api/src/database/saved_queries_test.go, cmd/api/src/test/integration/database.go, cmd/api/src/test/lab/fixtures/api.go, cmd/api/src/test/lab/fixtures/postgres.go
Plumb context into gorm remaining  db methods
-   [x] Bug fix (non-breaking …
=> fix: plumb ctx into remaining bh db methods 

cmd/api/src/api/middleware/middleware.go, cmd/api/src/api/tools/flag.go, cmd/api/src/api/v2/ad_related_entity.go, cmd/api/src/api/v2/ad_related_entity_test.go, cmd/api/src/api/v2/flag.go, cmd/api/src/api/v2/flag_test.go, cmd/api/src/daemons/datapipe/analysis.go, cmd/api/src/daemons/datapipe/datapipe.go, cmd/api/src/database/app_config.go, cmd/api/src/database/mocks/db.go, cmd/api/src/model/appcfg/flag.go
Plumb context into gorm feature flag db methods
-   [x] Bug fix (non-breaking …
=> fix: plumb ctx into feature flag db methods

cmd/api/src/api/auth.go, cmd/api/src/api/middleware/auth.go, cmd/api/src/api/mocks/authenticator.go, cmd/api/src/api/saml/saml.go, cmd/api/src/api/saml/saml_internal_test.go, cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/auth_test.go, cmd/api/src/api/v2/auth/login.go, cmd/api/src/bootstrap/initializer.go, cmd/api/src/daemons/api/bhapi/api.go, cmd/api/src/daemons/api/toolapi/api.go, cmd/api/src/daemons/daemon.go, cmd/api/src/daemons/datapipe/datapipe.go, cmd/api/src/daemons/gc/data_pruning.go, cmd/api/src/daemons/gc/data_pruning_test.go, cmd/api/src/database/agi.go, cmd/api/src/database/auth.go, cmd/api/src/database/auth_test.go, cmd/api/src/database/db.go, cmd/api/src/database/mocks/db.go
Plumb context into gorm session db methods
-   [x] Bug fix (non-breaking …
=> fix: plumb ctx into session db methods

cmd/api/src/api/auth.go, cmd/api/src/api/auth_internal_test.go, cmd/api/src/api/middleware/auth_test.go, cmd/api/src/api/v2/audit_integration_test.go, cmd/api/src/api/v2/database_wipe.go, cmd/api/src/api/v2/integration/audit.go, cmd/api/src/auth/model.go, cmd/api/src/database/agi.go, cmd/api/src/database/agi_test.go, cmd/api/src/database/audit.go, cmd/api/src/database/audit_internal_test.go, cmd/api/src/database/audit_test.go, cmd/api/src/database/auth.go, cmd/api/src/database/auth_test.go, cmd/api/src/model/audit.go, cmd/api/src/utils/test/auditlogs.go
Refactored audit log action from string to AuditLogAction type and added constants for all the hardcoded action strings.
While working on ctx plumbing https://github.com/SpecterOps/BloodHound/pull/467, I noticed that we were hardcoding the audit log action strings in a multitude of places. It felt like a good time to abstract them out to a constant. The added benefit here is there's also 1 place we can look to see all of the audit logs types we have without _auditing_ the entire codebase.
Relied on integration tests
-   [ ] Breaking change (fix or feature that would cause existing …
=> refactor: audit log action to constant

cmd/api/src/services/fileupload/file_upload.go, cmd/api/src/services/fileupload/file_upload_test.go, cmd/api/src/test/fixtures/fixtures/utf8bomjson.json
Removes the UTF-8 BOM from json files when processing on the API, as this is invalid regardless
https://github.com/SpecterOps/BloodHound/issues/30
Integration tests + local testing
=> Strip UTF-8 BOM from json files

cmd/ui/src/ducks/index.ts, cmd/ui/src/ducks/searchbar/saga.ts, cmd/ui/src/store.ts, cmd/ui/src/views/Explore/BasicObjectInfoFields.tsx, cmd/ui/src/views/Explore/ContextMenu/ContextMenu.test.tsx, cmd/ui/src/views/Explore/ContextMenu/ContextMenu.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx, cmd/ui/src/views/Explore/ExploreSearch/CommonSearches.tsx, cmd/ui/src/views/Explore/ExploreSearch/CypherSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/EdgeFilter.tsx, cmd/ui/src/views/Explore/ExploreSearch/EdgeFilteringDialog.tsx, cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.test.tsx, cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/NodeSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.test.tsx, cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/PathfindingSwapButton.tsx, cmd/ui/src/views/Explore/ExploreSearchCombobox/ExploreSearchCombobox.tsx, cmd/ui/src/views/GroupManagement/GroupManagement.tsx, packages/javascript/bh-shared-ui/rollup.config.js, packages/javascript/bh-shared-ui/src/components/FileValidationStatus/FileValidationStatus.tsx, packages/javascript/bh-shared-ui/src/hooks/useSearch/useSearch.test.ts, packages/javascript/bh-shared-ui/src/hooks/useSearch/useSearch.tsx, packages/javascript/bh-shared-ui/src/store/index.ts, packages/javascript/bh-shared-ui/src/store/searchbar/actions.ts, packages/javascript/bh-shared-ui/src/store/searchbar/index.ts, packages/javascript/bh-shared-ui/src/store/searchbar/reducer.ts, packages/javascript/bh-shared-ui/src/store/searchbar/types.ts, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx
This changeset adds handling for `undefined` input in the explore search. Additionally, the search reducer is moved to the shared-ui since it is used in both community and enterprise.
We have a flow in BHE where search input state is filled in from information outside of the expected search results data format. The data that was passed in was incomplete and causing the app to reach the error boundary as there was no other explicit handling for the unexpectedly incomplete data. Empty defaults and checks for undefined input have been added for circumventing reaching an error state.
A unit test was added at the point where the runtime error was encountered.
- …
=> fix: handle undefined input in explore search input

cmd/api/src/api/v2/ad_related_entity.go, cmd/api/src/api/v2/ad_related_entity_test.go, cmd/api/src/queries/graph_integration_test.go
The response shape for related entity queries with url param `type=graph` has been reverted in order to maintain the current api contract for this kind of request.
This endpoint response changes shape based on the params that are passed in the request. While it is better and something that we should have in place to standardize these response shapes, normalizing this response resulted in a breaking change for viewing a node's relationships in the graph from the entity panel. The response was previously flat and was not sent back as pagination results and so the UI was looking in the wrong place for the data to render in the graph. Reverting this shape allows these graphs to render in the UI again.
Tests have been added asserting on the response shape for both graph type and list type …
=> fix: revert response shape for type=graph related entity queries

packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/ADCSESC13.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/Opsec.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
Adds the components for the ESC13 edge information pane.
ESC13 is in the works and this changeset introduces the components that will render the edge information when clicking on this edge in the Explore page.
This edge is not yet implemented so this will preemptively have these components available once the edge is being generated. There are no additional requirements or blockers.
-   [ ] I have added and/or updated tests to …
=> feat: add esc13 edge info content

cmd/api/src/model/appcfg/flag.go
Add feature flag for new tier zero risk exposure calculation.  Default disabled, not user definable.
https://specterops.atlassian.net/browse/BED-4105
Verified flag use on local.
=> [BED-4105] Add new risk exposure calculation flag

packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC4/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC4/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/CodeController/CodeController.tsx
Fix 2 typos and an incorrect formatting on code snippets
BED-4271
Manually tested code snippet formatting and typos
=> fix: typo and wrong format for code snippit

cmd/api/src/api/bloodhoundgraph/bloodhoundgraph.go
The AIACA node icon for graph rendering has been updated to match the icon that is used in the rest of the UI.
This styling is defined in the API and was not matching the UI's definitions so different icons were shown in the regular UI components vs the graph.
=> fix: align node icons for AIACA nodes

cmd/api/src/api/v2/docs.go
Fixed invalid JSON in swagger doc
The JSON was invalid and would break a JSON parser.
Manual testing
=> fix: BED-4283 - fixed invalid json syntax in swagger doc json

cmd/api/src/api/v2/database_wipe.go, cmd/api/src/api/v2/database_wipe_test.go, cmd/api/src/daemons/datapipe/datapipe.go, cmd/api/src/daemons/datapipe/delete.go, cmd/api/src/daemons/datapipe/mocks/tasker.go, cmd/api/src/database/file_upload.go, cmd/api/src/database/mocks/db.go, cmd/api/src/model/datapipe_status.go, cmd/api/src/services/fileupload/file_upload.go, cmd/api/src/services/fileupload/mocks/mock.go, justfile
Moves logic for graph deletion to the datapipe to prevent deadlocks
The existing logic for clearing the DB was handled by the api handler in resources. However, if concurrent graph modifications were being performed in datapipe, this would lead to graph deadlocks. This MR moves the graph deletion logic into datapipe
https://specterops.atlassian.net/browse/BED-4286
Local testing
-   [ ] I have added and/or updated tests to cover …
=> Move graph deletion to datapipe

docker-compose.dev.yml, docker-compose.testing.yml, tools/docker-compose/neo4j.Dockerfile
This PR updates vulnerable libraries in our neo4j container used in development. I made the following fixes/changes to get down to only 1 "medium" vulnerability.
- Bump neo4j base image to 4.4.31
- Set the `allowlist` for procedures to only allow calls to `apoc.periodic.*` to mitigate CVE-2023-23926
- Updated `apoc` to 4.4.0.25
- Combined Docker commands to reduce the amount of layers needed for the container
- Added conditional command to add `memrec` to the neo4j config. This is configurable by setting the build arg `memconfig` to true. This is enabled by default in development docker compose deployments, but not testing.
- Updated the testing infrastructure to use BloodHound's custom neo4j container instead of the base image from Docker Hub
Note that this change means that we will now …
=> Resolve vulnerabilities in neo4j container

packages/go/dawgs/drivers/neo4j/cypher.go, packages/go/dawgs/drivers/neo4j/cypher_internal_test.go, packages/go/dawgs/drivers/neo4j/node.go, packages/go/dawgs/drivers/neo4j/relationship.go, packages/go/dawgs/drivers/neo4j/result.go, packages/go/dawgs/drivers/neo4j/transaction.go, packages/go/dawgs/util/errors.go, packages/go/dawgs/util/errors_test.go
This PR adds sanitization to errors returned from the neo4j driver for `dawgs`. This fixes #278.
I also noticed that the `IsNeoTimeoutError` was incorrectly returning false when the time out came from the neo4j driver from `dawgs`. I updated that function to properly handle that case and additional test cases, as well.
* Prevent leaking potentially sensitive information in logs
* I reduced the timeout for cypher queries to a low value and ran a complex query to verify sensitive values were stripped
* Added additional test cases for `IsNeoTimeoutError`
Before:
```
bhe-api-1       | {"level":"info","user_id":"7f63d6b4-c472-43f2-9ed1-5fac1a0fa6e8","remote_addr":"172.30.0.5:56408","proto":"HTTP/1.1","referer":"http://bhe.localhost/ui/mockServiceWorker.js","user_agent":"Mozilla/5.0 (Macintosh; …
```
=> Sanitize cypher errors from neo4j driver

packages/go/ein/ad.go
Fixed the order of cert mapping methods. Documentation for the values:  https://learn.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings?tabs=diffie-hellman#certificatemappingmethods
=> fix: mixed up order of cert mapping methods

packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC4/LinuxAbuse.tsx
corrected owneredit.py syntax
https://github.com/ThePorgs/impacket/blob/9aa93730ccb355a7ef8e9295c974460610ae798b/examples/owneredit.py#L246-L248
owneredit.py --help
........
owner:
Object, controlled by the attacker, to set as owner of the target object
-new-owner NAME       sAMAccountName
-new-owner-sid SID    Security IDentifier
-new-owner-dn DN      Distinguished Name
typo
yes, inside of a lab
-   [ ] I have added and/or …
=> Update LinuxAbuse.tsx, correct typo

packages/go/openapi/src/responses/bad-request.yaml, packages/go/openapi/src/responses/binary-response.yaml, packages/go/openapi/src/responses/csv-response.yaml, packages/go/openapi/src/responses/error-response.yaml, packages/go/openapi/src/responses/forbidden.yaml, packages/go/openapi/src/responses/internal-server-error.yaml, packages/go/openapi/src/responses/no-content.yaml, packages/go/openapi/src/responses/not-found.yaml, packages/go/openapi/src/responses/too-many-requests.yaml, packages/go/openapi/src/responses/unauthorized.yaml, packages/go/openapi/src/schemas/api.error-detail.yaml, packages/go/openapi/src/schemas/api.error-wrapper.yaml
This PR adds common responses and supporting schemas to the openapi document source.
Part of an ongoing effort to improve API documentation
Manual testing of openapi generation. Documentation only changes
=> chore: BED-4141 - Added common responses to openapi spec src

examples/docker-compose/README.md
This PR adds some additional verbiage to the `examples/README.md` file on how to configure BloodHound using the `bloodhound.config.json` file. Issue #207 highlighted that this is not clear in the previous version of the README as it was only documented in the `docker-compose.yml` file. 
* Avoid confusion when configuring BloodHound
* Verified the steps documented correctly apply the desired changes
-   [ ] I have added and/or …
=> Clarify configuration process in documentation

cmd/api/src/analysis/azure/queries.go
The kinds slice is updated in the graph stats method.
The missing azure stat kinds were not updated in the kinds slice which meant that the counts were not being accumulated so were being saved as zero counts. This changeset updates these kinds to be based on the list that is output from the azure cue schema.
Ran a local collection and verified the stat counts against the graph db. 
-   [ ] I have added and/or updated tests to …
=> fix: update kinds slice in graphstats for effectively saving kind stat counts

cmd/api/src/analysis/ad/ad_integration_test.go, packages/go/analysis/ad/esc3.go, packages/go/analysis/ad/post.go, packages/go/analysis/analysis.go
This PR prevents T0 assets from being incorrectly excluded from creating `DCSync` edges. The filtering was unintended and has been removed.
I also fixed an unrelated log message that I noticed had the incorrect log level. This should help prevent it from getting lost when parsing logs.
* Ensure `DCSync` edges are present for T0 assets
* Updated the associated test for the new logic and ensured it was passing
-   [ ] I have added …
=> Don't filter T0 assets from DCSync edges

justfile, packages/go/stbernard/command/show/show.go
Conditionally remove tmp file when running `prepare-for-codreview`
The first time running `just prepare-for-codereview` errors because we try to remove the tmp file. This change just checks if that dir exists before removing it.
Manual tests
=> fix: rm tmp if it exists

cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.test.tsx, cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.tsx
Fixes bug where editing the primary search field from the pathfinding search tab would actually do a single node search regardless of the destination search value. This fixes it so pathfinding tab always does a pathfinding search when editing that field.
manual tests and updated unit tests
https://github.com/SpecterOps/BloodHound/assets/66393111/aea15ea6-b05e-45d6-b377-972b67033ebe
https://github.com/SpecterOps/BloodHound/assets/66393111/42787a10-7e02-452f-8301-76d9593cec8c
=> BED-3852 - Pathfinding search when primary and destination node selected

cmd/ui/src/ducks/auth/types.ts, cmd/ui/src/views/Users/Users.test.tsx, cmd/ui/src/views/Users/Users.tsx, packages/javascript/bh-shared-ui/src/components/PasswordDialog/PasswordDialog.tsx, packages/javascript/js-client-library/src/client.ts, packages/javascript/js-client-library/src/types.ts
In the Administration/Manage Users page, Administrators who update a user to use username/password based authentication when the user had previously used SAML are now presented with the password reset dialog to help ensure that the user has a valid secret before attempting their next login.
Users lose their auth secret when not using username/password based authentication. If a user is updated to use username/password based authentication they can be left in a state where they cannot log in because there is no valid password for them to use. This change prompts admins to supply a password for these users to avoid this scenario.
New tests have been added to cover this behavior
-   [ ] Bug fix (non-breaking change …
=> Open password reset dialog when updating user to use username/password based authentication

cmd/ui/src/ducks/entityinfo/types.ts, packages/cue/bh/ad/ad.cue, packages/go/ein/ad.go, packages/go/ein/incoming_models.go, packages/go/graphschema/ad/ad.go, packages/javascript/bh-shared-ui/src/graphSchema.ts
Add EnterpriseCA property RoleSeparationEnabled
Ticket: BED-4351
If this setting is enabled, you cannot perform any CA actions if you have both ManageCA and ManageCertificates permissions. Only CA admins can modify the setting.
We need it for the ESC7 implementation, as some attack narratives require both ManageCA and ManageCertificates and could therefore be blocked by this setting.
More info on the setting: [Q: How can I make sure that a given Windows account is assigned only](https://www.itprotoday.com/security/q-how-can-i-make-sure-given-windows-account-assigned-only-single-certification-authority-ca)
With this SharpHound data [20240426013313_BloodHound.zip](https://github.com/BloodHoundAD/SharpHoundCommon/files/15128061/20240426013313_BloodHound.zip)
-   [ ] Chore (a change that does …
=> feat: add RoleSeparationEnabled property

cmd/ui/src/ducks/entityinfo/types.ts, packages/cue/bh/ad/ad.cue, packages/go/graphschema/ad/ad.go, packages/javascript/bh-shared-ui/src/graphSchema.ts
Ingest unresolved published cert templates for EnterpriseCAs.
Unresolved published cert templates are interesting, as an attacker can create or rename a cert template to have one of these names and then it will be published automatically.
Collected in my lab with one EnterpriseCA with no unresolved cert templates and another with.
-   [x] All new and existing tests …
=> feat: collect unresolved published cert templates

.devcontainer/docker-compose.yml, .gitignore, .vscode/extensions.json, .vscode/launch.json, docker-compose.dev.yml, docker-compose.testing.yml, docker-compose.watch.yml, examples/docker-compose/docker-compose.yml, packages/go/cypher/backend/cypher/format.go, packages/go/cypher/frontend/expression.go, packages/go/cypher/frontend/function.go, packages/go/cypher/frontend/literal.go, packages/go/cypher/frontend/pattern.go, packages/go/cypher/frontend/query.go, packages/go/cypher/model/copy.go, packages/go/cypher/model/model.go, packages/go/cypher/model/walk.go
Adds necessary plumbing to enable cypher MERGE clauses in our interpreter. This also means they are available when using the Cypher Search box in BloodHound, if `enable_cypher_mutations` is enabled.
We are working on cost modeling for mutation queries (BED-4358), and this was a prerequisite since it turned out we hadn't wired in support for MERGE yet.
Ran through multiple scenarios manually:
- `MERGE (n:Hello {objectid:'hello'}) RETURN n` (x2 to ensure that an existing node prevents a node creation)
- `MERGE (n:Hello {objectid:'hello'}) SET n.hello = 'hello' RETURN n`
- `MERGE (n:Hello {objectid:'goodbye'}) ON CREATE SET n.hello = 'goodbye' RETURN n`
- `MERGE (n:Hello {objectid:'goodbye'}) ON MATCH SET n.hello = 'hello' RETURN n`
- `MERGE (n:Hello {objectid:'goodbye'}) ON CREATE SET …
=> BED-4358: add merge clause to supported cypher

packages/javascript/bh-shared-ui/src/components/HelpTexts/AZUserAccessAdministrator/Abuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/AZUserAccessAdministrator/General.tsx
Update the AZUserAccessAdministrator help text to reflect abuse from the perspective of a Service Principal.
The current AZUserAccessAdministrator Abuse help text seems to indicate that the attack path can only be performed via the Azure portal. In the case where this role is assigned to a Service Principal, which cannot authenticate to the Azure portal, it is unclear if the path is abusable. This change adds some additional context and references to BARK functions which were provided by Andy Robbins (@_wald0).
Configure local developmnent environment as per documentation: https://github.com/SpecterOps/BloodHound/wiki/Development.
Tested the changes by viewing the updated AZUserAccessAdministrator Help Text in the BloodHound UI. 
-   [x] Chore (a change that does not modify the …
=> Update the AZUserAccessAdministrator help text

packages/go/cypher/frontend/atom.go, packages/go/cypher/frontend/expression.go, packages/go/cypher/test/cases/positive_tests.json
This is a minor change to support parsing out parameters from openCypher.
This is applicable to upcoming openCypher translation work and is inline with other work currently under way in the openCypher parser frontend.
Added some additional test cases in the JSON query tests.
=> feat: add parameter parsing support to cypher frontend

dockerfiles/bloodhound.Dockerfile
A recent run of the "Publish Edge Build" action failed after a merge: https://github.com/SpecterOps/BloodHound/actions/runs/9197923729/job/25299465051
The error was a python version conflict in our dockerfile between the version installed by the `apk add python3` command (v3.12) and a hardcoded reference to v3.11 later in the file. That reference existed to remove the `EXTERNALLY_MANAGED` python flag, fixing another bug that was originally addressed here: https://github.com/SpecterOps/BloodHound/pull/267
This fix updates the command to remove that flag with a command that does not rely on an exact version number.
Will allow our build to run successfully regardless of what version of python is installed.
Tested by building locally: `docker build . -f dockerfiles/bloodhound.Dockerfile`
- …
=> Remove version number from python command in dockerfile

cmd/api/src/api/auth_test.go, cmd/ui/src/views/Explore/GraphView.tsx, packages/javascript/bh-shared-ui/src/components/WebGLDisabledAlert/WebGLDisabledAlert.tsx, packages/javascript/bh-shared-ui/src/components/WebGLDisabledAlert/index.ts, packages/javascript/bh-shared-ui/src/components/index.ts, packages/javascript/bh-shared-ui/src/mocks/index.ts, packages/javascript/bh-shared-ui/src/mocks/webgl.ts, packages/javascript/bh-shared-ui/src/utils/compatibility.test.ts, packages/javascript/bh-shared-ui/src/utils/compatibility.ts
Our graph view on the Explore page requires WebGL to render correctly; currently, if a user tries to visit the explore page without WebGL enabled on their browser, the application crashes without a helpful error message. This PR adds a compatibility check to the Explore page and will render a more descriptive error message if the WebGL rendering context is not available.
Users currently do not have a way to differ between errors caused by their browser not having webGL enabled and other errors that could lead to the Explore page crashing.
Added a test for the compatibility check in the shared-ui project.
-   [ ] New feature (non-breaking change which adds …
=> BED-4431 -- Add webgl compatibility check to Explore page

packages/go/analysis/azure/azure.go, packages/go/ein/azure.go
Closes BED-4380
Stop `AZHasRole` edge from being created for appadmin / cloudappadmin for app scoped relationships
Also cleaned up some unused constants found
These edges were errantly created and shouldn't exist.
Ran Azurehound and verified edge wasn't created.
Run the following in explore
```
match p = ()-[:AZAppAdmin|:AZCloudAppAdmin]->()
return p
```
Pick one and find the path from principal to the app service principal. The edge for `AZHasRole `should be removed
-   [ ] Documentation updates are …
=> fix: errantly adding AZHasRole edge to non-tenant scoped principals

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Fix two broken predefined queries.
CONTAINS is used in Cypher to find sub-strings in strings. These queries used CONTAINS as it checked if an item existed in a list, which did not work.
=> fix: pre-defined queries with wrong contains usage

.github/workflows/edge-publish.yml, dockerfiles/bloodhound.Dockerfile, packages/go/stbernard/command/builder/builder.go, packages/go/stbernard/command/command.go, packages/go/stbernard/environment/environment.go, packages/go/stbernard/main.go, packages/go/stbernard/workspace/golang/build.go, packages/go/stbernard/workspace/workspace.go
This PR updates the existing Dockerfile to build with `stbernard` instead of `beagle`. A few key changes were necessary to enable this functionality:
* Pulling the version from the environment variable if the git tag was unavailable. This was necessary to support building the edge release.
* Adding flags to override the `GOOS` and `GOARCH` environment variables. This enables `stbernard` to build against any environment via `go run`. Prior to this change the variables would conflict against the architecture that was calling `go run stbernard`.
Also included in this PR is the removal of Python from the Docker build as it was only used by `beagle.`
* Consolidate on a single CLI tool for BloodHound
* Ran the builds locally and on GitHub actions and verified they built successfully
-   [ ] …
=> chore: modify dockerfile to build with stbernard

packages/go/analysis/ad/adcs.go, packages/go/analysis/azure/post.go, packages/go/dawgs/drivers/neo4j/neo4j.go, packages/go/dawgs/graph/errors.go, packages/go/dawgs/util/errors.go, packages/go/dawgs/util/errors_test.go
Simplifies errors coming from the `graph` package to be more ergonomic. This current iteration kept some utility functions for compatibility despite them just being syntax sugar for `errors.Is()`
I also saw several warnings for unused parameters and removed them here. The adcsEnabled boolean seemed like a vestige from before adcs was GA, but I'm slightly concerned about the ones that weren't using `tenant` and I would like to work with engineering to review if this is correct behavior. Seems like without consuming the tenant, we're likely doing a lot of duplicate work with those functions.
I get annoyed by error handling, I fix
There were some tests tied to the error implementation. I've fixed them to work with the new expectations while keeping the logic intact. No other errors appear to …
=> BED-4473: simplify graph errors

cmd/ui/src/ducks/global/types.ts, packages/javascript/js-client-library/src/client.ts, packages/javascript/js-client-library/src/responses.ts
Updates the type location for datapipestatus to be defined in the client.
This PR addresses: BED-4490 indirectly
Cleaner and consolidated response typing that will be used in the accompanying BHE MR.
No material changes only typing. UI still builds so type checking is good.
=> chore: move type to api client

cmd/api/src/database/migration/migrations/v5.12.0.sql
Fixes the part of our v5.12.0 migration that is not idempotent
Migrations should be written as idempotent whenever possible to ensure they can be reapplied safely
Deleted the migration record for v5.12.0 and restarted dev after running into a migration issue. This solves it.
=> BED-4391: Make v5.12.0 migration idempotent

cmd/api/src/api/bloodhoundgraph/conversions.go, cmd/api/src/api/bloodhoundgraph/properties.go, cmd/api/src/queries/graph.go, packages/go/dawgs/graph/properties.go, packages/go/dawgs/graph/properties_test.go
CLOSES BED-4429
Added a fallback utility fn to graph node properties.
Updated /search response nodes to fallback to display name and then object id if not name property does not exist.
A number of applications are missing names b/c they were ingested via their respective service principal 
Ran locally
Before:
After
-   [ ] …
=> fix: missing name property on azure apps spawned by service principals

packages/javascript/bh-shared-ui/src/utils/datetime.ts
Adds `ISO_8601` to luxon datetime formats
This PR supports: BED-4489
This format supports the ISO 8601 date format which is `yyyy-mm-dd`
Manually tested that the format string works as expected.
=> Supports 4489: add ISO_8601 date format

cmd/api/src/api/error.go, cmd/api/src/api/v2/agi.go, cmd/api/src/api/v2/agi_test.go, cmd/api/src/database/agi.go, cmd/api/src/database/db.go, cmd/api/src/database/migration/asset_group_constraints_test.go, cmd/api/src/database/migration/migrations/schema.sql, cmd/api/src/database/migration/migrations/v5.12.0.sql
Modified DB schema to prevent creation of asset groups with empty names/tags or duplicate tags.
Previously, asset groups could be created with tags that duplicate existing tags or with empty names/tags. This could potentially cause widespread bugs in analysis and display given our extensive reliance on string matching for these tags.
- Updated application layer unit test function `TestResources_CreateAssetGroup`
- Added new test cases for:
- Empty asset group name
- Empty asset group tag
- Whitespace in asset group tag
- Added new test file DB layer unit test function `migration/asset_group_constraints_test.go` to validate new schema constraints
- Verified compatibility with existing DB migration tests for asset groups
- Manually verified functionality through API Explorer UI
-   [ ] …
=> BED-4435: Enforce AG name tag uniqueness

packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteSPN/References.tsx
Fixed a broken link in edge references
This PR addresses: BED-4525
Accuracy is important :-)
Local testing - small link update
=> BED 4525: Fix broken link

cmd/api/src/model/filter.go, cmd/api/src/model/search.go
Fixes issue where domains without the `collected` property does not show up when filter is set to `collected=false`
Improved functionality from a bugfix
- Manual testing with API Explorer UI
- Passes unit and integration tests
=> BED-4439: Broken collected filter

cmd/api/src/model/appcfg/flag.go, cmd/ui/src/components/SettingsMenu.tsx, cmd/ui/src/store.ts, cmd/ui/src/views/EarlyAccessFeatures/EarlyAccessFeatures.tsx
Adds a dark mode feature flag and hides the dark mode toggle until the feature is enabled.
This is going to be behind a feature flag for now and addresses BED-4546
Local testing only at the moment.
=> feat: move dark mode behind feature flag

README.md, cmd/ui/src/views/Explore/GraphView.tsx
Update links in README.MD and in the Explore help modal to point directly to the new docs location.
This PR addresses: BED-4568
Local environment
=> BED-4568: Update links to point directly to sample data

packages/go/openapi/src/openapi.yaml, packages/go/openapi/src/paths/domains.domains.id.computers.yaml, packages/go/openapi/src/paths/domains.domains.id.controllers.yaml, packages/go/openapi/src/paths/domains.domains.id.dc-syncers.yaml, packages/go/openapi/src/paths/domains.domains.id.foreign-admins.yaml, packages/go/openapi/src/paths/domains.domains.id.foreign-gpo-controllers.yaml, packages/go/openapi/src/paths/domains.domains.id.foreign-groups.yaml, packages/go/openapi/src/paths/domains.domains.id.foreign-users.yaml, packages/go/openapi/src/paths/domains.domains.id.gpos.yaml, packages/go/openapi/src/paths/domains.domains.id.groups.yaml, packages/go/openapi/src/paths/domains.domains.id.inbound-trusts.yaml, packages/go/openapi/src/paths/domains.domains.id.linked-gpos.yaml, packages/go/openapi/src/paths/domains.domains.id.ous.yaml, packages/go/openapi/src/paths/domains.domains.id.outbound-trusts.yaml, packages/go/openapi/src/paths/domains.domains.id.users.yaml, packages/go/openapi/src/paths/domains.domains.id.yaml
- Added all of the domains specs
- Ticket: BED-4551
- Subtask above is from here: BED-4141
- Simplifies and improves on our existing OpenAPI spec documentation
- I made sure to check that all refs and paths were correct and led to their proper locations
=> BED-4551: Add Domain Entity Paths to OAPI Spec

cmd/api/src/daemons/datapipe/convertors.go, packages/go/ein/ad.go, packages/go/ein/azure.go, packages/go/ein/models.go
- Moved to an initializer for ein.IngestibleRelationship, and refactored all current uses to that initializer.
- Fixes some cases where we explicitly created empty ein.IngestibleRelationship structs, which would contain a nil map
- Fixed issues with some `make([]IngestibleRelationship...)` to ensure that the slice length is set to 0 even if the capacity was set to another number, removing the chance of having empty IngestibleRelationship structs in those slices.
This PR addresses: BED-4570 | #695 
Removes chances for panics when invalid data is ingested
Local testing with reproduction steps from original GitHub issue
- Bug fix (non-breaking change which fixes an …
=> BED-4570: Resolve panics with IngestibleRelationship

cmd/ui/src/App.tsx
fixes edge case where dark_mode feature flag is turned off remotely, leaving other users stuck in dark mode.
This PR addresses: BED-4574
If dark_mode feature flag is not enabled then all users should be on light mode by default
manual tests
=> BED-4574: Dark Mode early access fix

packages/go/openapi/src/openapi.yaml, packages/go/openapi/src/paths/analysis.asset-groups.id.combo-node.yaml, packages/go/openapi/src/paths/analysis.meta-nodes.id.yaml, packages/go/openapi/src/paths/analysis.meta-trees.id.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.id.collections.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.id.custom-selectors.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.id.members.counts.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.id.members.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.id.selectors.id.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.id.selectors.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.id.yaml, packages/go/openapi/src/paths/asset-isolation.asset-groups.yaml, packages/go/openapi/src/paths/attack-paths.attack-path-types.yaml, packages/go/openapi/src/paths/attack-paths.attack-paths.id.acceptance.yaml, packages/go/openapi/src/paths/attack-paths.attack-paths.yaml, packages/go/openapi/src/paths/attack-paths.domains.id.attack-path-findings.yaml, packages/go/openapi/src/paths/attack-paths.domains.id.available-types.yaml, packages/go/openapi/src/paths/attack-paths.domains.id.details.yaml, packages/go/openapi/src/paths/attack-paths.domains.id.sparkline.yaml, packages/go/openapi/src/paths/risk-posture.posture-stats.yaml, packages/go/openapi/src/schemas/model.asset-group-collection-entry.yaml, packages/go/openapi/src/schemas/model.asset-group-collection.yaml, packages/go/openapi/src/schemas/model.asset-group-member.yaml, packages/go/openapi/src/schemas/model.asset-group-selector-spec.yaml, packages/go/openapi/src/schemas/model.asset-group-selector.yaml, packages/go/openapi/src/schemas/model.asset-group.yaml, packages/go/openapi/src/schemas/model.list-finding.yaml, packages/go/openapi/src/schemas/model.relationship-finding.yaml, packages/go/openapi/src/schemas/model.risk-counts.yaml, packages/go/openapi/src/schemas/model.risk-posture-stat.yaml
added openapi spec definitions for paths:
- analysis
- attack-paths
- risk-posture
- asset-isolation
This PR addresses: BED-4141 / BED-4555
=> BED-4555: added analysis related paths to openapi spec

packages/javascript/bh-shared-ui/src/constants.ts
Improves contrast of graph progress bar
This PR addresses: BED-4589
The graph loading bar contrast is low in lightmode
Visual tests
=> BED-4589: Graph loading bar contrast in dark mode

packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
- Remove a prop passed to the search result component that caused the first result in the list of search results to always appear highlighted
- Removed some unnecessary pieces of state and effects from the component to simplify and avoid rerenders
This PR addresses: [BED-4592]
While reviewing the dark mode changes, we realized the existing highlighting does not really convey any information to the user and could potentially be misleading.
- Manual testing to confirm the highlighting is removed
- Code …
=> BED-4592: Remove unnecessary highlighting from Search Current Nodes

packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.test.tsx, packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.tsx
This will return the active styles to the FILTERS button in the group management page.
This PR addresses: BED-4606
There was a regression in the active styles applied.
Unit test was updated.
=> fix: filters active button styles

cmd/ui/src/App.tsx
Updates api-explorer filter input styles to match other inputs
This PR addresses: BED-4591
Api explorer filter input did not respect dark mode.
visual tests
=> BED-4591: api-explorer filter input styles

cmd/api/src/database/agi.go, cmd/api/src/database/agi_test.go, packages/go/errors/error.go
Added a new `getAssetGroupMemberCount` helper function that queries the latest asset group collection
Resolves the bug where asset group member counts were incorrectly reported as 0 in API responses and ensures accurate representation of group membership
Manually tested via API Explorer UI
=> BED-4168: Fixed inaccurate AG member_count value 

cmd/ui/src/styles/general.scss, packages/javascript/bh-shared-ui/src/views/Explore/InfoStyles/Pane.tsx
Remove global scroll bar styles and scrollbar gutter
This PR addresses: BED-4627
After reviewing the styles and some conversation in the dark mode channel, we have agreed on removing custom scrollbar styles. Overriding these styles can be inconsistent across different browsers.
visual tests
https://github.com/user-attachments/assets/c401f138-6ae9-43ce-97b1-665d4677cbdf
=> BED-4627: global scrollbar styles

packages/javascript/bh-shared-ui/src/constants.ts
Fix text contrast for MUI error alert in light mode
This PR addresses: BED-4628
The contrast between the text and background color of error alerts was too low in light mode.
Uploading Screen Recording 2024-07-24 at 3.28.43 PM.mov…
=> BED 4628:  Error alert text contrast

cmd/ui/src/rendering/programs/edge-label.ts, cmd/ui/src/rendering/programs/node-hover.ts, cmd/ui/src/rendering/programs/node-label.ts, cmd/ui/src/rendering/utils/utils.ts, cmd/ui/src/utils.ts, cmd/ui/src/views/Explore/GraphView.tsx, cmd/ui/src/views/Explore/utils.ts, packages/javascript/bh-shared-ui/src/utils/icons.ts
Updates the graph label colors to better reflect the theme
This PR addresses: BED-4596
Fixes hovered/selected styles contrast ratio non conformance
Labels fit theme colors better
See screenshots section
=> fix: theme graph label colors

cmd/api/src/api/v2/saved_queries.go, cmd/api/src/api/v2/saved_queries_test.go, cmd/api/src/database/db.go, cmd/api/src/database/migration/migrations/v5.13.1.sql, cmd/api/src/database/mocks/db.go, cmd/api/src/database/saved_queries.go, cmd/api/src/database/saved_queries_permissions.go, cmd/api/src/database/saved_queries_permissions_test.go, cmd/api/src/database/saved_queries_test.go, cmd/api/src/docs/json/definitions/v2.json, cmd/api/src/model/saved_queries.go, cmd/api/src/model/saved_queries_permissions.go, cmd/api/src/model/saved_queries_test.go, packages/go/openapi/src/schemas/model.saved-query.yaml
These changes add a new description field to the `saved_queries` model, which will allow users the ability to add short descriptions on what their cypher query does.
We are also adding a new model called `saved_queries_permissions` which will contain the relationships between users and the queries they have been shared - globally or directly.
This PR addresses: BED-4535
Initial database implementation required for work on API to begin development. Ultimately will enable the ability to search and share cypher queries directly from the UI.
First I ensured that the UI was still able to save queries while sending up the new description field in the body:
We can see that the migration successfully ran on startup by having the …
=> BED-4534: Saved Cypher Improvements & Description Field

dockerfiles/bloodhound.Dockerfile, tools/docker-compose/api.Dockerfile
This PR bumps the included version of SharpHound to v2.5.2 to support the v5.13.0 release of BloodHound.
* Include the latest fixes for the collector
* Verified the correct version is listed on the Download Collectors page
=> BED-4636 bump sharphound

packages/go/dawgs/drivers/neo4j/cypher.go, packages/go/dawgs/drivers/neo4j/cypher_internal_test.go
Batch updates are bucketed by a unique key that matches the generated openCypher query statement. This sort appears to damage the uniqueness of these buckets, resulting in mismatched kinds being applied to nodes during upsert.
This would manifest as nodes having more than one valid kind such as: `match (n) where n:Base and n:Group and n:User return n`
This damages the validity of data stored in the graph as nodes are being incorrectly labeled.
Integration tests pass. Added an additional unit test with some explanation for the assertions. …
=> BED-4479 - ensure update key uniqueness by removing sort

packages/javascript/bh-shared-ui/src/constants.ts
Removes default background image from Table and Paper MUI components
This PR addresses: BED-4638
There are a number of container background colors that were not matching our color elevations because there was a background image also being applied to them.
visual tests
Before: 
After:
=> Bed 4638:  table root remove bgimage

cmd/api/src/api/v2/apiclient/auth.go, cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth_integration_test.go, cmd/api/src/api/v2/integration/auth.go, cmd/api/src/database/auth.go, cmd/api/src/database/auth_test.go
Closes BED-4580
Added `target_user_id` to DeleteAuthToken audit log
Updated unauthorized response to 403 (from 404)
Added additional failure cases to audit log such as the unauthorized case
This PR addresses: BED-4580
Updated tests
The audit log logic was elevated to the handler so the db related test had to be updated to remove audit log checks.
=> chore: BED-4580 - add audit log failures to delete auth token

cmd/ui/src/views/Explore/ContextMenu/CopyMenuItem.tsx
This change updates the styles for the submenu under "Copy" in the right click context menu on the Explore page to display correctly with dark mode.
This PR addresses: [BED-4639]
This particular component was missed during the initial dark mode implementation.
Visual confirmation that this menu matches the parent context menu in both dark and light mode
[BED-4639]: …
=> BED-4639:  Update Copy menu palette for dark mode

cmd/ui/src/components/SettingsMenu.tsx
Updates the support link to point directly to the help center.
This PR addresses: BED-4645
When TAMs or SEs demonstrate browsing to the documentation to customers, there is a risk that they get redirected to the authenticated ticket view, exposing customer information. This change points the link directly to the help center to avoid that redirect.
Validated locally
=> BED-4645: Update support link to point directly to docs

cmd/api/src/migrations/graph.go, cmd/api/src/migrations/manifest.go, packages/go/dawgs/drivers/neo4j/cypher.go, packages/go/dawgs/ops/ops.go, packages/go/dawgs/query/model.go
`Version_513_Migration` covers a bug discovered in ingest that would result in nodes containing more than one kind. For example, the following query should return no results: `(n:Base) where (n:User and n:Computer) return n` but, at time of writing, due to the ingest defect several environments will return results for this query.
For instances where nodes are discovered that contain more than one valid kind assignment, the node's kinds are reset to the matching base entity kind such that:
```
node.Kinds = Kinds{ad.Entity, ad.User, ad.Computer} must be reset to:
node.Kinds = Kinds{ad.Entity}
```
This PR addresses: BED-4641
Tested locally with a 1M+ node dataset.
- New feature …
=> BED-4641 - Create Ingest Defect Graph Migration

packages/go/dawgs/drivers/neo4j/cypher.go, packages/go/dawgs/drivers/neo4j/cypher_internal_test.go
This PR cherry-picks the fix for BED-4479 (#741) so it can be included in the `v5.13.0` release.
* This fix should be included as it's actively causing pain.
* This fix was tested in the original PR. It will be tested further in the release build.
- Code comments …
=> BED-4479 Cherry-pick fix to stage/v5.13.0

cmd/ui/src/App.tsx, cmd/ui/src/hooks/useFeatureFlags.tsx
Stops retying /features request at app entrypoint.
This PR addresses: BED-4660
Prevent loop of logging in and immediately getting logged out
Observing network requests
=> BED-4460: stop retrying /features request at app entrypoint

cmd/api/src/analysis/hybrid/hybrid_integration_test.go, cmd/api/src/test/integration/harnesses.go, packages/go/analysis/hybrid/hybrid.go
Fixes an edge case where a node can exist with a given `objectid` but may not have a `User` label due to not being directly collected or some other case where the label is missing. This includes checking each node we think we need to create for existence, and if it does already exist, adding the `User` label to that node.
This PR addresses: BED-4663
Fixes an important edge case we found in v5.13.0. This is being staged for hotfix v5.13.1
Used a debugger to pause on the first objectid that needed to be created because it wasn't found in our list of AD Users. During that pause, I did a `MERGE` for that objectid and ensured that the node had only `:Base`, no `:User`. I then resumed the debugger until the next item and checked Neo4j for the previous node. When not adding on the label, I saw …
=> BED-4663: Fix Hybrid Paths Failure When Node Exists But Not As AD User

cmd/api/src/services/entrypoint.go
Remove fatality from api initialization based off init analysis request
This PR addresses: BED-4664
Request analysis failures shouldn't cause api fatalities
Locally
=> BED-4664 fix: remove fatal return on init analysis

cmd/api/src/model/filter.go, cmd/api/src/model/filter_test.go, cmd/api/src/model/saved_queries.go, cmd/api/src/model/saved_queries_test.go
In order to support querying for saved_queries via description, we need to support a way to query strings with similarity. Currently, we support `eq` and `neq` predicates for string filters which would require the user to enter the enter saved query's description as the filter. This adds support for our already defined `in` predicate, which is used in our GraphDB, in Postgres.
This PR addresses: BED-4662
Allows filtering our PG database based on string likeness rather than exact match
I created 3 queries with the following `description` values:
> This is a test description
> An example description
> Contains test text
I then sent a request to `http://bloodhound.localhost/api/v2/saved-queries?description=in:test`
Note the query parameter `description=in:test`
I then verified that the …
=> BED-4662 implement new `in` predicate for string filtering on PG

cmd/ui/src/utils.ts
Block logout attempts after a 401 when the requested url is `/api/v2/features`
This PR addresses: BED-4666
When a user is logging in with MFA, if the page is unfocused and then refocused, the `/features` endpoint will 401 and force the user back to the username/password screen.
manual tests
=> BED-4666: remove logout on 401 /features

dockerfiles/bloodhound.Dockerfile, tools/docker-compose/api.Dockerfile
Reverts the version of SharpHound available for download in BHCE to v2.4.1 from v2.5.4
This PR addresses: BED-4668
No tests have been updated or added for this revert.
=> chore: revert available SharpHound version to v2.4.1

packages/javascript/bh-shared-ui/src/commonSearches.tsx
AZDevice nodes contain two properties "operatingsystem" and "operatingsystemversion". These can be used to deduct unsupported OS versions.
This is effectively an Entra version of the AD pre-saved query "Devices with unsupported operating systems". Returned systems by these two queries may overlap if they are Entra synced, but both queries have to be run to ensure full coverage.
This PR addresses: BED-4652
- Ran Cypher in multiple large BHE tenants, it did not fail and returned results
- Built BHCE, uploaded sample data, verified the query is in UI and it works …
=> BED-4652: Entra devices with unsupported operating systems

.github/workflows/publish.yml, .github/workflows/rc-publish.yml
Sets a run-name (title) for the publish workflow runs.
BED-4675
Currently the GitHub workflows for publishing builds use the default title for each workflow run. The default doesn't give any indication of which release the build is for. This sets it to use the triggering ref name, which should be the relevant tag.
N/A
=> BED-4675: Update publish workflows to set a relevant run-name

cmd/api/src/analysis/hybrid/hybrid_integration_test.go, packages/go/analysis/hybrid/hybrid.go
Removes the logic to convert unknown AD nodes into AD User nodes when making hybrid edges
This PR addresses: BED-4663
We don't want to alter unknown nodes for consistency, so the logic was removed. Some test parameters needed to be adjusted to cover the change properly.
Tests were altered to handle the correct logic and are passing
=> BED-4663: Followup

cmd/api/src/analysis/hybrid/hybrid_integration_test.go, dockerfiles/bloodhound.Dockerfile, tools/docker-compose/api.Dockerfile
This is a final followup to our hotfix issue BED-4663. The goal was to clean up some testing cases to ensure that places where we expect the nodes to be users are covered appropriately while allowing for the unknown edge case to only rely on `ad.Entity`.
This PR addresses: BED-4663
Testing cleanup identified while reviewing BED-4663 for the hotfix. This work will not be part of the hotfix, but was important to finish tying down for mainline.
Test updated and ran without any issues
- …
=> BED-4663: Testing ergonomics fix

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Added the following default limits to all pre-built queries:
- List objects returned: LIMIT 100
- Pattern returned: Limit 1000
This PR addresses: BED-4674
In larger environments, unlimited queries will result in returned data which exceeds the ability of a system to render performantly. By limiting the default returns, customers may get some data back, and then modify their query to target specific items, or to expand the limit. This reduces the risk of blowing out memory on a single click.
Ran each query in a local environment to insure they ran properly with proper results
- Read the …
=> BED-4674 - Add default limits to all queries

cmd/api/src/database/migration/migrations/v5.14.0.sql
Adds stepwise migration for v5.14.0 to add Postgres Dual Ingest record to feature flag table
Closes: BED-4689
From now forward, all new FF records must be added via a stepwise migration
Ran locally and confirmed record was added
=> chore: add FF migration for postgres dual ingest

cmd/api/src/api/v2/saved_queries.go, cmd/api/src/database/mocks/db.go, cmd/api/src/database/saved_queries.go
Updated usage of the `saved_query.id` field to always expect int64. This includes reading the value in from the API handler and passing through to the database functions.
This PR addresses: BED-4698
Light refactoring to make `savedQueryID` usages more consistent overall, including always treating as an int64 and using the same naming conventions everywhere.
Existing tests pass, no functional changes
- All new …
=> chore: refactored saved query id parameter to always expect int64

cmd/api/src/model/filter.go, cmd/api/src/model/filter_test.go, cmd/api/src/model/saved_queries.go, cmd/api/src/model/saved_queries_test.go
Revert #767 
We discussed using a new predicate instead of `in:`, but the changes were already staged for release.
This is to revert the implementation of the `in:` predicate in favor of BED-4726
Avoiding API changes from going out so that we may further improve on it before releasing to the public
I tested the `in:` predicate to ensure it returns an error as the predicate is no longer supported
I then tested the supported predicates for the `ListSavedQueries` endpoint to ensure they still worked
`in:` no longer working:
`eq:` description working as intended
`neq:` description returns nothing
`neq:` description returns data
`eq:` name returns data
`neq:` name returns data
- …
=> Revert BED-4662 PR 767

cmd/api/src/daemons/datapipe/decoders.go
This PR addresses: [BED-4320](https://specterops.atlassian.net/browse/BED-4320)
Using one of the test files from https://github.com/SpecterOps/BloodHound/wiki/Example-Data and changing the value from `*_domains.json`,
```json
{
"TargetDomainSid": "S-1-5-21-2845847946-3451170323-4261139666",
"TargetDomainName": "GHOST.CORP",
"IsTransitive": true,
"SidFilteringEnabled": false,
"TrustDirection": "Bidirectional",
"TrustType": "ParentChild"
},
```
after 
```json
{
"TargetDomainSid": "S-1-5-21-2845847946-3451170323-4261139666",
"TargetDomainName": "GHOST.CORP",
"IsTransitive": true,
"SidFilteringEnabled": false,
"TrustDirection": 1,
"TrustType": "ParentChild"
},
```
We then produce the error on the UI. …
=> fix(bed-4320): Return an error if decoding fails

cmd/api/src/database/mocks/db.go, cmd/api/src/model/unified_graph.go, cmd/ui/src/ducks/explore/reducer.ts, cmd/ui/src/utils.ts, cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItem.tsx, cmd/ui/src/views/Explore/utils.ts
Just some cleanup work solved by running `just prepare-for-codereview`
This PR addresses: BED-4735
Fixing up another issue in BHE and caught some linter fixes
No code was functionally changed
=> BED-4735: Linting Fixes

cmd/api/src/database/migration/migrations/v5.15.0.sql
Related BED-4363 follow-up fix
Identified a missing constraint that breaks the idempotency of v5.15.0
This PR addresses:  BED-4363
Locally ran both and ensured no issues
=> BED-4363 fix: missing constraint on roles

packages/go/analysis/ad/esc13.go, packages/go/analysis/ad/post.go, packages/go/dawgs/ops/traversal.go
This is an update to the traversal logic in ESC13 post processing for the func `groupIsContainedOrTrusted`.
ESC13 post processing logic involved checking whether a group is contained or trusted based on the domain being processed. Domain trusts, which are often "bidirectional", were being traversed but there was no check in the traversal for whether a cycle was encountered. Encountering a cycle was drastically increasing analysis times as the reverse walk for the pathVisitor would go back and forth between the trusting domains. 
The `ExpansionFilter` property of a TraversalPlan was exported so that it could be used outside of the package similarly to the already defined acyclic traversal …
=> fix: prevent cyclic traversals in esc13 post processing

cmd/api/src/daemons/datapipe/agi.go
Swap the db instance with `GetFlagByKeyer` interface .
This PR addresses: BED-4740
We only need the `GetFlagByKeyer` methods from `BloodhoundDB`. …
=> BED-4740: replace BloodhoundDB with GetFlagByKeyer

packages/cue/bh/azure/azure.cue, packages/go/graphschema/azure/azure.go, packages/javascript/bh-shared-ui/src/graphSchema.ts
Add `LoginURL` to `azure.cue` properties
This PR addresses: BED-4750
Running `just generate` off of `main` successfully runs, but it removes `azure.LoginURL` from the codebase. Running a subsequent generate will produce errors saying `azure.LoginURL` does not exist.
Adding `LoginURL` to the properties properly generates the file
Run `just generate` twice to ensure that the files are properly being generated and are not causing errors
- Added/updated tests to cover my …
=> BED-4750 added LoginURL to properties and re-generated files

cmd/api/src/database/migration/migrations/schema.sql, cmd/api/src/database/migration/migrations/v5.15.0.sql
- Moved the `adcs` feature flag to `schema.sql` where it should have been from this PR https://github.com/SpecterOps/BloodHound/pull/772
- Also bootstrapped it with updatable to false to be super safe
This PR addresses: BED-4363
Fixes a bug where adcs was updatable in bootstrapped environments due to order of migrations
bootstrapped db to ensure it wasn't updatable 
=> BED-4363 fix: adcs feature flag not in schema.sql

dockerfiles/bloodhound.Dockerfile
Fixes our Go version when building the distroless release image by copying from the official Go alpine image
This PR addresses: BED-4778
Edge commits (and eventually full release commits) are currently blocked by this issue
Needs to run in CI to be sure it's working properly. Local docker run seemed to indicate this will work fine.
=> BED-4778: Fix Go version in distroless release image

cmd/api/src/analysis/ad/adcs_integration_test.go, cmd/api/src/api/v2/file_uploads_integration_test.go
- Disabled failing integration tests
- Ticket: BED-4747
- Subtask above is from BED-4680
- Disabling the following tests will allow engineers to continue submitting PRs and not have significant errors
- Tested that all the disabled tests above were being skipped
=> BED-4747: Disable Failing Tests

.github/workflows/edge-publish.yml, dockerfiles/bloodhound.Dockerfile
Fixes multiarch builds so we stop failing for real this time
This PR addresses: BED-4778
Last attempt at a fix broke multiplatform builds since local testing for that case is difficult to set up
Mix of local testing and engaging the edge publish action by adding this branch to it during testing. Artifacts were tested on a Linux x86-64 machine and an Apple Silicon machine to ensure the final results were correct.
- Added/updated tests to cover my …
=> BED-4778: Fix multiarch builds

.env.example, docker-compose.dev.yml, local-harnesses/build.config.json.template, parca.yaml, tools/docker-compose/api.Dockerfile
- Adds a valid parca config for scraping pprof data from the toolapi in development modes
- This allows devs to instrument their dev versions of BHCE to see what function calls are using the most resources, as well as monitor CPU, memory, and goroutine usage
- Requires installing parca locally, but otherwise you just run it in the project root and everything "Just Works"
- Fixes default configuration for the toolapi to make it properly accessible/configurable
- Fixes an issue with dlv version after the upgrade to Go 1.23
This PR addresses: BED-4781
We need to use parca internally for some instrumentation when evaluating features and it makes sense to standardize our config, making it easier for anyone wanting to work on BloodHound to run the instrumentation.
Locally tested across all …
=> BED-4781: Add Parca Config for ToolAPI

cmd/ui/src/views/EarlyAccessFeatures/EarlyAccessFeatures.tsx
Fixes button alignment on Early Access page when the feature flag description extends the full width of the FF card.
This PR addresses: BED-4746
The description of the recent `Automatically add parent OUs` feature flag caused the enable/disable button to wrap to the next line. The expectation is that the button stays aligned to the right of the card and centered vertically.
visual tests
Previous:
Updated:
- All new and …
=> BED-4746: button alignment on early access page

.github/CODEOWNERS
This PR addresses: BED-4776
Adds a new CODEOWNERS file to declare members of @SpecterOps/bloodhound-engineering as the code owners for the entire repository.
This change will enable us to require at least 1 approval from a member of the BloodHound Engineering team for all future pull requests.
To learn more about code owners please read the docs kindly provided by GitHub.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
There are no functional code changes present in this PR.
- Read the Contributing …
=> BED-4776: Add .github/CODEOWNERS

tools/docker-compose/api.Dockerfile
Point `air` to the new `air-verse` organization
This PR addresses: BED-4789
`air` has moved from github.com/cosmtrek/air to github.com/air-verse/air
Destroy local containers with:
`docker system prune -a`
Recreate the local containers with:
`just bh-dev`
Ensured that the containers all spin up and the `AIR` console output is shown
=> BED-4789 switch air from comstrek repo to air-verse

cmd/api/src/analysis/ad/adcs_integration_test.go, packages/go/analysis/ad/adcs.go, packages/go/analysis/ad/adcscache.go, packages/go/analysis/ad/esc1.go, packages/go/analysis/ad/esc10.go, packages/go/analysis/ad/esc13.go, packages/go/analysis/ad/esc3.go, packages/go/analysis/ad/esc4.go, packages/go/analysis/ad/esc6.go, packages/go/analysis/ad/esc9.go
Added RWMutex to the adcs cache
Swapped to a getter / setter approach to help protect concurrent access to the inner properties with correct locking
This PR addresses: BED-4796
Analysis was reporting concurrent writes to maps across goroutines./
Relied on testing but should be rigorously tested in larger environments
=> refactor: adcs cache with RWMutex

cmd/api/src/daemons/datapipe/ingest.go, cmd/api/src/daemons/datapipe/ingest_test.go, packages/javascript/bh-shared-ui/src/views/Explore/fragments.test.tsx, packages/javascript/bh-shared-ui/src/views/Explore/fragments.tsx
Prevents 'reconcile' from being persisted in node properties upon ingest.
Prevents 'reconcile' from being displayed in the entity panel if already persisted.
This PR addresses: BED-4623
Unit tests have been added.
=> fix: filter node property at ingest and for entity panel display

README.md
Changed the link for 'examples/docker-compose/docker-compose.yaml'.  The file is now called 'examples/docker-compose/docker-compose.yml'
The original link results in a 404 as the file did not exist, due to the extension change
This PR addresses: BP-881
Documentation update, no testing needed …
=> BP-881: Update README.md to reflect the docker-compose.yml filename change, which breaks the hyperlink

packages/go/openapi/doc/openapi.json, packages/go/openapi/src/schemas/model.audit-log.yaml, packages/go/openapi/src/schemas/model.auth-token.yaml, packages/go/openapi/src/schemas/model.client-scheduled-job.yaml, packages/go/openapi/src/schemas/model.client.yaml, packages/go/openapi/src/schemas/model.components.timestamps.yaml, packages/go/openapi/src/schemas/model.user.yaml
Currently we incorrectly apply readOnly to ref properties like this:
```yaml
status:
allOf:
- $ref: './enum.audit-log-status.yaml'
- readOnly: true
- ```
It should be applied like this:
```yaml
status:
readOnly: true
allOf:
- $ref: './enum.audit-log-status.yaml'
```
This PR addresses: BED-4736
=> fixed incorrect usage of readonly properties with model refs

cmd/api/src/api/v2/app_config.go, cmd/api/src/api/v2/app_config_integration_test.go, cmd/api/src/api/v2/app_config_test.go, cmd/api/src/api/v2/auth/auth.go, cmd/api/src/bootstrap/server.go, cmd/api/src/database/app_config.go, cmd/api/src/database/featureflags.go, cmd/api/src/database/migration/migrations/v5.16.0.sql, cmd/api/src/database/parameters.go, cmd/api/src/database/parameters_test.go, cmd/api/src/model/appcfg/flag.go, cmd/api/src/model/appcfg/parameter.go, cmd/api/src/model/appcfg/parameter_test.go, cmd/api/src/model/audit.go, cmd/api/src/utils/validation/duration_validator.go, cmd/api/src/utils/validation/duration_validator_test.go, cmd/api/src/utils/validation/mocks/validator.go, cmd/api/src/utils/validation/password_validator.go, cmd/api/src/utils/validation/password_validator_test.go, cmd/api/src/utils/validation/registry.go, cmd/api/src/utils/validation/required_validator.go, cmd/api/src/utils/validation/required_validator_test.go, cmd/api/src/utils/validation/validator.go
- Light cleanup of the parameters service
- Added reconciliation prune TTLs to parameters
- Added duration schema validation support
- Moved reconciliation feature flag to parameters while maintaining current flag value
- Fixed incorrect neo4j configuration loading bug
Blocker: BED-4611 should be merged prior to this one
This PR addresses: BED-4676
Added new integration tests
Locally hit api via Bruno
Updated existing tests …
=> BED-4676 feat: Add support for prune TTLs and move reconciliation feature flag to parameters

cmd/api/src/auth/role.go, cmd/api/src/database/migration/migrations/v5.16.0.sql
Added a migration to add ReadOnly role the SavedQueriesRead permission and updated the role template accordingly 
This PR addresses: BED-4835
Fixes issue where ReadOnly users are not able to access saved queries
Spin up BH `just bhce-dev`
Create or use an existing User with the ReadOnly role
Send a request to
`GET /api/v2/saved-queries?scope=owned` as the ReadOnly user
And expect a 200 response back
Screenshot of the bug running in `main`:
- …
=> BED-4835 Add SavedQueriesRead Permission To ReadOnly Role

cmd/api/src/api/v2/audit.go, cmd/api/src/api/v2/audit_test.go, cmd/api/src/api/v2/helpers.go, cmd/api/src/model/pagination.go
- Fixes an issue where `skip` parameter is not parsed from the `/api/v2/audit` endpoint, resulting in log output not starting at the specified offset
Currently, this endpoint only supports using `offset` to specify skip, as opposed to other endpoints which uses `skip`.  This change enables the endpoint to support both `offset` and `skip` and uses whichever one is populated. If they are both populated, the endpoint uses the `skip` parameter value.
This PR addresses: BED-4128
Unit tests have been updated
- Open API …
=> BED-4128: Fix skip for audit endpoint

cmd/api/src/daemons/datapipe/cleanup.go, cmd/api/src/daemons/datapipe/cleanup_test.go
This updates the OrphanFileSweeper to properly preserve intended files when cleaning up ingest files. Previously it did not handle being passed filenames with a path, but would only work for plain filenames. Now it will properly compare filenames with a path to see if they should be preserved.
This PR addresses: BED-4388
If the API was restarted during ingest, multiple valid but not yet processed ingest files would be deleted. This would cause file not found errors when attempting to process those files, as well as requiring another collection to reacquire the deleted ingest data.
I ran AzureHound locally and triggered an on-demand collection. I then monitored the ingest directory during the collection process and restarted the API while there were multiple files yet to be processed. I …
=> BED-4388: Properly handle paths passed to OrphanFileSweeper

cmd/api/src/bootstrap/initializer.go, cmd/api/src/cmd/bhapi/main.go, cmd/api/src/daemons/api/toolapi/api.go, cmd/api/src/services/entrypoint.go
- Added a preMigrationDaemons property to initializer struct in order to allow daemons to start before migrations are run
- Moved the tools api daemon to the preMigrationDaemons property to launch the API prior to migrations
- Added a `/health` endpoint for infrastructure & container management
This PR addresses: BED-4696
Long running migrations on large datasets prevent the bh API `/health` endpoint from starting which can trip container management automation tied to the `/health` endpoint. This bh API `/health` endpoint remains unchanged and can be used in conjunction with the above to determine where in the bootstrap the process is.
Force added a couple minutes sleep to the migration check
Hit GET `0.0.0.0:2112/health` after launching before migration sleep finishes.
- New feature …
=> BED-4696 feat: add preMigrationDaemons support

packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10a/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC4/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9a/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9b/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9b/WindowsAbuse.tsx
ESC9b and ESC10b require the attacker to modify the SPN of a victim account. Add that step to the abuse steps for those edges.
This PR addresses: BED-4804
Verified that all the abuse sections looks good.
=> esc9b and esc10b abuse info improvement

packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Enroll/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Enroll/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Enroll/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
Add abuse info for GenericAll, GenericWrite, WriteOwner, Owns, WriteDacl, and AllExtendedRights against ADCS nodes.
The abuse info was missing for those edges against those nodes.
This PR addresses: BED-3945
With this data: 
[20240731002117_BloodHound.zip](https://github.com/user-attachments/files/16898329/20240731002117_BloodHound.zip)
=> Add abuse info for generic ACL edges against ADCS nodes

cmd/api/src/database/migration/migrations/v5.16.0.sql, packages/go/cypher/models/pgsql/format/format_test.go, packages/go/cypher/models/pgsql/functions.go, packages/go/cypher/models/pgsql/model.go, packages/go/cypher/models/pgsql/pgtypes.go, packages/go/cypher/models/pgsql/translate/expansion.go, packages/go/dawgs/drivers/pg/batch.go, packages/go/dawgs/drivers/pg/query/format.go, packages/go/dawgs/drivers/pg/query/sql/schema_up.sql, packages/go/log/log.go
This change remove MERGE in favor of an edge composite constraint and INSERT with ON CONFLICT.
This PR addresses: BED-4839
The MERGE keyword comes with come caveats that require a full linear table scan for each insert, trashing performance of ingest in PG. Instead, we should move to a composite constraint and an INSERT w/ ON CONFLICT statement.
Local and integration testing.
- Added/updated tests …
=> BED-4839 - PG Ingest Fixes

.github/CODEOWNERS
Reverts SpecterOps/BloodHound#839
Reverting this since it is creating unwanted noise in emails by subscribing the entire team to every PR opened.
=> Revert "BED-4776: Add .github/CODEOWNERS"

cmd/api/src/daemons/datapipe/jobs.go, cmd/api/src/services/fileupload/file_upload.go
Used `bomenc.NormalizeToUTF8()` to normalize files during extraction while processing zip files for ingest.
BED-4725
Currently JSON files in an uploaded zip file that are encoded with a BOM marker or alternative UTF format fail to ingest.
Uploaded a zip file containing an UTF16LE encoded JSON file to see if it would ingest without errors.
=> BED-4725: normalize files to UTF8 when extracting zip files for ingest

packages/go/analysis/azure/tenant.go
It would be better to use Measure instead of LogAndMeasure for this call. Measure intentionally does not log unless the measured call exceeds a wall time of 1 second. The intent of this call appears to be identifying potential slow calls so the refactor feels right.
Log is too noisy otherwise.
Local testing …
=> fix: BED-4869 clean up logging for TenantRoles

cmd/ui/src/App.tsx
Added selectors to target elements that were not responding to the dark / light mode functionality in API explorer
This addresses ticket [BED-4753](https://specterops.atlassian.net/browse/BED-4753)
Tested manually.
https://github.com/user-attachments/assets/783c8e58-2c87-43cb-bc72-69af2900af47
[BED-4753]: https://specterops.atlassian.net/browse/BED-4753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> BED-4753: Added styling selectors to address sections in api explorer not working in dark/light mode

cmd/api/src/database/migration/migrations/v6.0.0.sql
Marks dark mode as default enabled and hides the flag from the BloodHound UI in preparation for removal of the feature flag and related code paths.
Dark mode is ready for primetime. We should enable it for all installs by default.
Local testing with database access. …
=> feat: BED-4879 enable by default and hide dark mode feature flag

packages/javascript/bh-shared-ui/src/components/HelpTexts/Contains/Abuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Contains/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
Add abuse info text for Container nodes and Contains edge.
This PR addresses: BED-3945
Uploaded data and checked the entity panels.
=> BED-3945: More abuse info

packages/javascript/bh-shared-ui/src/components/CitrixRDPConfiguration/CitrixRDPConfiguration.test.tsx
Cleaned up test to match best practices. Removed multiple assertions in a waitFor method, used findByText in queries where  needed instead of getByText.
This addresses [BED-4888](https://specterops.atlassian.net/browse/BED-4888). Really to keep tests as consistent and with as many known best practices as possible.
Ran the tests locally.
[BED-4888]: …
=> BED-4888: Cleaned up citrix RDP configuration tests

.env.example, docker-compose.dev.yml, justfile
- Add authentik to docker-compose.dev.yml
- Added profiles bh-sso as well as bh-sso-only  for just support to quickly spin up authentik and bhe
- Ticket: BED-4655
- This adds authentik - https://github.com/goauthentik/authentik to the dev stack. It provides us with an IDP that supports a variety of SSO protocols so we can locally test and support OIDC / SAML auth flows.
- Run `just bh-sso` Note you have to go to `http://authentik.localhost/if/flow/initial-setup/` to register an admin password before you can progress further
- Read the …
=> BED-4655: Add Authentik to docker-compose.dev.yml

cmd/api/src/database/migration/migrations/v6.1.0.sql, cmd/api/src/database/migration/migrations/v6.2.0.sql, cmd/api/src/model/appcfg/flag.go
Adds a new feature flag to the current migration file with the key `updated_posture_page`. The flag should initially be set to false and should be non user-updatable.
This feature flag will be used for toggling to the new posture page during development.
This PR addresses: [BED-4934]
Confirmed migration runs on startup and creates the new flag with the expected settings and initial value.
- Added/updated tests to cover my …
=> BED-4934: Posture page feature flag

cmd/api/src/database/datapipestatus.go, cmd/api/src/database/datapipestatus_test.go
Fixes a logic bug that was causing last_analysis_run_at to run every time the datapipe status changed
This PR addresses: BED-4947
This bug was causing scheduled analysis to never run
- Existing test has been updated to account for the correct, intended behavior
=> BED-4947: Fix Last Analysis Run At Bug

.github/workflows/vuln-scan.yml
Use the aws images for the trivy dbs. Suggested workaround from the community
* https://github.com/orgs/community/discussions/139074
* https://github.com/aquasecurity/trivy-action/issues/389
This PR addresses: https://specterops.atlassian.net/browse/BED-4956
- Added/updated tests to …
=> fix: use aws registry mirrors for vuln scan

cmd/api/src/api/registration/v2.go, cmd/api/src/auth/permission.go, cmd/api/src/auth/role.go, cmd/api/src/auth/role_test.go, cmd/api/src/database/analysisrequest.go, cmd/api/src/database/migration/migrations/v6.2.0.sql
…
Create a new permission that controls the ingestion/file upload routes, and add that permission to the roles that currently have GraphDBWrite (and remove that permission where necessary)
This PR addresses: BED-4903 and BED-4950
The permission intended to control upload rights for clients should only be allowed to perform uploads. The GraphDBWrite permission also includes to modify access groups and trigger manual analysis runs. …
=> Create a new permission to limit the scope for RoleUploadOnly

cmd/api/src/api/auth.go, cmd/api/src/api/constant.go, cmd/api/src/api/error.go, cmd/api/src/api/registration/v2.go, cmd/api/src/api/v2/auth/oidc.go, cmd/api/src/api/v2/auth/sso.go, cmd/api/src/database/mocks/db.go, cmd/api/src/database/oidc_providers.go, cmd/api/src/database/oidc_providers_test.go, cmd/api/src/database/sso_providers.go, cmd/api/src/database/sso_providers_test.go, cmd/api/src/go.mod, cmd/api/src/go.sum, docker-compose.dev.yml, packages/go/crypto/go.mod, packages/go/crypto/go.sum, packages/go/cypher/go.mod, packages/go/cypher/go.sum, packages/go/dawgs/go.mod, packages/go/dawgs/go.sum, packages/go/log/go.mod, packages/go/log/go.sum, packages/go/schemagen/go.mod, packages/go/schemagen/go.sum, packages/go/stbernard/go.mod, packages/go/stbernard/go.sum
**Note: This shouldn't be merged into BED-4851 and should wait until both https://github.com/SpecterOps/BloodHound/pull/896 and https://github.com/SpecterOps/BloodHound/pull/894 are merged. It was just selected as the base for easier PR review.**
Add login handler for OIDC
This PR addresses: BED-4768
In order to support OIDC we need to have a generic login handler
This is used in conjunction with Authentik locally to verify proper redirection occurred.  …
=> BED-4768 feat: add login handler for OIDC

cmd/api/src/api/v2/auth/sso.go, cmd/api/src/auth/bhsaml/db.go
This update applies `FormatSAMLProviderURL` to the SAML provider details in the `ListAuthProviders` API endpoint for consistent and correct formatting of provider information.
This PR addresses: BED-4766
- Manually validated through API endpoint requests
- Confirmed with existing unit and integration tests
=> BED-4766: Correctly Format SAML Provider Details in ListAuthProviders Endpoint

cmd/api/src/daemons/datapipe/convertors.go, packages/go/ein/ad.go, packages/go/ein/ad_test.go, packages/go/ein/incoming_models.go
Adds logic to EIN to convert certain string properties to integers/bools as necessary. 
Counterpart to https://github.com/BloodHoundAD/SharpHoundCommon/pull/173
This PR addresses: https://specterops.atlassian.net/browse/BED-4928
Unit tests written
=> feat: add conversion logic to EIN to fix badly typed properties

cmd/api/src/api/auth.go, cmd/api/src/api/auth_internal_test.go, cmd/api/src/api/saml/saml.go, cmd/api/src/api/saml/saml_internal_test.go, cmd/api/src/auth/model.go, cmd/api/src/config/default.go, cmd/api/src/database/sso_providers.go
The bugfix provided from #913 is no longer valid after the refactoring of `createSessionFromAssertion` from the latest changeset in #898. This PR addresses BED-4931, factoring the changes from #898
This PR addresses: BED-4931
- Manually tested via API explorer
- Unit testing in `auth_internal_test.go`
- Unit testing in `saml_internal_test.go`
=> BED-4931: Add Audit Logging for SAML Authentication Attempts after BED-4767

cmd/api/src/api/registration/v2.go
Removed FF gate on SSO delete provider endpoint to support deletion when FF is disabled.
This PR addresses: BED-4852 bug fix
Cannot delete SAML providers when FF is disabled
Locally tested 
=> fix: remove FF from delete sso-providers endpoint

cmd/api/src/api/auth.go, cmd/api/src/api/registration/v2.go, cmd/api/src/api/saml/saml.go, cmd/api/src/api/saml/saml_internal_test.go, cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/oidc.go, cmd/api/src/api/v2/auth/saml.go, cmd/api/src/api/v2/auth/sso.go
- Setup redirects for old saml urls
- Dynamically generated the saml providers inside handlers
This PR addresses: BED-4921
Allows old saml urls to continue to function by redirecting to the new generic sso login flow 
Locally
=> refactor: old saml urls redirect to new sso url

cmd/api/src/api/v2/auth/saml.go, packages/go/graphschema/ad/ad.go, packages/go/graphschema/azure/azure.go, packages/go/graphschema/common/common.go, packages/javascript/bh-shared-ui/src/commonSearches.tsx
Multiple updates to pre-saved Cypher queries to add functionality and fix issues. Details in context below.
This PR addresses:
- BED-4973: Kerberoastable queries did not properly include logic for accounts being enabled and excluding the KRBTGT account
- BED-4972: Saved Cypher queries utilized multiple quote styles making consumption via API a non-ideal experience in handling both double and single quotes.
- BED-4974: Re-adds the old "Map OU structure" query
- BED-4975 / #680: Adds two shortest path queries related to Owned objects
Tested locally with test data, validating that queries ran and returned accurate data.
- New feature (non-breaking change which adds …
=> FEAT/CHORE/BUG: Cypher Updates

cmd/api/src/migrations/graph.go, packages/go/cypher/models/cypher/functions.go, packages/go/cypher/models/pgsql/functions.go, packages/go/cypher/models/pgsql/test/translation_cases/pattern_expansion.sql, packages/go/cypher/models/pgsql/translate/expression.go, packages/go/cypher/models/pgsql/translate/translator.go, packages/go/dawgs/drivers/pg/query/query.go, packages/go/dawgs/drivers/pg/query/sql/schema_up.sql, packages/go/dawgs/drivers/pg/types.go
PG query path related work.
Usually not a fan of stacked changed but these are all super small in scope and it's less thrashing against the staging branch.
Below are the fixed tickets:
* BED-4981 - Correctly Sanitize Index and Constraint Input from PostgreSQL
* BED-4980 - Fixup int32 Types in PostgreSQL Query Path
* BED-4982 - Implement Cypher Split Function for PgSQL Translation
* Updated unit and integration tests
- Code comments (GoDocs …
=> PostgreSQL Related Query Path Fixes

cmd/api/src/api/v2/auth/saml.go, cmd/ui/src/views/Login.tsx
- Ensure that the entity id is correctly formatted for SAML provider flow
- Fix handling for no sso-provider on UI 
This PR addresses: BED-4921
Currently fallback to /metadata url breaks existing SAML flow
Live.
=> BED-4921 fix: missing entity id for saml provider

packages/javascript/bh-shared-ui/src/commonSearches.tsx
Adds logic to exclude GMSAs and MSAs from Kerberoastability logic.
This PR addresses: BED-4973
Testing feedback yielded that this was missed in the first round. Updating logic for accuracy.
Validated in local test
=> BED-4973 round 2: Add logic to exclude GMSA/MSA from Kerberoastable

cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/saml.go
- Surface parsing cert errors
- Fix missing format uri on `/api/v2/saml/providers/{provider_id}`
Addresses: https://github.com/SpecterOps/BloodHound/issues/949
Addresses: BED-4768
Addresses: BED-4767
Addresses: BED-4921
When we refactored the saml login flow, we obfuscated any parsing cert errors under 500, this keeps the 500 but surfaces the specific error now
Locally with bruno
Before:
- Added/updated tests …
=> BED-4921 chore: surface cert parsing error

packages/go/analysis/azure/post.go, packages/go/analysis/post.go, packages/go/dawgs/drivers/pg/query/format.go, packages/go/dawgs/drivers/pg/statements.go
Revert and change for edge creation during post-processing.
* Related to BED-4997
* Fixes BED-5044
The changes authored had a far greater impact on memory than expected. This ticket exists to cover reverting the change and authoring a small update to the SQL used for create to change the edge create statement into an edge upsert statement.
Local test w/ folk on Zoom.
=> BED-5044 - revert edge constraint map checking in API and prefer SQL upsert

cmd/api/src/api/v2/auth/auth.go
- Fix not removing auth secret on update user to SSO
This PR addresses: BED-5048 
Need to delete auth secret when swapped to SSO
Locally
=> BED-5048 fix: removing authSecret with SSO assignment

packages/javascript/bh-shared-ui/src/components/InfiniteScrollingTable/InfiniteScrollingTable.tsx
This change moves the style definition from the FixedSizeList/InfiniteLoader to the Row element
This PR addresses: BED-4930
By moving the style definition from the InfiniteLoader to the Row, we are able to accurately determine the index of the row that is being mapped.
What was happening is that the InfiniteLoader adds and removes elements from the DOM when they come in and out of view. This causes the `nth-child(odd)` and `nth-child(even)` bindings to change with each scroll.
I ran Bloodhound Enterprise and navigated to a panel that utilized the InfiniteLoader element and verified that the colors were no longer shifting while scrolling …
=> BED-4930 fixed color shift in panel lists

cmd/api/src/api/v2/auth/sso.go, cmd/api/src/database/samlproviders.go, cmd/api/src/model/samlprovider.go, packages/javascript/bh-shared-ui/src/components/SSOProviderInfoPanel/SSOProviderInfoPanel.tsx, packages/javascript/js-client-library/src/types.ts
Add callback uri info for easy copy pasting when setting up OIDC
This PR addresses: BED-5012
Ran locally
=> BED-5012 feat: add callback uri to oidc details

cmd/api/src/database/migration/migrations/v6.3.0.sql
- Sets the `updated_posture_page` feature flag to true in the 6.3.0 migration file
This PR addresses: https://specterops.atlassian.net/browse/BED-5073
Enables the updated Posture page feature flag. For BHE use case only.
No logical changes …
=> Set `updated_posture_page` feature flag to true

packages/go/openapi/doc/openapi.json, packages/go/openapi/src/paths/attack-paths.domains.id.details.yaml
Updates were made to the API documentation for finding detail expected type values
This PR addresses: BED-4403
There was a discrepancy in the originally documented values with the column type in the migration.
=> chore: update docs for finding details endpoint

cmd/api/src/api/registration/v2.go, cmd/api/src/api/v2/auth/oidc.go, cmd/api/src/api/v2/auth/oidc_test.go, cmd/api/src/api/v2/auth/saml.go, cmd/api/src/api/v2/auth/sso.go, cmd/api/src/auth/saml.go, cmd/api/src/database/auth_test.go, cmd/api/src/database/mocks/db.go, cmd/api/src/database/oidc_providers.go, cmd/api/src/database/oidc_providers_test.go, cmd/api/src/database/samlproviders.go, cmd/api/src/database/sso_providers.go, cmd/api/src/model/audit.go, cmd/api/src/model/samlprovider.go, cmd/api/src/utils/validation/url_validator.go
- Added PATCH `/sso-providers/{sso_provider_id}` to update SSO provider info
This PR addresses: BED-5068
Adds support for editing sso provider info without the need to delete it and disassociate the users. It also terminates active sessions.
Unit tests
Locally through Bruno …
=> Bed-5068 feat: Add PATCH endpoint to update sso providers

cmd/api/src/api/error.go, cmd/api/src/database/db.go, cmd/api/src/database/ingest.go, cmd/api/src/database/mocks/db.go
This function is part of supporting BED-5079 in lifting some additional metrics for infrastructure to monitor.
Previously, without this count function present, the metric for monitoring ingest queue depth would fetch the entire contents of each row and then use the golang `len(...)` function to acquire a count.
This reduces the necessary work for the DB and drops network bandwidth for this metric significantly.
Local testing. Unsure as to the value of testing this function in unit or integration.
- Open API …
=> feat: BED-5079 - Add Ingest Task Count Function

packages/go/analysis/post_integration_test.go, packages/go/openapi/doc/openapi.json, packages/go/openapi/src/paths/sso.sso-providers.id.yaml, packages/go/openapi/src/paths/sso.sso-providers.oidc.yaml, packages/javascript/bh-shared-ui/src/components/SSOProviderTable/SSOProviderTable.tsx, packages/javascript/bh-shared-ui/src/components/UpsertOIDCProviderDialog.tsx, packages/javascript/bh-shared-ui/src/components/UpsertOIDCProviderForm.tsx, packages/javascript/bh-shared-ui/src/components/UpsertSAMLProviderDialog/UpsertSAMLProviderDialog.tsx, packages/javascript/bh-shared-ui/src/components/UpsertSAMLProviderDialog/index.ts, packages/javascript/bh-shared-ui/src/components/UpsertSAMLProviderForm/UpsertSAMLProviderForm.test.tsx, packages/javascript/bh-shared-ui/src/components/UpsertSAMLProviderForm/UpsertSAMLProviderForm.tsx, packages/javascript/bh-shared-ui/src/components/UpsertSAMLProviderForm/index.ts, packages/javascript/bh-shared-ui/src/components/index.ts, packages/javascript/bh-shared-ui/src/views/SSOConfiguration/SSOConfiguration.tsx, packages/javascript/js-client-library/src/client.ts, packages/javascript/js-client-library/src/types.ts
- Renamed create provider dialogs to upsert
- Added edit support to provider dropdown
NOTE: https://github.com/SpecterOps/BloodHound/pull/975 should be merged first
This PR addresses: BED-5067
Currently you cannot edit a SSO provider without deleting it first. This adds support for the UI to hit the new PATCH endpoints created by https://github.com/SpecterOps/BloodHound/pull/975
Locally and through unit tests
- Code comments (GoDocs / …
=> BED-5067 feat: add edit sso provider support to ui

cmd/api/src/api/registration/v2.go, cmd/api/src/api/v2/auth/saml.go, packages/go/crypto/tls.go, packages/go/openapi/doc/openapi.json, packages/go/openapi/src/openapi.yaml, packages/go/openapi/src/paths/sso.sso-providers.id.signing-certificate.yaml, packages/javascript/bh-shared-ui/src/components/SSOProviderInfoPanel/SSOProviderInfoPanel.tsx, packages/javascript/js-client-library/src/client.ts
- Added GET `/sso/{sso-provider-slug}/signing-certificate` for SAML providers
- Added download button to UI to download it
- Fixed formatting cert parsing checks
This PR addresses: BED-5010
Currently it's not easy to retrieve the signing certificate for SAML providers. This rectifies that.
Unit tests + locally
=> Bed-5010 feat: Add ability to download SAML signing certificate

cmd/api/src/api/tools/pg.go, packages/go/dawgs/drivers/pg/query/format.go, packages/go/dawgs/drivers/pg/statements.go
This small change updates a few improper casts to `int4` in certain SQL formatting statements.
While this won't blow up in any local test, customers that have large environments will eventually exhaust ID space for `int32`. 
Validated with schema. Types need to match from the SQL schema in `schema_up.sql` and in all statements addressing either the `node` or `edge` tablespace.
=> fix: BED-5080 - move improper int4 casts to int8

packages/go/dawgs/drivers/pg/pg_integration_test.go, packages/go/dawgs/drivers/pg/query/sql/schema_up.sql
Removing more int32 cruft.
Without this change, type casting using the PgSQL composite types will fail due to the use of `int4` width ID types.
Regression test added.
=> BED-5080 - remove additional integer types from SQL schema

cmd/api/src/database/migration/migrations/v6.3.0.sql
Added migration to delete leftover auth_secret from users that were designated SSO
This PR addresses: BED-5103
A bug was introduced that was recently patched but didn't address any existing users in a bad state. This should address those users.
Locally
=> BED-5103 fix: users in bad auth state

packages/go/analysis/ad/adcs.go
Correct edge names in log.Warnf() calls. Appears to be a copy/paste mistake. 
This PR addresses: https://specterops.atlassian.net/browse/BED-5059
Analysis of existing code. Imported default data and noticed a few warnings are triggered and now print out as expected:
```
bhe-api-1       | {"level":"info","time":"2024-12-02T23:07:47.050043946Z","message":"Finished building adcs cache"}
bhe-api-1       | {"level":"warn","time":"2024-12-02T23:07:47.232343975Z","message":"Post processing for ADCSESC6a: property isuserspecifiessanenabled: property not found"}
bhe-api-1       | {"level":"warn","time":"2024-12-02T23:07:47.232376467Z","message":"Post processing for ADCSESC6b: property isuserspecifiessanenabled: property not found"}
bhe-api-1       | …
```
=> BED-5059 - Wrong edge name referenced in warning message

cmd/api/src/database/migration/migrations/v6.3.0.sql
- Sets the `oidc_support` feature flag to true in the 6.3.0 migration file
Ticket: BED-5120
- Enables the `oidc_support` feature flag. For BHE use case only
- No logical changes
=> BED-5120: Enable OIDC for use

packages/go/analysis/ad/ad.go
Removes DCOM Users and Performance Log Users from default Tier Zero.
This PR addresses: BED-5183
We added these groups to default Tier Zero as a new attack revealed how they could compromise any user logged into DCs. Microsoft has now patched that (see end note): [Hello: I’m your Domain Admin and I want to authenticate against you](https://decoder.cloud/2024/04/24/hello-im-your-domain-admin-and-i-want-to-authenticate-against-you/)
Locally.
- …
=> Update default tier zero

packages/go/analysis/ad/ad.go
Removes DnsAdmins from default Tier Zero.
This PR addresses: BED-5199
We added DnsAmins to default Tier Zero because the group can in a default AD control DNS in AD, which enables relay attacks. However, some organizations do not host DNS on DCs, and in that case we do not know if the group is abusable, but we think it is not. We will therefore remove it from default Tier Zero. 
Locally.
- All new and …
=> Remove DnsAdmins from default tier zero

cmd/ui/src/main.tsx
This change fixes the infinite loop caused by the mock service workers in local dev.
This PR addresses: [BED-5072]
The issue causes the local dev environment to randomly go into an infinite loop when first starting a server.
This was tested manually to ensure the infinite loop was no longer happening.
[BED-5072]: https://specterops.atlassian.net/browse/BED-5072?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> BED-5072 fix local dev infinite loop

packages/javascript/bh-shared-ui/src/components/NoDataDialog/NoDataDialog.test.tsx, packages/javascript/bh-shared-ui/src/components/NoDataDialog/NoDataDialog.tsx, packages/javascript/bh-shared-ui/src/components/NoDataDialog/index.tsx, packages/javascript/bh-shared-ui/src/components/index.ts
Added a NoDataDialog component as requested in BED-5110.
This PR addresses: [BED-5110](https://specterops.atlassian.net/browse/BED-5110)
This component addresses the need to have a shared dialog component that we can use across platforms to let the user know that no data is available.
This has been tested with unit tests to check proper rendering of the dialog component. It was also tested via a local dev environment to ensure proper functionality.
- …
=> BED-5110 added NoDataDialog component

packages/go/cypher/models/pgsql/format/format.go, packages/go/cypher/models/pgsql/operators.go, packages/go/cypher/models/pgsql/pgtypes.go, packages/go/cypher/models/pgsql/pytypes_test.go, packages/go/cypher/models/pgsql/test/translation_cases/nodes.sql, packages/go/cypher/models/pgsql/test/translation_cases/pattern_binding.sql, packages/go/cypher/models/pgsql/test/translation_cases/stepwise_traversal.sql, packages/go/cypher/models/pgsql/test/translation_cases/update.sql, packages/go/cypher/models/pgsql/translate/expression.go, packages/go/cypher/models/pgsql/translate/expression_test.go, packages/go/cypher/models/pgsql/translate/translation.go, packages/go/cypher/models/pgsql/translate/translator.go, packages/go/cypher/models/pgsql/translate/update.go
Latest batch of CySQL changes.
This changeset address the following tickets:
* BED-5201 - Enforce Better Type Checking in CySQL Frontend
* BED-5192 - Enforce Correct JSONB Operators for Type Conversion
* BED-5193 - Ensure Function Return Signature Null Conversion
* BED-5185 - Correctly Coerce Bare Property Lookups as Boolean
Translation tests have been added for all validated cases.
- Added/updated …
=> CySQL Fixes and Updates

packages/go/dawgs/graph/node.go, packages/go/dawgs/graphcache/cache.go
This prevents the possibility of missing nodes causing a panic in caching logic for traversal.
Seeing this happen in two large environments. This also cleans up caching logic that could panic.
Integration test coverage.
=> CySQL Fix Poor Type Negotiation for []graph.ID Parameters

packages/go/graphschema/ad/ad.go, packages/go/graphschema/azure/azure.go, packages/go/graphschema/common/common.go, packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/LinuxAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
- Cover Windows LAPS in read LAPS password abuse info
- Remove incorrect non-LAPS computer abuses for AllExtendedRights
- Remove incorrect read LAPS abuse for domain nodes
This PR addresses: BED-5174 (https://github.com/SpecterOps/BloodHound/issues/1016) and BED-5175
The current abuse information around reading LAPS password contains incorrect information and its also missing information about Windows LAPS. This PR fixes that issue.
Tested with this dataset:
[20241001082802_BloodHound.zip](https://github.com/user-attachments/files/18149390/20241001082802_BloodHound.zip)
- Read the …
=> Fix abuse info around read LAPS password narrative

README.md, dockerfiles/bloodhound.Dockerfile, tools/docker-compose/api.Dockerfile
https://specterops.atlassian.net/browse/BED-5259
https://github.com/SpecterOps/BloodHound/actions/runs/12675096237/job/35325322552
Build error on publish:
[linux/amd64 hound-builder  2/14] WORKDIR /tmp/sharphound
ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code <long dockerfile url>: 403 Forbidden
This looks to be an issue of the Dockerfile looking to the old BloodHoundAD org for Sharphound and Azurehound releases, while they now exist in SpecterOps org.
- Added the …
=> bloodhound.Dockerfile needs to point to SpecterOps org to find *hound releases

cmd/api/src/queries/graph.go, cmd/api/src/queries/graph_test.go, packages/go/cypher/frontend/context.go, packages/go/cypher/frontend/error.go, packages/go/cypher/frontend/filter.go, packages/go/cypher/frontend/pattern.go, packages/go/cypher/frontend/query.go
Add the ability to have "helper" shortcuts that allow a user to specify ALL_ATTACK_PATHS (or by AZ/AD). 
This PR addresses: https://specterops.atlassian.net/browse/BED-4907
curl 'http://bhe.localhost/api/v2/graphs/cypher' --compressed -X POST \
-H "Authorization: Bearer *************" \
-H 'Content-Type: application/json' \
--data-raw '{"query":"MATCH p=shortestPath((n)-[:ALL_ATTACK_PATHS*1..]->(m:Computer))\nWHERE m.unconstraineddelegation = true AND n<>m\nRETURN p\nLIMIT 1000"}' | jq
should return a list of all Attack Edge Types
- Associated an issue: This PR addresses: https://specterops.atlassian.net/browse/BED-4907 …
=> Kpom/bed 4907/cypher shortcut helpers

cmd/api/src/api/static/assets.go
Include all files in the static assets `embed.FS` for the UI instead of excluding files starting with `.` or `_`.
This PR addresses: https://specterops.atlassian.net/browse/BED-5259
Some JS files starting with `_` were being dropped from the static assets in the built binary.
=> fix: include all asset files in static assets embed.FS

cmd/api/src/migrations/graph.go, cmd/api/src/migrations/manifest.go, packages/go/dawgs/drivers/pg/pg.go
Minor changes to the ordering of graph schema assertions as well as graph schema migration checking.
Graph assertions in driver spinup for the pg dawgs driver are causing deadlocks during HA hand-off in production. While these deadlocks quickly resolve, they’re thrashing for no reason. The solution proposed is to change, slightly, how graph migration works.
First is to remove the assertion of graph schema from the `dawgs` driver init. Next, instead of checking only for bespoke migrations for versions listed in the graph migration manifest, the version check now references the application version as the latest available migration.
Stepwise graph migrations still function as expected with one exception tacked on the end. After assertions are made, which in the case of an empty DB would end …
=> BED-5288 - Graph Assertion Ordering and Versioned Migration Checks

go.work
A potential fix for
```
go: downloading go1.23 (linux/amd64)
go: download go1.23 for linux/amd64: toolchain not available
```
When building bh-dev.
Building of development version on my machine fails with toolchain not available. This changes to go1.23.0 which is enough for me to get it over the line. 
This probably isn't the correct fix for something environmental or user error, but even as PR is closed it might save someone some time when searching issues for the error. Also pinning to .0 is probably bad.
Intent is to raise this and close it as invalid, but at least the information can be found.
I tested that build then completed only.
- Chore
- Read the …
=> Update go.work for go version

packages/javascript/bh-shared-ui/src/commonSearches.tsx
PostgreSQL does not allow type inference from strings to booleans. Updating these saved queries to directly compare to boolean variables for expected behavior.
This PR addresses: BED-5304
Validated locally.
=> BED-5304 Fix pre-saved queries with coalesce for proper type-checking

.actrc, .github/actions/build-container-image/action.yml, .github/actions/container-image-metadata/action.yml, .github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/reusable.build-container-image.yml, .github/workflows/reusable.docker-content-trust.yml, .gitignore, dockerfiles/bloodhound.Dockerfile
This PR introduces a comprehensive container image build and publishing pipeline using GitHub Actions.
- Multi-architecture container builds (linux/amd64, linux/arm64)
- Build caching optimization for faster builds
- Container image signing using Docker Content Trust
- Software Bill of Materials (SBOM) generation
- Image provenance for supply chain security
- Local testing support via act
- CI: Runs on PRs to validate container builds
- CD: Builds, publishes and signs images on merges to main/develop and tags
- Reusable composite actions for container builds and signing
- Docker Content Trust for image signing
- SBOM generation for dependency tracking
- Image provenance for build verification
- Privileged container support for multi-arch builds
The pipeline publishes images to both …
=> feature: GitHub Action reusable workflow

packages/go/dawgs/cardinality/hyperloglog32.go, packages/go/dawgs/cardinality/hyperloglog64.go, packages/go/dawgs/cardinality/roaring32.go, packages/go/dawgs/cardinality/roaring64.go
Some minor additions that make interfacing with the generic cardinality interface type `Provider` easier.
This added a bunch of indirection when using the base `Provider` interface type.
=> BED 5330 - Cardinality Chores

local-harnesses/build.config.json.template, local-harnesses/integration.config.json.template, packages/go/dawgs/graph/types.go
A union method to the threadsafekindbitmap is added for use upstream.
This PR addresses: BED-5339
This method will be used in concurrent process for safe reading and writing of kind maps.
The new method was used upstream and analysis was run on a test dataset to ensure that there isn't a material change in performance.
=> chore: introduce Or method to threadsafekindbitmap

packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx, packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
The nav uses css hover state to expand and collapse instead of state and js.
This PR addresses: BED-4810
This pursuit is largely personal as I often navigate pages using the vimium extension. "Clicking" a nav item with vimium would leave the nav open until I used my mouse to enter and exit the nav bar which contradicts the intent of keyboard navigation.
The work cleans the component up a little though.
Tests were updated and the behavior works as desired with the vimium extension.
- …
=> chore: expand collapse nav with tw hover and grouping

packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
The collapsed nav will now show the whole version number and wrap to next line if it exceeds space. When nav is expanded it will be all in one line.
This PR addresses: [BP-1303](https://specterops.atlassian.net/browse/BP-1303)
Manually
[BP-1303]: https://specterops.atlassian.net/browse/BP-1303?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> BP-1303: Replace truncated version with wrapped version number when nav collapsed

packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
Reduced the height at which nav starts scrolling so it doesn't show scroll on full height of smaller laptops.
This PR addresses: [BP-1302](https://specterops.atlassian.net/browse/BP-1302)
Manually in Edge and Chrome.
https://github.com/user-attachments/assets/2cec9f8b-75f8-4970-834f-df21da641af3
=> BP-1302: Reduced the height at which nav scroll activates

packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx, packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
This hides the version number to only show it when nav is expanded
This PR addresses suggestion and comments from [BED-5353](https://specterops.atlassian.net/browse/BED-5353)
Manually and updated tests
[BED-5353]: …
=> BED-5353A: Hide version number when nav collapsed

cmd/ui/src/components/MainNav/MainNavData.tsx, packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx, packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx, packages/javascript/bh-shared-ui/src/components/Navigation/types.ts
Added back the data-testid attributes to the nav bar items to ensure we don't break existing functionality that depends on it.
This PR addresses: [BED-5369](https://specterops.atlassian.net/browse/BED-5369)
Manually and updated FE tests.
[BED-5369]: https://specterops.atlassian.net/browse/BED-5369?atlOrigin=eyJpIjoiNWRkNTl …
=> BED-5369:  Added back data-testid attributes 

cmd/api/src/bootstrap/server.go, cmd/api/src/config/config.go, cmd/api/src/config/default.go, cmd/api/src/services/entrypoint.go, docker-compose.dev.yml, examples/docker-compose/docker-compose.yml
Adds new environment variable to allow recreating the default admin user
This PR addresses: BED-5377
This supports an upstream need, but also means we'll have a supported way for users to reset their admin credentials if they lose access to their account without having to reset the entire database.
Worked through some scenarios locally with a dataset, seems to handle cases where the admin doesn't yet exist, where it already exists, and won't run by default, only if the environment variable gets intentionally set to true …
=> BED-5377: Enable recreating the default admin user with environment variable

packages/go/analysis/azure/tenant.go, packages/go/analysis/impact/id_aggregator.go, packages/go/dawgs/ops/traversal.go
Several of our Measure logs were incorrectly migrated to slog format during our switch to slog
This PR addresses: BED-5410
Several of our Measure logs were incorrectly migrated to slog format during our switch to slog
All existing tests complete and the project builds, there were no logical changes
=> BED-5410: Fix invalid slog parameters in measure logs

.env.example, .github/config/integration.config.json, cmd/api/src/config/default.go, docker-compose.dev.yml, dockerfiles/configs/bloodhound.config.json, examples/docker-compose/.env.example, examples/docker-compose/bloodhound.config.json, examples/docker-compose/docker-compose.yml, examples/helm/values.yaml, local-harnesses/build.config.json.template, local-harnesses/integration.config.json.template
When preparing BHE defaults, we unintentionally turned on pg by default in BHCE. This change reverts the global default, while ensuring the default configuration files also specify neo4j for now to assist in any future migrations.
This PR addresses: BED-5419
Make sure BHCE continues to default to neo4j as the graph database
No functional changes
=> BED-5419: Revert mistaken change to make pg the global default driver

cmd/api/src/database/migration/migrations/v7.1.0.sql
- Adds a new disabled, non-user updatable feature flag `back_button_support` to the `feature_flags` table
This PR addresses: BED-5438
This feature flag enables developers to begin building out support for BED-4757 (also #781) without impacting end users. 
No tests have been added or modified. This change contains only an updated migration file to update records in the postgres database.
No screenshots. …
=> feat: Adds new feature flag `back_button_support`

packages/cue/bh/ad/ad.cue, packages/go/graphschema/ad/ad.go, packages/go/graphschema/azure/azure.go, packages/go/graphschema/common/common.go, packages/javascript/bh-shared-ui/src/graphSchema.ts
Remove the `highvalue` property from the BH schema. This is a holdover from Legacy and is not utilized by BHCE.
This PR addresses: BED-5262
Validated locally.
Note the following screenshot no longer autocompletes the "highvalue" property
=> BED-5262: Remove highvalue from schema

cmd/api/src/api/v2/auth/login.go, packages/go/graphschema/ad/ad.go, packages/go/graphschema/azure/azure.go, packages/go/graphschema/common/common.go
This PR fixes an issue where users were unable to login when their username/email address contained leading or trailing spaces. Added trimming of whitespace from username inputs during login.
This PR addresses: BED-5434
- Manually tested with test accounts containing leading/trailing spaces
- Confirmed original functionality works for properly formatted emails
=> BED-5434: Fix login with leading/trailing spaces in username

cmd/api/src/test/integration/harnesses.go, packages/go/analysis/ad/ntlm.go
This change correctly checks the `IsDC` property for a `true` value, rather than checking for a `domainsid`
This PR addresses: BED-5026
Fixes a bug in the harness and LDAP(S) edge creation
Integration tests are passing
- …
=> BED-5026 Fix LDAP(S) IsDC Usage From String Comparison To Bool Comparison

cmd/api/src/analysis/ad/adcs_integration_test.go, cmd/api/src/analysis/post_integration_test.go, packages/go/analysis/ad/ad.go, packages/go/analysis/ad/adcs.go, packages/go/analysis/ad/adcscache.go, packages/go/analysis/ad/esc1.go, packages/go/analysis/ad/esc10.go, packages/go/analysis/ad/esc13.go, packages/go/analysis/ad/esc3.go, packages/go/analysis/ad/esc4.go, packages/go/analysis/ad/esc6.go, packages/go/analysis/ad/esc9.go, packages/go/analysis/ad/esc_shared.go, packages/go/analysis/ad/post.go, packages/go/analysis/ad/queries.go
Improve group shortcutting (cross-product node set) logic and optimize ADCS post-processing.
This PR addresses: BED-5473, BED-5474
BED-5473:
Our special group shortcutting (cross-product node set) logic, that ensures we don’t check membership of Authenticated Users and Everyone (special groups) but simply assume all nodes as members, only considers the Authenticated Users and Everyone groups of the current domain. That means the shortcutting does not work when the target node is of a different forest. This change removes the filtering based on the domain SID.
BED-5474:
An enterprise CA can chain up to multiple domains. In that case, we calculate the the same ADCS edges for a given enterprise CA once per domain. With this change, we now iterate enterprise CAs, determine what domains they …
=> Improve group shortcutting and ADCS logic

docs/hc/en-us/reference/eula/accept-eula.mdx, packages/go/openapi/doc/openapi.json, packages/go/openapi/src/paths/eula.accept-eula.yaml
NO FUNCTIONAL IMPACT.
Updating API docs to reflect correct call.
This PR addresses: BED-5485
Doc for `accept-eula` was stating `get` but shud be `put`
Checked the docs locally. …
=> chore: Updating OpenAPI doc to update `get` to `put`

tools/docker-compose/neo4j.Dockerfile
This PR addresses: [BED-4145](https://specterops.atlassian.net/browse/BED-4145)
The prior image tag contains severe vulnerability risks.
Starting application locally and performing basic functionality.
Update Neo4j version to newest image tag to address vulnerability issues found on Docker Hub.
- [x ] I have met the contributing prerequisites
- All new and existing tests …
=> chore(docker): Upgrade Neo4j base image to version 5.26.1

tools/docker-compose/neo4j.Dockerfile
This reverts commit 4790b740d9393023bf3363c31ac98554f29c01e1. Automated tests began failing after PR #1131 was merged. It appears to be caused by calling a procedure (`db.indexes`) that is deprecated in neo4j 5+.
* This is related to the original ticket of BED-4145.
* Fix broken tests so other PRs can be merged.
- …
=> Revert "chore(docker): Upgrade Neo4j base image to version 5.26.1 (#1131)"

packages/go/analysis/ad/ntlm.go, packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/CoerceAndRelayNTLMToADCS.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/CoerceAndRelayNTLMToLDAP.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/CoerceAndRelayNTLMToLDAPS.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/CoerceAndRelayNTLMToSMB.tsx
Correct a null pointer issue in NTLM post, fixes the edge panels
- All new and existing tests …
=> Small fixes in NTLM

packages/javascript/bh-shared-ui/src/commonSearches.ts
Removes a duplicated NTLM saved query
This PR addresses: BED-5526
We had removed event log based NTLM edge processing, this query was left in after the removal but ends up being a duplicate of the `All coerce and NTLM relay edges` query
`All NTLM Session-based Relay Edges` was removed, which is the expected behavior
=> BED-5526 removed artifact of event log based NTLM saved query

cmd/ui/src/views/GroupManagement/GroupManagement.tsx, packages/javascript/bh-shared-ui/src/constants.ts
Two different constants are created for disambiguation purposes: `TIER_ZERO_LABEL` and `HIGH_VALUE_LABEL`.
This PR addresses: BED-5524
There was a constant in the BHE repository that is also called `TIER_ZERO_LABEL` which has a different string value assigned to it. The constant name update helps with disambiguation and makes it clear that these constants do not have the same value.
The bug is upstream. The project builds as the updated constant name is updated where it was used. …
=> fix: update t0 label const name to disambiguate from high value

cmd/api/src/database/migration/migrations/v7.1.0.sql, packages/go/analysis/ad/ntlm.go, packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/General.tsx
Change NTLMToSMB's General copy to reference `Composition` instead of `Relay Targets`
Default NTLM feature flag to disabled
This PR addresses: BED-5525
With a fresh instance of BHE I ingested data and ensured no NTLM edges were created.
I then enabled the NTLM feature flag and re-ingested the same zip and confirmed that the edges were created
=> BED-5525 Set NTLM Feature Flag Default To Disabled & Update NTLMSMB General Copy

packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/WindowsAbuse.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/WindowsAbuse.tsx
SMB steps were accidentally added to the LDAP, LDAPS, and ADCS WindowsAbuse copy
This simply removes the step
This PR addresses: BED-5484
=> BED-5484 Removed extra step from NTLM [LDAP, LDAPS, ADCS] WindowsAbuse copy

.github/workflows/cd.yml
This PR fixes the Docker image tagging in the CD workflow. The change modifies the `image_flavor` parameter in the GitHub Actions workflow to set the "latest" tag for Docker images correctly.
The change updates the syntax from:
```yaml
image_flavor: ${{ (github.ref_name == 'main' || contains(github.ref_name, '-rc')) && 'latest=false' }}
```
To:
```yaml
image_flavor: latest=${{ (github.ref_name == 'main' || contains(github.ref_name, '-rc')) == false }}
```
This ensures the "latest" tag is applied correctly based on the branch conditions.
This PR addresses [BED-5539](https://specterops.atlassian.net/browse/BED-5539)
The current implementation of Docker image tagging in the CD workflow does not correctly apply the "latest" tag. This change fixes the syntax to ensure images are correctly …
=> fix(BED-5539): Update image flavor tag generation logic in workflow

docs/mint.json
As part of the Mintlify doc revamp, this PR disables the "Try it" button on the API docs, per Kate's request. 
This PR addresses: [#1085](https://github.com/SpecterOps/BloodHound/issues/1085)
Tested locally with Mintlify 
$$ Types of changes
- Chore
- Docs
I have read the CLA Document and I hereby sign the CLA
=> Disable the try it button for API docs

.github/actions/build-container-image/action.yml, .github/workflows/reusable.build-container-image.yml
Ignore DockerHub logins for PRs from forks as they do not have access to the required secrets.
Using this PR instead of #1186 so we can test the changes since this isn't coming from a fork.
BED-5547
Re-enable PRs from forked repos to be able to be merged.
This hasn't actually been fully tested, as there is a bit of a chicken/egg problem. We can't successfully build due to the restrictions, but building is the only way we can test it. 
- Added/updated tests to cover …
=> BED-5547 Don't try to login to dockerhub for PRs from forks

.github/workflows/build-ui.yml, .github/workflows/ci.yml, .github/workflows/run-tests.yml, .github/workflows/static-code-analysis.yml, .github/workflows/vuln-scan.yml
Skip CI when there are only changes to product or process documentation.
It is unnecessary and time-consuming to build & test changesets that do not directly affect the product. This PR excludes certain checks from running when there are only changes to product or process documentation.
https://specterops.atlassian.net/browse/BED-5561
n/a
=> ci(docs,rfc): skip ci when there are only changes to documentation or rfcs

cmd/api/src/database/migration/migrations/v7.2.0.sql
- Allows users to enable or disable the `back_button_support` feature flag via the Early Access Features page.
This PR addresses: https://specterops.atlassian.net/browse/BED-5557
No tests have been added or updated.
=> BED-5557: Allow users to enable or disable `back_button_support` feature

local-harnesses/build.config.json.template
Adding email field to support email login in local
This PR addresses: [BED-5565]
1. I manually logged in using the email/ password from the template
2. I ran HoundStrike and the existing tests passed. using email/ password
[BED-5565]: https://specterops.atlassian.net/browse/BED-5565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Adding email to the buid.config.json.config to support email login

cmd/api/src/analysis/ad/ntlm_integration_test.go, cmd/api/src/test/integration/harnesses.go, packages/go/analysis/ad/ntlm.go
This PR prevents computers from self relaying in post processing for NTLM attack paths pertaining to SMB, LDAP, and LDAPS.
This PR addresses: BED-5544
Test harnesses were setup with self relay scenarios and integration tests were written around those to ensure no edges were being created.
Existing integration tests pass with the expected number of edges being created, ensuring that the new logic only affects scenarios where a self relay is possible
- Added/updated …
=> BED-5544 remove self relay from SMB and LDAP(S)

cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.tsx, cmd/ui/src/views/Explore/ExploreSearch/switches/usePathfindingSearchSwitch.ts, packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingSearch.test.tsx, packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingSearch.ts
With our new deep linking changes to the Explore page, clicking the pathfinding swap button and then navigating back through browser history shows two history locations have been created, and the intermediary state has the source and destination nodes set to the same value.
This fix updates our pathfinding swap process to make sure all URL changes occur in one step.
This PR addresses: [BED-5581](https://specterops.atlassian.net/browse/BED-5581)
This intermediary state where both inputs are the same is unhelpful to users and will always create an invalid pathfinding result.
Added an additional unit test to cover the new function. …
=> BED-5581: Remove extra browser history entries from pathfinding swap

cmd/ui/src/components/SigmaChart.tsx
Updates our initial sigma settings to use the correct color for node labels based on the current dark mode setting.
This PR addresses: [BED-4948](https://specterops.atlassian.net/browse/BED-4948)
Currently, the node labels on initial load in dark mode (or after toggling dark mode on/off) are the incorrect color and can't be read against the application's background.
Manual testing …
=> BED-4948: Set initial node label color based on dark mode setting

cmd/api/src/api/v2/auth/auth.go, cmd/api/src/api/v2/auth/auth_test.go
It was found during a pen test that users could delete themselves from the API.
This became a particular problem when it was found that admins could delete themselves, which disallowed them from managing the BH instance
This PR addresses: BED-5564
I sent a DELETE request to /api/v2/bloodhound-users/c9051693-59ef-479a-ba68-2e1143a333e9 and verified that I could not delete myself
=> BED-5564: Deny Users From Self-Deleting Via The API

packages/javascript/bh-shared-ui/src/components/HelpTexts/OwnsRaw/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/OwnsRaw/OwnsRaw.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/OwnsRaw/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwnerRaw/General.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwnerRaw/References.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwnerRaw/WriteOwnerRaw.tsx, packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
Adding help texts for OwnsRaw and WriteOwnerRaw edges
This PR addresses: https://github.com/SpecterOps/BloodHound/issues/1267
Tested using latest `main` branch of BHCE.
=> Added help texts for OwnsRaw and WriteOwnerRaw edges

cmd/api/src/api/v2/edge.go
It was found in larger environments that we were returning 400 bad request errors when attempting to view edge composition.
This was because we were only parsing strings with 32 bit integer support, this simply bumps us up to 64 bit integers to support those larger environments
This PR addresses: BED-5638
- Code …
=> BED-5638: GetEdgeComposition Now Parses Node IDs Into 64bit Integers

cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoPane.tsx
Small cleanup of code for edge info panel. There was a conditional block that wasn't doing anything as well as a missing SelectedEdge type. Figured I would add it in as sister PR as it was relevant for parity between bhce and bhe.
This ticket is complementary to keep parity with [BED-5505](https://specterops.atlassian.net/browse/BED-5505)
Manually and existing tests passing …
=> BED-5505: Entity/Edge Panels Deep linking cleanup for parity with BHE

packages/go/ein/ad.go
Fixes HTTPEnrollmentEndpoints ingestion on EnterpriseCA nodes
This PR addresses: BED-5669
Ran collection locally, viewed an EnterpriseCA node, and confirmed that the url existed as a property in the Entity Panel
Screenshot of the fix working is attached to the ticket's comments
=> BED-5669: HTTPEnrollmentEndpoints will now be properly ingested

rfc/bh-rfc-0.md, rfc/bh-rfc-1.md
Draft initial RFC documents for creating RFCs and outlining the BloodHound release process.
A well-structured, clear RFC process ensures that BloodHound's development and policy changes are documented in a single source of truth. By following the guidelines outlined in `bh-rfc-0` we make it easier for contributors to understand, review, and implement changes and increase transparency for consumers.
n/a
Documentation
=> doc(bh-rfc-0,bh-rfc-1): create initial draft rfcs for rfc and release processes

cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.test.tsx, cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.test.tsx, packages/javascript/bh-shared-ui/src/mocks/handlers/tierHandlers.ts, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/CypherSearch.test.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.test.tsx
Added api mocks to remove warnings in output when running tests
This PR addresses: [BED-5648](https://specterops.atlassian.net/browse/BED-5648)
Manually and visually seeing no warning in output from running tests
[BED-5648]: https://specterops.atlassian.net/browse/BED-5648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
=> BED-5648:  Export graph data test warning cleanup

packages/go/analysis/ad/post.go
Coercion edges were not added to the PostProcessedRelationships array so were not being removed at start of post appropriately
This PR addresses: https://specterops.atlassian.net/browse/BED-5700
=> fix: coerce edges not added to post processed relationships properly

packages/javascript/bh-shared-ui/src/components/VirtualizedNodeList.tsx
This PR adds a conditional styling override to VirtualizedNodeList. If there are fewer than 2 nodes, overflow will not be applied.
This PR addresses: BED-5576
Our VirtualizedNodeList components will display the scrollbar even if single node is rendered. This components uses [React Window's](https://github.com/bvaughn/react-window) FixedSizeList component, which [unconditionally applies](https://github.com/bvaughn/react-window/blob/72db696dd8ebb7f0f287c78d037ff68ba9534183/src/createListComponent.js#L373) an 'auto' overflow, causing the scrollbar to always be displayed.
Manually tested using demo data set.
Before (notice `DC01.PHANTOM.CORP` is slightly cut off at bottom): 
After: …
=> BED-5576: Unset overflow when FixedSizeList has fewer than 2 nodes

packages/javascript/bh-shared-ui/src/hooks/useExploreParams/useExploreParams.tsx, packages/javascript/bh-shared-ui/src/utils/searchParams/searchParams.ts
Corrects the return type of `setParamsFactory` from `(updatedParams: T) => void` to `(updatedParams: Partial<T>) => void` as the returned function is able to accept a partial object of query params.
This PR addresses: BED-5450
This change allows us to clean up a linting error in the `useExploreParams` hook.
All existing unit tests pass.
=> Update the return type definiton for `setParamsFactory`

packages/go/stbernard/main.go
When trying to use the St Bernard package, I needed to set the Log Level to DEBUG so I could troubleshoot an issue I was having when trying to run the analysis. It was discovered that a change needed to be made inside of the St Bernard package to set the log level correctly. This ticket reflects said change.
This PR addresses: https://specterops.atlassian.net/browse/BED-5714
Fixes the ability to set the log level when running the St Bernard Package
Manually tested running `SB_LOG_LEVEL=debug just analyze`
- Open API …
=> BED-5714 Small Bug Fix in St Bernard Package

cmd/api/src/daemons/datapipe/convertors.go, cmd/api/src/test/fixtures/fixtures/expected_ingest.go, cmd/api/src/test/fixtures/fixtures/v6/all/domains.json, packages/go/ein/incoming_models.go
The original PR for GPOLocalGroup (https://github.com/SpecterOps/BloodHound/pull/1147) did not include the domain nodes which also have the same information. This PR corrects that.
This PR addresses: https://specterops.atlassian.net/browse/BED-5384
Tested using lab data
=> Add GPOLocalGroup Ingestion to Domain Objects

packages/javascript/bh-shared-ui/src/utils/queries/index.ts, packages/javascript/bh-shared-ui/src/utils/queries/queries.test.ts, packages/javascript/bh-shared-ui/src/utils/queries/queries.ts
Moves some of the common shared react-query utils to the shared-ui to be shared with other query hooks
This PR addresses: BED-5504
We keep recreating these functions so this PR moves them to the shared-ui so we only have one version.
Moved existing unit tests
=> BED-5504: Move common query utils to shared-ui

dockerfiles/bloodhound.Dockerfile, tools/docker-compose/api.Dockerfile
`api/v2/collectors/*` endpoints won't find the embedded files by their new names, must be named '<collectortype>-<version>.zip(.sha256)', all lowercase.
This PR addresses: [BED-4714]
just bh-dev
docker build -f dockerfiles/bloodhound.Dockerfile .
[BED-4714]: https://specterops.atlassian.net/browse/BED-4714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> [BED-4714] Correct filename embedded into image

cmd/api/src/migrations/manifest.go
This is a simple migration to remove the admin_rights_count property from User nodes
This PR addresses: BED-4886
Update the migration data node to version 7.2.0
SELECT * FROM node WHERE kind_ids @> ARRAY[1]
Find a User node in the `node` table (kind_id 23)
Take node of the ID and properties of the node
Add `"adminrightscount": 1` to the properties of the User node
kind_ids @> properties ? 'adminrightscount'
Ensure that this query works, and take a note of the node’s ID that you modified
Run the application and ensure you see in the logs:
`Migration to remove admin_rights_count property from user nodes","measurement_id":1`
Re-run this query
kind_ids @> properties ? 'adminrightscount'
And ensure that the node is no longer returned
Query for the node you changed and ensure the properties …
=> fix(migrations): Added migration to remove admin_rights_count property from User nodes

justfile
Removes the yarn and go testing steps from the `just prepare-for-codereview` script.
This PR addresses: [BED-5730]
There was recently a discussion in the engineering-council channel to move tests to a CI check. So tests are being removed from the prc just script as to not be redundant
The `just pfc` script was ran again to ensure that it still works and does not run the tests. 
- All new and existing tests …
=> chore: remove tests from just prepare-for-codereview

cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
This change conditions the relationship search to only panels that have a member count less then the limit (1000). It addresses the bug that did not allow to open panels when count was over the limit.
This PR addresses: [BED-5454](https://specterops.atlassian.net/browse/BED-5454)
Manually and all existing tests passed.
[BED-5454]: https://specterops.atlassian.net/browse/BED-5454?atlOrigin=ey …
=> BED-5764: Relationship search / Graph rendering only happening if member count under query limit

cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.test.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoHeader.test.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoHeader.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoPane.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeObjectInformation.test.tsx, cmd/ui/src/views/Explore/EdgeInfo/EdgeObjectInformation.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoContent.test.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoHeader.test.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoHeader.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityInfoPanel.tsx, cmd/ui/src/views/Explore/EntityInfo/EntityObjectInformation.tsx, packages/javascript/bh-shared-ui/src/providers/ObjectInfoPanelProvider/ObjectInfoPanelContext.ts, packages/javascript/bh-shared-ui/src/providers/ObjectInfoPanelProvider/ObjectInfoPanelContextProvider.tsx, packages/javascript/bh-shared-ui/src/providers/ObjectInfoPanelProvider/index.ts
This fixed the collapse all button and now when clicked collapses all open panels in Edge or Entity Panels
This PR addresses ticket: [BED-5732](https://specterops.atlassian.net/browse/BED-5732)
Manually, added new tests and existing tests passed
https://github.com/user-attachments/assets/dbdbd650-5a09-47fc-afde-334fb12058d1
[BED-5732]: …
=> BED-5732: Fix Collapse All button in Entity/Edge panels

docs/docs.json
As part of the Mintlify doc revamp, this PR makes a config change to properly display API methods and paths in the reference docs. 
Motivation and Context
- This PR addresses: [#1085](https://github.com/SpecterOps/BloodHound/issues/1085)
Testing
- Tested locally with Mintlify for broken links and broken site
Types of changes
- Chore
- Docs
I have read the CLA Document and I hereby sign the CLA
=> Fix missing API endpoints

cmd/ui/src/views/DisabledUser.tsx, cmd/ui/src/views/NotFound.tsx
Update NotFound page to clearly state 404 status and to redirect to login if unauthenticated.
Resolves BED-5326
Manually tested. Visited bad routes while authenticated and again while unauthenticated.
ex. http://bloodhound.localhost/ui/not-a-route
Before
After
=> feat(ui): enhance not-found page

packages/go/stbernard/workspace/golang/generate.go, packages/go/stbernard/workspace/golang/mod.go
The golang code generation step contains a goroutine amplification trap that clobbers the snot out of my local machine every time I run generation steps. This causes skips in my Doom playthrough videos which requires me to then break flow and rewind them.
Resolves BED-5810
This is just a little nicer to developer machines by limiting concurrency and consuming more IO operations. The changeset also addresses the nested goroutine amplification trap.
Code generation looks good!
- Code …
=> BED-5810 - Make stbernard Less Aggressive during Golang Code Generation

cmd/api/src/queries/graph.go
Changing the log level from Info to debug when fetching the count of the entity
Fixes BED-5768
Changing the log level from Info to debug when fetching the count of the entity
Running queries at `Info` level generates a lot of logs which adds resource constraints on the system.
Resolves BED-5768
Verified locally
- Breaking change (fix or feature that would cause …
=> chore: set debug log level on entity count query

cmd/api/src/database/assetgrouptags_test.go, cmd/api/src/database/migration/migrations/v7.4.0.sql
Add default cypher selector migrations for new Tiering engine
Resolves BED-5548
Resolves #615
The new tiering engine doesn't store selectors in the same tables
Manually ran the relevant SQL
=> BED-5548: chore: migrate group management selectors

cmd/api/src/api/v2/analysisrequest_integration_test.go, cmd/api/src/api/v2/app_config_integration_test.go, cmd/api/src/api/v2/audit_integration_test.go, cmd/api/src/api/v2/auth/auth_integration_test.go, cmd/api/src/api/v2/azure_integration_test.go, cmd/api/src/api/v2/cypherquery_integration_test.go, cmd/api/src/api/v2/datapipe_integration_test.go, cmd/api/src/api/v2/file_uploads_integration_test.go, cmd/api/src/auth/role_test.go
Reverts SpecterOps/BloodHound#1289
We need these tests a bit longer. There was a miss in intent that led to premature removal of these tests. Bringing them back for now
=> Revert "BHE-5639 Integration Test Removal (preparation for replacement)"

cmd/api/src/api/v2/edge_test.go, cmd/api/src/migrations/migrations_integration_test.go
I added tests for the handler `GetEdgeRelayTargets` and changed the test `TestVersion_730_Migration` to be an integration test.
Resolves [BED-5816](https://specterops.atlassian.net/browse/BED-5816?atlOrigin=eyJpIjoiZTQyZjZmYjQ5M2U3NGJhOTk3NjI1MzJlNDg4ZTAwMTQiLCJwIjoiaiJ9)
Add code coverage for `GetEdgeRelayTargets` and fix the test `TestVersion_730_Migration` being miscategorized as a unit test when it should be an integration test. 
Unit tests and integration tests have been run locally. …
=> BED-5816 (chore) adding tests for GetEdgeRelayTargets & changing TestVersion_730_Migration to integration test

docs/docs.json, docs/resources/edges/abusetgtdelegation.mdx, docs/resources/edges/crossforesttrust.mdx, docs/resources/edges/sameforesttrust.mdx
This PR publishes the edge pages that got missed in the Zendesk doc cutover. 
Motivation and Context
- This PR addresses: [#1085](https://github.com/SpecterOps/BloodHound/issues/1085)
Testing
- Tested locally with Mintlify for broken links and broken site
Types of changes
- Chore
- Docs
I have read the CLA Document and I hereby sign the CLA
=> Add missing edge pages

cmd/api/src/api/v2/assetgrouptags.go, cmd/api/src/model/filter.go, cmd/api/src/model/filter_internal_test.go, cmd/api/src/model/saved_queries.go
BED-5737 was flawed in its assumptions and this work will break several endpoints due to the way filtering works. Reverting for now and putting ticket back into queue
Reverts SpecterOps/BloodHound#1418
=> Revert "Bed 5737"

cmd/api/src/test/fixtures/fixtures/expected_ingest.go
Also commented out new test assertions that are failing, will need to work with Jonas to troubleshoot.
This should allow us to run existing tests while we work on the overhaul.
Closes BED-5639
=> fix: moved v6 only ingest assertions to the v6 specific assertions

packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.test.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.test.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/index.tsx, packages/javascript/js-client-library/src/client.ts
closes BED-5855
This makes the sorting button for the objects list reset the list items and make a new API request since this endpoint is paginated.
Resolves BED-5855
Right now the sorting button only changes the icon display for the list. This change will make the sorting functional.
Checked the network requests being sent out on clicking the sort button. …
=> fix: tier details object sort order

justfile, packages/go/stbernard/command/command.go, packages/go/stbernard/command/generate/generate.go, packages/go/stbernard/command/goimports/goimports.go, packages/go/stbernard/workspace/golang/goimports.go
Fixes: BED-5760
The PR addresses Golang formatting issues when generating schemas files at runtime
Fixes: BED-5760
- Run `just generate` command and observe the command does not introduces no file changes
- …
=> chore: fix file drifts in schemagen packages

cmd/api/src/database/migration/migrations/v7.4.0.sql
This PR sets the `back_button_support` feature flag to be enabled and makes it not user updatable.
Partially implements BED-5620
This will effectively make the deep linking feature GA. While there is more work to complete BED-5620, this is all that is required to go GA. We have a fast follow up PR that will remove all feature flag code flows and updates tests to expect the deep linking state management
Validated against my local DB which has run the latest migration
- Code comments …
=> BED-5620: GA deep linking feature flag

cmd/ui/src/views/Explore/EntityInfo/EntityObjectInformation.tsx, packages/javascript/bh-shared-ui/src/views/Explore/BasicObjectInfoFields.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/EntityObjectInformation.tsx
Adds node type to Entity Panel
Shows the node type on the Entity Panel.
Resolves BED-5052
Manually tested by clicking on a node and seeing the new info.
Before:
After:
=> feat(Entity Panel): add node type

packages/javascript/bh-shared-ui/src/components/AssetGroupManagement/AssetGroupSelectorObjectSelect.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Cypher/Cypher.test.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Cypher/Cypher.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/BasicInfo.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.test.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.tsx
An equality check is updated to account for setting a default value for the selectorId path param within the selector form component.
Updates the run buttons for seed selection to display "Update Sample Results"
Resolves BED-5894
Unit test is added for creating selector
- 
=> fix: selectorId empty check since it defaults to empty string now

packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.tsx
Fixed text overflow at 1080p.
Resolves [BED-5893](https://specterops.atlassian.net/browse/BED-5893)
Manually tested
[BED-5893]: https://specterops.atlassian.net/browse/BED-5893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: BED-5893

packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/EntityInfoPanel.tsx, packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/SelectorList.tsx
Fixes object info panel width issue by setting max width to match entity panels throughout the app.
Resolves [BED-5898](https://specterops.atlassian.net/browse/BED-5898)
Fixes width issue.
Manually
[BED-5898]: https://specterops.atlassian.net/browse/BED-5898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix:BED-5898 fixed width issue

cmd/api/src/database/migration/migrations/v7.4.0.sql
This PR sets the `back_button_support` feature flag to be enabled and makes it not user updatable.
Fixes an issue with the implementation of BED-5620
A malformed update statement in our v7.4.0 migration file caused the `back_button_support` record in the `feature_flags` table to be only partially updated.
Validated against my local DB which has run the latest migration
=> fix: corrects an invalid update statement in the v7.4.0 migration file

cmd/ui/src/views/Explore/ContextMenu/ContextMenuV2.tsx
This adds a feature flag to prevent options from being available when the tier feature flag is enabled.
Resolves [BED-5910](https://specterops.atlassian.net/browse/BED-5910)
We need to hide certain options from being available when the tier feature flag is enabled.
Tested manually
[BED-5910]: https://specterops.atlassian.net/browse/BED-5910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> feat: BED-5910

dockerfiles/bloodhound.Dockerfile
Upgrade our container building to use Go 1.23.10 in order to address
CVE-2025-22874
CVE-2025-0913
CVE-2025-4673
Resolves: BED-6036 …
=> BED-6036: Update Go Container Build From 1.23.9 to 1.23.10

cmd/api/src/services/graphify/azure_convertors.go
This takes the function defined in BHE used for `KindAZRoleEligibilityScheduleInstance` ingestion, removes the BHE specific code, and allows BHE to create `AZRoleEligible` edges
Resolves BED-6127
I ingested a sample AzureHound dataset and searched for the nodes using
```
MATCH p = (:AZBase)-[:AZRoleEligible]-(:AZBase)
RETURN p
```
=> BED-6127: Added KindAZRoleEligibilityScheduleInstance To The Azure Converters

cmd/ui/src/views/ZoneManagement/InfoHeader.tsx, packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/Details.tsx, packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DynamicDetails.tsx, packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/Save.test.tsx, packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/Save.tsx, packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.tsx, packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/Summary.tsx
Updates the use of the id value returned from the useHighestPrivilegeTagId hook to destructure the ID now that it is returning the loading and error states and not just a primitive value. 
Resolves BED-6189
Some of the routing was broken when this hook was updated. This changeset rectifies the behavior.
- Code comments …
=> fix: update tag id usage for object return value

cmd/api/src/auth/role.go, cmd/api/src/database/migration/migrations/v8.0.0.sql
Brings back app config read for power users.
closes BED-6250
Calling the feature flag endpoint results in a 403 without this permission. This means that conditional rendering in the UI based on feature flags for power users would not function as intended. Power Users will still be limited in changing app config.
- Code …
=> fix: power user app config read

dockerfiles/bloodhound.Dockerfile, tools/docker-compose/api.Dockerfile
Bumps sharphound to latest version
BED-6227 - Prepare for Release v8.0.0
SharpHound v2.7.0 is now released and should be included as our baseline version
Tested that building local dockerfiles works and that the correct version is now included
=> chore: bump sharphound to v2.7.0

cmd/api/src/database/migration/migrations/v8.1.0.sql
Adds a new migration for v8.1.0 that creates the etac feature flag
Resolves BED-6023
The app was started up and we ensured that the feature flag exists in the feature table. the migration incremented to v8.1.0, and the feature flag was not editable via the UI
=> BED-6023 Added eTAC feature flag and Houndstrike tests

dockerfiles/bloodhound.Dockerfile, packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DetailsList.test.tsx, tools/docker-compose/api.Dockerfile
Bumps SharpHound to the Latest Version
Resolves [BED-6302](https://specterops.atlassian.net/browse/BED-6302)
A new patch was released of SharpHound and this change includes this new version. 
This has been tested by building and running locally and ensuring the new version of SharpHound was available.
[BED-6302]: https://specterops.atlassian.net/browse/BED-6302?atlOrigin=eyJ …
=> chore: bump SharpHound Version

cmd/ui/public/img/BHCE_Vertical_RedField.svg, packages/csharp/graphschema/PropertyNames.cs, packages/cue/bh/ad/ad.cue, packages/go/graphschema/ad/ad.go, packages/go/openapi/doc/openapi.json, packages/javascript/bh-shared-ui/src/commonSearchesAGI.ts, packages/javascript/bh-shared-ui/src/commonSearchesAGT.ts, packages/javascript/bh-shared-ui/src/graphSchema.ts
This reverts commit 5dce78f7f8ea34a6c012e67c410d12407ef27b30.
This feature depends on some collector work that will not be completed in time for this release cycle, so we are pulling it out of the staging branch and it will get pulled in during 8.2.0
Removes [BED-6286](https://specterops.atlassian.net/browse/BED-6286)
The pre-built cypher queries added in this PR currently will not return any results since we are not collecting the required properties yet, which could lead to a poor user experience. …
=> Revert "feat: AdminSDHolder Protected - BED-6286 (#1743)"

packages/javascript/bh-shared-ui/src/hooks/usePermissions/usePermissions.tsx
Removes 'permissions' from the query key for the get self call in the usePermissions hook.
Resolves BED-6387
=> fix: get self query key consistency

packages/javascript/bh-shared-ui/src/components/PrebuiltSearchList/PrebuiltSearchList.tsx, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.tsx, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/ConfirmDeleteQueryDialog.tsx, packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/QuerySearchFilter.tsx
In the saved queries flow, there are two places where the user can delete a saved query.  
1. On the top bar next to export.  
2. In the saved queries list within the ellipsis menu
The delete button in the ellipsis is firing off a confirmation modal as expected.  The delete button on the top bar was not.  So, we have added the confirmation modal to the top bar delete button so that there is consistency across both.  
Additionally, the top bar delete button is now correctly set to be disabled for shared queries.  
Resolves BED-6494
Manually tested in local environment.  
All test cases passed.
- …
=> BED-6494 -- Delete Query Confirmation Modal

packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/Details.tsx, packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/SearchBar.tsx
Updates styles for the row with buttons and the search input in PZ details page.
Resolves BED-6496
On small width resolutions the search input element overlaps the create buttons even though not readily apparent. This interferes with clicking the buttons and is confusing.
Manually verified. 
=> fix(agt): search bar overlap create buttons fix

cmd/ui/src/views/Explore/utils.test.ts, cmd/ui/src/views/Explore/utils.ts
Updates our graph data transformation logic to remove duplicate edges before handing them off to graphology.
Resolves BED-6451
Duplicate edges from cypher queries were causing graphology to throw an unhandled exception after a recent refactor to our graph data transformations. 
Added a new test to check that edges are correctly deduped and do not cause an error.
=> BED-6451:  Duplicate edge issue
