- license_check.py
Added a condition to `license_check.py` to keep it from adding extra whitespace
The extra whitespace is being removed by formatting tools and causing extra noise in PRs
Manually generated a license header and verified the header is correct and has no extra EOL whitespace
> chore: Update license check to remove extra whitespace

- cmd/ui/src/components/SigmaChart.tsx
- cmd/ui/src/ducks/graph/utils.ts
- cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx
- cmd/ui/src/views/Explore/ExploreSearchCombobox/ExploreSearchCombobox.tsx
- cmd/ui/src/views/Explore/GraphView.tsx
- cmd/ui/src/views/Explore/InfoStyles/CollapsibleSection.tsx
- cmd/ui/src/views/Explore/InfoStyles/Pane.tsx
- packages/javascript/bh-shared-ui/src/components/InfiniteScrollingTable/InfiniteScrollingTable.tsx
These changes set the panes that float above the canvas where the graph is rendered within a \<Grid\/\> component so that they can resize responsively.
These panes overlapped when the window size is relatively small and it is nice to have them resize so that the UI looks polished. 
https://github.com/SpecterOps/BloodHound/assets/16910931/8e92dfe0-f8ae-4550-b372-023949e8ce09
-   [ ] I have added and/or updated tests to cover my …
> Responsive explore page

- .all-contributorsrc
- CONTRIBUTORS.md
Adding a new user to the `CONTRIBUTORS.md` file.
> chore: add nodauf as a contributor

- docker-compose.testing.yml
- docker-compose.yml
- dockerfiles/bloodhound.Dockerfile
- examples/docker-compose/docker-compose.yml
- tools/docker-compose/api.Dockerfile
- tools/docker-compose/neo4j.Dockerfile
- tools/docker-compose/pgadmin.Dockerfile
- tools/docker-compose/ui.Dockerfile
Update references to container image names to use fully qualified names instead of short names
This is a best practice to remove ambiguity and prevent security issues
Pulled all updated image names to verify they refer to the same container image
-   [ x] Chore (a change that does not modify the application functionality)
> chore: update container image names to be fully qualified

- .all-contributorsrc
- CONTRIBUTORS.md
Add @exploide as a contributor.
They submitted a PR that was merged!
> chore: add exploide as a contributor

- cmd/api/src/test/fixtures/fixtures/expected_ingest.go
- cmd/api/src/test/fixtures/fixtures/v5/ingest/users.json
Adds a test that covers umlauts in display names
Future proofing and testing
Tests pass
> chore: add an additional test harness covering umlauts in display names

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
- Bumps the bundled AzureHound version to v2.0.5
The new version of AzureHound includes misc. bugfixes and logging enhancements.
> chore: bump bundled azurehound version

- cmd/api/src/test/fixtures/fixtures/expected_ingest.go
- cmd/api/src/test/fixtures/fixtures/v5/ingest/computers.json
- cmd/api/src/test/fixtures/fixtures/v6/ingest/computers.json
- packages/go/ein/ad.go
- packages/go/ein/incoming_models.go
Fixes ingestion not properly grabbing privileged/registry sessions
https://github.com/SpecterOps/BloodHound/issues/63
Added tests to ingest fixtuers
> Fix Privileged Session Ingest

- cmd/api/src/daemons/datapipe/agi.go
- cmd/api/src/go.mod
- cmd/api/src/go.sum
- packages/go/analysis/ad/membership.go
- packages/go/analysis/ad/queries.go
- packages/go/analysis/azure/post.go
- packages/go/analysis/azure/queries.go
- packages/go/analysis/impact/aggregator.go
- packages/go/analysis/impact/id_aggregator.go
- packages/go/dawgs/cardinality/cardinality.go
- packages/go/dawgs/cardinality/hyperloglog32.go
- packages/go/dawgs/cardinality/hyperloglog64.go
- packages/go/dawgs/cardinality/lock.go
- packages/go/dawgs/cardinality/roaring32.go
- packages/go/dawgs/cardinality/roaring64.go
- packages/go/dawgs/graph/node.go
- packages/go/dawgs/ops/ops.go
- packages/go/dawgs/traversal/traversal.go
- packages/go/log/log.go
This changeset updates a few utilities and moves some queries that do not belong in the data pipeline.
Cleanup and supporting refactor work in Enterprise.
Individual units.
> chore: Refactor graph tools

- packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.test.tsx
- packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.tsx
Fixes an issue causing the new API Key Management option to not appear in the My Profile page when user is logged in via SAML.
Related unit tests have been updated.
> Ensure API Key Management option appears in the My Profile page when user is logged in via SAML

- packages/cue/bh/ad/ad.cue
- packages/go/graphschema/ad/ad.go
- packages/javascript/bh-shared-ui/src/graphSchema.ts
A few additional fields were missing friendly names. This MR adds those into the schema files, complete with schemagen run.
Improved UX
Tested in local environment.
> BED-3717: Chore add friendly names for a few extra fields

- cmd/api/src/analysis/ad/post.go
- cmd/api/src/daemons/datapipe/convertors.go
- packages/cue/bh/ad/ad.cue
- packages/go/analysis/ad/post.go
- packages/go/ein/ad.go
- packages/go/ein/ein.go
- packages/go/ein/incoming_models.go
- packages/go/graphschema/ad/ad.go
- packages/javascript/bh-shared-ui/src/graphSchema.ts
> chore: handle isaclprotected and isdelted in ConvertObjectToNode, update enterpriseca ingestion, add properties to ad schema

- cmd/api/src/daemons/datapipe/convertors.go
- packages/cue/bh/ad/ad.cue
- packages/go/ein/ad.go
- packages/go/ein/incoming_models.go
- packages/go/graphschema/ad/ad.go
- packages/javascript/bh-shared-ui/src/graphSchema.ts
This PR adds ingestion support for new computer properties that SharpHound collects. More information on where these properties are collected from can be found here:
https://learn.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings?tabs=diffie-hellman#certificatemappingmethods
https://support.microsoft.com/en-us/topic/kb5014754-certificate-based-authentication-changes-on-windows-domain-controllers-ad2c23b0-15d8-4340-a468-4d4f3b188f16#bkmk_kdcregkey
* Adding support for additional attack paths
* Uploaded SharpHound data containing the new properties and ensured they are properly collected on the Computer
-   [ ] New feature (non-breaking …
> chore: Ingest DCRegistryData 

- packages/go/analysis/ad/adcs.go
Adds the TrustedForNTAuth method for post processing.
> feat: trustedforntauth

- cmd/ui/src/components/Header.tsx
- cmd/ui/src/components/LoginPage.tsx
- cmd/ui/src/views/Explore/ExploreSearch/CypherInput.tsx
Adds the base URL to image srcs since the root is different when served from the API.
These URL's are not currently resolving for the logos.
I compiled the API and ran the executable locally to better replicate how the application is being run in production.
> fix: include base url in img srcs

- cmd/ui/src/icons.ts
- packages/javascript/bh-shared-ui/src/components/NodeIcon/constants.ts
This PR updates the node icons for a few of the new nodes being added for ADCS support.
> Update ADCS Node Icons

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
bumped AzureHound to v2.1.5
Adding to next release candidate
> chore: bump AzureHound to v2.1.5

- packages/cue/bh/ad/ad.cue
- packages/go/graphschema/ad/ad.go
- packages/javascript/bh-shared-ui/src/graphSchema.ts
Fix the strings representation shown in the entity panel of cert template properties
Because we like it pretty.
Before:
After:
> Fix print version of CertTemplate properties

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Pulls in minor changes made during release staging.
Keep main fresh.
> Merge Staging Fixes into Main 

- packages/javascript/bh-shared-ui/src/utils/datetime.ts
Add new `LuxonDate` formats so we can handle Datetime and timezones separately.
The `<LocalizationProvider />` component does not support timezone tokens in the `inputFormat` string. So we need a way to display the Datetime and timezone tokens separately.
> Update luxon format enum

- packages/go/analysis/ad/adcs.go
The edge was generated from EnterpriceCAs of other domains with TrustedForNTAuth edges.
This seems to fix the issue.
> Fix TrustedForNTAuth edge

- packages/go/analysis/ad/adcs.go
The EnrollOnBehalfOf edge was not being created because it depends on other ADCS post-processed edges. This fixes the order of the creation of the edges.
Note that EnrollOnBehalfOf must be processed before ESC3.
Uploaded data from my lab and the edge was created as expected.
> Fix EnrollOnBehalfOf

- cmd/api/src/api/registration/v2.go
- cmd/api/src/api/v2/container.go
- cmd/api/src/docs/json/paths/v2/container-entity.json
- cmd/ui/src/ducks/entityinfo/types.ts
- cmd/ui/src/ducks/explore/types.ts
- cmd/ui/src/views/Explore/EntityInfo/content.ts
- packages/javascript/js-client-library/src/client.ts
Entity panel for Container node type.
Ticket: BED-3286
As a BH user, I want to be able to see information about Container nodes. 
Ran BHCE and the entity panel showed up as expected.
> feat: container entity panel

- .github/workflows/jira-issue-transfer.yml
Fixing Fields field
Unexpected input(s) 'extraFields', valid inputs are ['project', 'issuetype', 'summary', 'description', 'fields']
reviewed documentation again
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] Documentation updates are needed, and have been made accordingly.
> Correct Fields field

- cmd/api/src/api/v2/edge.go
- cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.tsx
- packages/go/analysis/ad/ad.go
- packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/Details.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/GoldenCert.tsx
Added Details section for GoldenCert edge.
For the user to be able to see detail nodes and edges that cause the GoldenCert edge.
Ran it locally and the detail nodes and edges showed up as expected.
> feat: GoldenCert details

- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/ManageCA.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/ManageCertificates.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKIEnrollmentFlag/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKIEnrollmentFlag/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKIEnrollmentFlag/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKIEnrollmentFlag/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKIEnrollmentFlag/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKIEnrollmentFlag/WritePKIEnrollmentFlag.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKINameFlag/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKINameFlag/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKINameFlag/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKINameFlag/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKINameFlag/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WritePKINameFlag/WritePKINameFlag.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
Add entity panel texts for ManageCA, ManageCertificates, WritePKIEnrollmentFlag, and WritePKINameFlag.
> feat: helptexts for ManageCA, ManageCertificates, WritePKIEnrollmentFlag, and WritePKINameFlag

- packages/javascript/js-client-library/src/types.ts
New collection properties associated with ADCS were added to the client job types.
These properties align with the updates to the client tables and are needed for compiling the BHE UI.
BHE UI builds successfully with these updates.
> Adcs client type update

- README.md
Minor verbiage tweaks to expand available info
Ease of adoption and consumption
Markdown preview
> Add BloodHound slack link and update quick-deploy

- cmd/api/src/database/migration/migrations/v5.3.0.sql
- cmd/ui/src/views/Explore/fragments.tsx
- dockerfiles/bloodhound.Dockerfile
- packages/javascript/bh-shared-ui/src/components/Disable2FADialog/Disable2FADialog.test.tsx
- packages/javascript/bh-shared-ui/src/components/Disable2FADialog/Disable2FADialog.tsx
- tools/docker-compose/api.Dockerfile
Merge in v5.3.0 after release
v5.3.0
RCs ahead of release
> Merge stage/v5.3.0

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
> Bump SharpHound to v2.3.0

- cmd/api/src/docs/json/definitions/attributes.json
- cmd/api/src/docs/json/definitions/models.json
- cmd/api/src/docs/json/definitions/parameters.json
- cmd/api/src/docs/json/definitions/v2.json
- cmd/api/src/docs/json/paths/v2/aiaca-entity.json
- cmd/api/src/docs/json/paths/v2/certtemplate-entity.json
- cmd/api/src/docs/json/paths/v2/enterpriseca-entity.json
- cmd/api/src/docs/json/paths/v2/ntauthstore-entity.json
- cmd/api/src/docs/json/paths/v2/rootca-entity.json
This PR updates the docs for new entity API endpoints added to support ADCS nodes.
* Add the `Hydrate Counts` query parameter
* Update the response structure to display the schema on the API Explorer page
* Add response definitions for Entity and Controller endpoints
* Use the common Error response across each of the new endpoints for consistency
* Make the docs more accurate and DRY them up
* Verified via API Explorer page
- …
> More ADCS API Doc Improvements

- packages/go/analysis/ad/post.go
The golden cert edge is added to the list of post processed edges.
This is used in logic in BHE.
> fix: add golden cert edge to post processed edges list

- packages/cue/bh/ad/ad.cue
- packages/go/graphschema/ad/ad.go
- packages/javascript/bh-shared-ui/src/graphSchema.ts
Add Home Directory to the schema and fix typo in "Marked Sensitive"
Accuracy and completion of schema
Local environment
-   [X] Bug fix (non-breaking change which fixes an issue)
> Fix: Add and update field names in schema

- packages/go/analysis/ad/adcs.go
Post operations encapsulate parallel operations that open connections against the database. In adcs post processing, we were failing to close these operations when error cases where hit, leading to connections staying open
See description
No testing required, this is the intended functionality
-   [ ] My changes include a …
> Failure to close connections can lead to conn exhaustion

- packages/javascript/bh-shared-ui/src/commonSearches.tsx
Domain Users RDP to Servers query inaccurately had "Server" in sentence caps. Moved it to fully uppercase.
Accuracy of query and response.
Local testing
-   [X] Bug fix (non-breaking change which fixes an issue)
> Update Domain Users RDP Query for case sensitivity

- .github/workflows/run-tests.yml
- docker-compose.testing.yml
- Make it easier to see debug logging from our test databases for troubleshooting purposes
- Show these logs during GitHub Actions for troubleshooting flakey tests
We've had some flakey tests lately but they're almost impossible to reproduce locally and we need to know what's going on within the databases
Local testing works, this PR will provide proof that the debug logs show up when the action runs
-   [ ] I have added and/or …
> chore: debug logging for test databases

- cmd/api/src/api/v2/agi.go
- cmd/api/src/api/v2/agi_test.go
- cmd/api/src/api/v2/auth/auth.go
- cmd/api/src/database/agi.go
- cmd/api/src/database/auth.go
- cmd/api/src/database/auth_test.go
- cmd/api/src/database/db.go
- cmd/api/src/database/mocks/db.go
`UpdateAssetGroup`, `UpdateAssetGroupSelector`, `DeleteAssetGroupSelector`, `CreateSAMLIdentityProvider`, and `UpdateSAMLIdentityProvider` now have audit log support.
Removed unused `RemoveAssetGroupSelector` method
Continuing our checklist for audit log
Local tests pass after minimal adjustment to match our new interface
- …
> feat: audit log entries 3/4/5

- cmd/api/src/analysis/ad/adcs_integration_test.go
- cmd/api/src/test/integration/harnesses.go
- cmd/api/src/test/integration/harnesses/esc10bharness1.json
- cmd/api/src/test/integration/harnesses/esc10bharness2.json
- cmd/api/src/test/integration/harnesses/esc10bharnesseca.json
- cmd/api/src/test/integration/harnesses/esc10bharnessvictim.json
- cmd/api/src/test/integration/harnesses/esc10bprincipalharness.json
- packages/go/analysis/ad/adcs.go
- packages/go/analysis/ad/esc1.go
- packages/go/analysis/ad/esc10.go
- packages/go/analysis/ad/esc3.go
- packages/go/analysis/ad/esc6.go
- packages/go/analysis/ad/esc9.go
- packages/go/analysis/ad/esc_shared.go
- packages/go/analysis/ad/queries.go
- packages/go/dawgs/cardinality/cardinality.go
- packages/go/dawgs/ops/ops.go
ESC10b post processing.
Integration tests have been added.
> feat: esc10b post processing

- packages/javascript/bh-shared-ui/src/commonSearches.tsx
Fixed typo
Query produced error
Query now works without error
-   [x ] Bug fix (non-breaking change which fixes an issue)
-   [ x] All new and existing tests passed.
> Fixed Typo in ADCS Cypher Query

- tools/docker-compose/neo4j.Dockerfile
Add apoc to our dev env to allow for batch operations when needed
Needed a batch operation for a dev issue
Everything worked after building a new neo4j image
> chore: add apoc to dev to allow for batch operations

- packages/go/analysis/ad/adcs.go
Remove feature flag gate for the described edges
See description
Testing is already complete, just removing a feature flag
> Enable 6b,9b.10b edges

- cmd/api/src/services/fileupload/file_upload_test.go
Remove accidental import of wrong buffer.
> fix: remove incorrect buffer import

- cmd/api/src/database/agi_test.go
Use standard lib slice in lieu of experimental slices pkg dependency
Less dependencies is good. 
Std lib is better.
Ran the test
> fix: replaces x/exp/slices with std lib slices

- packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC1/References.tsx
This change updates the link text for a handful of links which appear in the ADCSESC1 edge information panel.
This change improves the readability of the remediation links which appear in the ADCSESC1 edge information panel.
The application functionality has not changed therefore no changes in tests are required.
-   [ ] My …
> chore: replace display text for links in ADCSESC1 edge information panel

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Updates the sharphound versions to the newly cut v2.3.3 in associated dockerfiles
Supporting v5.8.0 BHCE release
> chore: bump sharphound versions in dockerfiles

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
These are updates to our dockerfiles for the collector version of azurehound.
New AzureHound release; Supporting the v5.8.0 release
> chore: update azurehound version in dockerfiles for download resources

- packages/javascript/bh-shared-ui/src/commonSearches.tsx
Minor fix in a saved query for ESC1.
> fix: add missing condition in saved query

- cmd/api/src/daemons/datapipe/delete.go
Delete edges and then nodes
Graph deletion is blowing up neo4j
> Performant graph delete

- cmd/api/src/api/v2/database_wipe.go
- cmd/api/src/api/v2/database_wipe_test.go
- cmd/api/src/model/appcfg/flag.go
- cmd/ui/src/views/DatabaseManagement/DatabaseManagement.test.tsx
- cmd/ui/src/views/DatabaseManagement/DatabaseManagement.tsx
Puts graph clearing options behind a feature flag this enabled by default but not user updatable.
Gives us levers to pull in the case of unexpected behavior.
> chore: gate graph clearing

- cmd/api/src/api/auth.go
- cmd/api/src/api/middleware/compression.go
- cmd/api/src/api/v2/agi.go
- cmd/api/src/auth/model.go
- cmd/api/src/config/config.go
- cmd/api/src/daemons/datapipe/azure_convertors.go
- cmd/api/src/migrations/manifest.go
- cmd/api/src/model/appcfg/parameter.go
- cmd/api/src/queries/graph.go
- packages/go/analysis/ad/ad.go
- packages/go/analysis/ad/adcs.go
- packages/go/analysis/ad/adcscache.go
- packages/go/analysis/ad/esc1.go
- packages/go/analysis/ad/esc10.go
- packages/go/analysis/ad/esc13.go
- packages/go/analysis/ad/esc3.go
- packages/go/analysis/ad/esc4.go
- packages/go/analysis/ad/esc6.go
- packages/go/analysis/ad/esc9.go
- packages/go/analysis/ad/esc_shared.go
- packages/go/dawgs/drivers/neo4j/cypher.go
- packages/go/ein/ad.go
Fixes some minor consistency issues with logging, including the use of `%w` in `log.Errorf`s in a few places
BED-4311
All changes should be no-op, validated myself, code review should validate as well.
> BED-4311: Minor logging fixes

- packages/cue/bh/ad/ad.cue
Fixes a broken cue file which was causing codegen issues
BED-4336
Ran through `just prepare-for-codereview` and got a green light, which means code generation and builds are working as intended
> BED-4336: Cue file problem

- packages/javascript/bh-shared-ui/src/components/HelpTexts/ExtendedByPolicy/ExtendedByPolicy.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ExtendedByPolicy/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ExtendedByPolicy/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ExtendedByPolicy/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ExtendedByPolicy/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ExtendedByPolicy/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/OIDGroupLink/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/OIDGroupLink/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/OIDGroupLink/OIDGroupLink.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/OIDGroupLink/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/OIDGroupLink/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/OIDGroupLink/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
Adds help text components for use when rendering edge information panels for edges of type `OIDGroupLink` and `ExtendedByPolicy`.
All existing tests pass.
> Edge help text for `OIDGroupLink` and `ExtendedByPolicy`

- packages/go/analysis/ad/esc3.go
The ADCSESC3 composition does not return any paths if the collection of enrollment agent restrictions was successful of the 2nd EnterpriseCA but the EnterpriseCA does not have enrollment agent restrictions. This PR fixes that.
I also replaced the cypher query for the composition as the existing one was wrong.
With lab data. …
> fix: broken ADCSESC3 composition

- cmd/api/src/daemons/datapipe/ingest.go
- cmd/api/src/test/fixtures/fixtures/expected_ingest_adcs.go
- packages/go/analysis/ad/adcs.go
Removes feature flags in prep for full release
See description
Integration tests
> Remove ESC13 Feature Flags

- packages/javascript/bh-shared-ui/src/commonSearches.tsx
Added a pre-defined query for ADCS ESC2.
We will not create an edge for this one, but we can still provide a cypher query to find the templates.
Locally.
> feat: add ESC2 pre-defined query

- cmd/api/src/analysis/ad/adcs_integration_test.go
- packages/go/analysis/ad/esc_shared.go
Reverse edge direction of ExtendedByPolicy
> Reverse edge direction on ExtendedByPolicy

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Updates the dockerfiles for the patch bump to SharpHound
Supporting v5.9.0
> chore: update sh version in dockerfiles

- examples/sample-data/README.md
Fixed a bad link.
Bad references are bad.
Tested in GH preview
> Fix example link

- .github/workflows/jira-issue-transfer.yml
- .github/workflows/pr-jira-issue-transfer.yml
Introduces Community PR Ticketing,  allowing the workflow to confirm the organization prior to creating a ticket.  Updates to Jira Issue Ticketing,  resulting in a confirmation workflow after creation to ensure there is enough information collected prior to ticketing to Jira. Updates the incorrect link to the corrected HTML link
Reduce incomplete information for Bug / Feature Requests,  introduce Community PR tickets to allow Engineering to review and merge community PR with normalized workflow
Will need to test live, since self-hosted runner is the only permitted worker for this workflow
-   [X] New feature (non-breaking change which adds functionality)
- …
> Q1 Jira Workflow Updates

- cmd/ui/src/ducks/explore/saga.ts
- packages/go/dawgs/graph/node_test.go
- packages/go/dawgs/graph/path_internal_test.go
- packages/go/dawgs/graph/relationships_test.go
- packages/javascript/bh-shared-ui/src/components/HelpTexts/AZUserAccessAdministrator/Abuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/AZUserAccessAdministrator/General.tsx
Code gen updates to support BED-4383
Proper code hygiene and license presence.
Local testing.
> BED-4383: Code hygiene updates

- cmd/api/src/model/appcfg/flag.go
Add a new feature flag for use with the FedRAMP EULA feature.
Note: FedRAMP Support is Enterprise only.
BED-4391
ran `just test -g`
> BED-4391: Add FedRAMP EULA feature flag

- dockerfiles/bloodhound.Dockerfile
Merge the staging branch back into main after our recent release. This also contains a fix for our dockerfile that resolves an issue we are having with our "Publish Edge Build" github action.
Close the open threads from the v5.10.0 release.
> Merge staging branch for v5.10.0 into main post-release

- .github/workflows/jira-issue-transfer.yml
Introduces Community PR Ticketing, allowing the workflow to confirm the organization prior to creating a ticket. Updates to Jira Issue Ticketing, resulting in a confirmation workflow after creation to ensure there is enough information collected prior to ticketing to Jira. Updates the incorrect link to the corrected HTML link
Correcting Logic and returning the ticket number
Reduce incomplete information for Bug / Feature Requests, introduce Community PR tickets to allow Engineering to review and merge community PR with normalized workflow
YAML verified through validator plugin
Will need to test live, since self-hosted runner is the only permitted worker for this workflow
-   [ ] Bug fix (non-breaking change which …
> Correcting Logic and returning the ticket number

- packages/cue/bh/ad/ad.cue
- packages/go/analysis/ad/esc_shared.go
- packages/go/graphschema/ad/ad.go
- packages/javascript/bh-shared-ui/src/graphSchema.ts
Rename a couple of properties. Only the display name in the entity panel.
Ticket: BED-4436
> docs: rename properties in certtemplate entity panel

- packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC1/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC3/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC4/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC6a/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC6b/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/WindowsAbuse.tsx
Fix abuse commands that did not work in some cases.
See ticket: BED-4440
> docs: fix certify and rubeus commands

- README.md
Add note about installing BHCE on Windows.
Ticket: BED-4453
> docs: windows installation note

- packages/javascript/bh-shared-ui/src/commonSearches.tsx
Adds hygiene section to pre-defined queries
We have more information we can share with users about their environments. Making it clear these are hygiene-related.
Validated in local dev environment
-   [X] New feature (non-breaking change which adds functionality)
> Bed 4464: Update pre-saved queries

- packages/javascript/js-client-library/src/client.ts
closes BED-4391
adds three endpoints to the js-client for fedramp eula purposes
> add endpoints for fedramp eula

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/pull_request_template.md
This PR updates the templates for Pull Requests and Issues
This is the first step in making some updates to improve our templates and create consistency within our process.
This introduces a requirement that all PR's must have an associated Jira ticket or GitHub issue.
For GitHub issues, a new section has been introduced for the author to indicate they intend to open an associated PR.
Some checklists have been modified to remove the "checklist" functionality in favor of "remove what doesn't apply" so that actual checklists can function as intended. For PRs, this also means changing the checklist verbiage to be inclusive so that all checks are required.
-  Chore (a change that does not modify the application functionality)
> Updated GitHub templates

- packages/go/openapi/src/schemas/api.request.user.set-secret.yaml
- packages/go/openapi/src/schemas/api.request.user.update.yaml
- packages/go/openapi/src/schemas/api.response.pagination.yaml
- packages/go/openapi/src/schemas/api.response.time-window.yaml
- packages/go/openapi/src/schemas/enum.audit-log-status.yaml
- packages/go/openapi/src/schemas/enum.client-type.yaml
- packages/go/openapi/src/schemas/enum.datapipe-status.yaml
- packages/go/openapi/src/schemas/enum.job-status.yaml
- packages/go/openapi/src/schemas/enum.mfa-activation-status.yaml
- packages/go/openapi/src/schemas/enum.risk-acceptance.yaml
- packages/go/openapi/src/schemas/null.int32.yaml
- packages/go/openapi/src/schemas/null.int64.yaml
- packages/go/openapi/src/schemas/null.string.yaml
- packages/go/openapi/src/schemas/null.time.yaml
- packages/go/openapi/src/schemas/null.uuid.yaml
Added more schemas to the new openapi docs in preparation for paths
This PR addresses: BED-4141
The last of the prep work to begin adding paths
> chore: added more base schemas to new openapi docs

- .github/pull_request_template.md
I have updated the pull request template for github
This PR addresses: #672 
Adds more information to pull requests to help contributors 
> chore: updated the github pull request template

- cmd/api/src/api/registration/v2.go
- cmd/api/src/api/v2/saved_queries.go
- cmd/api/src/database/db.go
- cmd/api/src/database/mocks/db.go
- cmd/api/src/database/saved_queries.go
> Bed 4534 stephanie

- cmd/ui/src/views/Explore/GraphView.tsx
> Dlh encode url

- packages/javascript/bh-shared-ui/src/components/ApiVersion.tsx
- packages/javascript/bh-shared-ui/src/components/PageWithTitle.tsx
- packages/javascript/bh-shared-ui/src/components/index.ts
- packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.test.tsx
- packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.tsx
Add API version to the My Profile page to make reporting issues easier.
Successful display:
Version loading:
Failed to load:
This PR addresses: BED-4541
Closes https://github.com/SpecterOps/BloodHound/issues/493
Bug reports require reporting a specific product version. At present, the only way to find that is using the API explorer or a separate API integration. We should make it easy to find.
Validated in local environment and updated tests to account for changes.
- Code comments (GoDocs / …
> BED-4541: Add server version to profile page

- packages/javascript/bh-shared-ui/src/commonSearches.tsx
- packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx
Handles several small tasks to get Hybrid Paths up and running
Closes: BED-4447
- Ensure new edges are enabled for pathfinding (turns out they were already wired up)
- Add relevant predefined cypher queries under a new heading in the Azure tab
- Add new edges to new headers in pathfinding filter list (enabled by default) 
- Local testing against a dataset with a good number of hybrid edges
- ![Screenshot from 2024-07-16 16-04-13](https://github.com/user-attachments/assets/2a0cb1c8-4d0e-4d0c-ab1e-54d8a1d106f8)
- ![Screenshot from 2024-07-16 16-15-50](https://github.com/user-attachments/assets/37f9c8c9-ae4e-45e3-b663-edc6893ccf21) …
> BED-4447: Hybrid Paths Small Tasks

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/aiacas.aiaca.id.controllers.yaml
- packages/go/openapi/src/paths/aiacas.aiaca.id.yaml
- packages/go/openapi/src/paths/certtemplate.certtemplates.id.controllers.yaml
- packages/go/openapi/src/paths/certtemplate.certtemplates.id.yaml
- packages/go/openapi/src/paths/containers.containers.id.controllers.yaml
- packages/go/openapi/src/paths/containers.containers.id.yaml
- packages/go/openapi/src/paths/enterprisecas.enterprisecas.id.controllers.yaml
- packages/go/openapi/src/paths/enterprisecas.enterprisecas.id.yaml
- packages/go/openapi/src/paths/eula.accept-eula.yaml
- packages/go/openapi/src/paths/ntauthstores.ntauthstores.id.controllers.yaml
- packages/go/openapi/src/paths/ntauthstores.ntauthstores.id.yaml
- packages/go/openapi/src/paths/rootcas.rootcas.id.controllers.yaml
- packages/go/openapi/src/paths/rootcas.rootcas.id.yaml
Addresses feedback and splits the work into smaller commits that was initially done in [BED-4141](https://specterops.atlassian.net/browse/BED-4141)
This PR addresses: [BED-4549](https://specterops.atlassian.net/browse/BED-4549)
Simplify and improve on our existing OpenAPI spec documentation
GoLand will only recognize valid OpenAPI specs when they are added as a path to the base document (openapi.yaml in this case), we can verify that there are no errors in the code through GoLand, but until all following tickets are complete we cannot test that the spec renders properly …
> BED-4549: Simple Entity Paths To OAPI Spec

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/computers.computers.id.admin-rights.yaml
- packages/go/openapi/src/paths/computers.computers.id.admin-users.yaml
- packages/go/openapi/src/paths/computers.computers.id.constrained-delegation-rights.yaml
- packages/go/openapi/src/paths/computers.computers.id.constrained-users.yaml
- packages/go/openapi/src/paths/computers.computers.id.controllables.yaml
- packages/go/openapi/src/paths/computers.computers.id.controllers.yaml
- packages/go/openapi/src/paths/computers.computers.id.dcom-rights.yaml
- packages/go/openapi/src/paths/computers.computers.id.dcom-users.yaml
- packages/go/openapi/src/paths/computers.computers.id.group-membership.yaml
- packages/go/openapi/src/paths/computers.computers.id.ps-remote-rights.yaml
- packages/go/openapi/src/paths/computers.computers.id.ps-remote-users.yaml
- packages/go/openapi/src/paths/computers.computers.id.rdp-rights.yaml
- packages/go/openapi/src/paths/computers.computers.id.rdp-users.yaml
- packages/go/openapi/src/paths/computers.computers.id.sessions.yaml
- packages/go/openapi/src/paths/computers.computers.id.sql-admins.yaml
- packages/go/openapi/src/paths/computers.computers.id.yaml
- packages/go/openapi/src/paths/eula.accept-eula.yaml
- Added all of the computers specs
- Corrected small typo in `eula.accept-eula.yaml`
- Ticket: https://specterops.atlassian.net/browse/BED-4550
- Subtask above is from here: https://specterops.atlassian.net/browse/BED-4141
- Simplifies and improves on our existing OpenAPI spec documentation
- I made sure to check that all refs and paths were correct and led to their proper locations
- …
> BED-4550: Add Computer Entity Paths to OAPI Spec

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/api-info.spec.yaml
- packages/go/openapi/src/paths/api-info.version.yaml
- packages/go/openapi/src/paths/audit.audit.yaml
- packages/go/openapi/src/paths/config.config.yaml
- packages/go/openapi/src/paths/config.features.id.toggle.yaml
- packages/go/openapi/src/paths/config.features.yaml
- packages/go/openapi/src/paths/eula.accept-eula.yaml
- packages/go/openapi/src/schemas/model.app-config-param.yaml
- packages/go/openapi/src/schemas/model.audit-log.yaml
- packages/go/openapi/src/schemas/model.components.base-ad-entity.yaml
- packages/go/openapi/src/schemas/model.components.int32.id.yaml
- packages/go/openapi/src/schemas/model.components.int64.id.yaml
- packages/go/openapi/src/schemas/model.components.timestamps.yaml
- packages/go/openapi/src/schemas/model.components.uuid.yaml
- packages/go/openapi/src/schemas/model.feature-flag.yaml
Added openapi source for api-info, config, and audits
This PR addresses: BED-4556
> Bed 4556 add api info to oapi spec

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/aiacas.aiaca.id.controllers.yaml
- packages/go/openapi/src/paths/aiacas.aiaca.id.yaml
- packages/go/openapi/src/paths/certtemplate.certtemplates.id.controllers.yaml
- packages/go/openapi/src/paths/certtemplate.certtemplates.id.yaml
- packages/go/openapi/src/paths/containers.containers.id.controllers.yaml
- packages/go/openapi/src/paths/containers.containers.id.yaml
- packages/go/openapi/src/paths/enterprisecas.enterprisecas.id.controllers.yaml
- packages/go/openapi/src/paths/enterprisecas.enterprisecas.id.yaml
- packages/go/openapi/src/paths/gpos.gpos.id.computers.yaml
- packages/go/openapi/src/paths/gpos.gpos.id.controllers.yaml
- packages/go/openapi/src/paths/gpos.gpos.id.ous.yaml
- packages/go/openapi/src/paths/gpos.gpos.id.tier-zero.yaml
- packages/go/openapi/src/paths/gpos.gpos.id.users.yaml
- packages/go/openapi/src/paths/gpos.gpos.id.yaml
- packages/go/openapi/src/paths/ntauthstores.ntauthstores.id.controllers.yaml
- packages/go/openapi/src/paths/ntauthstores.ntauthstores.id.yaml
- packages/go/openapi/src/paths/ous.ous.id.computers.yaml
- packages/go/openapi/src/paths/ous.ous.id.gpos.yaml
- packages/go/openapi/src/paths/ous.ous.id.groups.yaml
- packages/go/openapi/src/paths/ous.ous.id.users.yaml
- packages/go/openapi/src/paths/ous.ous.id.yaml
- packages/go/openapi/src/paths/rootcas.rootcas.id.controllers.yaml
- packages/go/openapi/src/paths/rootcas.rootcas.id.yaml
Moving our GPO and OUS specs to a flattened format in a common directory
This PR addresses: BED-4552
Simplifies and improves our OAPI spec layout
Goland was used to verify that the files are correctly recognized as OAPI specs and references correctly
[BED-4552]: …
> BED-4552 GPO OUS Specs

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/users.users.id.admin-rights.yaml
- packages/go/openapi/src/paths/users.users.id.constrained-delegation-rights.yaml
- packages/go/openapi/src/paths/users.users.id.controllables.yaml
- packages/go/openapi/src/paths/users.users.id.controllers.yaml
- packages/go/openapi/src/paths/users.users.id.dcom-rights.yaml
- packages/go/openapi/src/paths/users.users.id.memberships.yaml
- packages/go/openapi/src/paths/users.users.id.ps-remote-rights.yaml
- packages/go/openapi/src/paths/users.users.id.rdp-rights.yaml
- packages/go/openapi/src/paths/users.users.id.sessions.yaml
- packages/go/openapi/src/paths/users.users.id.sql-admin-rights.yaml
- packages/go/openapi/src/paths/users.users.id.yaml
- Added all of the users specs
- Ticket: BED-4553
- Subtask above is from here: BED-4141
- Simplifies and improves on our existing OpenAPI spec documentation
- I made sure to check that all refs and paths were correct and led to their proper locations
> BED-4553: Add User Entity Paths to OAPI Spec

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/azure.entity.yaml
- packages/go/openapi/src/paths/base.base.id.controllables.yaml
- packages/go/openapi/src/paths/base.base.id.controllers.yaml
- packages/go/openapi/src/paths/base.base.id.yaml
- packages/go/openapi/src/paths/meta-entity.meta.id.yaml
- Added all of the base, azure, and meta specs
- Ticket: BED-4554
- Subtask above is from here: BED-4141
- Simplifies and improves on our existing OpenAPI spec documentation
- I made sure to check that all refs and paths were correct and led to their proper locations
> BED-4554: Add Base Entity, Azure Entity, and Meta Entity Paths to OAPI Spec

- cmd/api/src/database/migration/migrations/v5.13.0.sql
- cmd/ui/public/img/logo-secondary-transparent-banner.svg
- cmd/ui/public/img/logo-secondary-transparent-full.svg
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/PageWithTitle.tsx
- packages/javascript/bh-shared-ui/src/utils/colors.ts
Adds a migration file for the dark mode feature flag.
Also adds license headers to file that were missing them.
This PR addresses: BED-4585
This query was run using pg admin for validation. …
> fix: dark mode migration

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/auth.login.yaml
- packages/go/openapi/src/paths/auth.logout.yaml
- packages/go/openapi/src/paths/auth.saml.providers.id.yaml
- packages/go/openapi/src/paths/auth.saml.providers.yaml
- packages/go/openapi/src/paths/auth.saml.sso.yaml
- packages/go/openapi/src/paths/auth.saml.yaml
- packages/go/openapi/src/paths/auth.self.yaml
- packages/go/openapi/src/paths/bh-users.bloodhound-users.id.mfa-activation.yaml
- packages/go/openapi/src/paths/bh-users.bloodhound-users.id.mfa.yaml
- packages/go/openapi/src/paths/bh-users.bloodhound-users.id.secret.yaml
- packages/go/openapi/src/paths/bh-users.bloodhound-users.id.yaml
- packages/go/openapi/src/paths/bh-users.bloodhound-users.yaml
- packages/go/openapi/src/paths/permissions.permissions.id.yaml
- packages/go/openapi/src/paths/permissions.permissions.yaml
- packages/go/openapi/src/paths/roles.roles.id.yaml
- packages/go/openapi/src/paths/roles.roles.yaml
- packages/go/openapi/src/paths/tokens.tokens.id.yaml
- packages/go/openapi/src/paths/tokens.tokens.yaml
- packages/go/openapi/src/schemas/api.requests.user.set-secret.yaml
- packages/go/openapi/src/schemas/api.requests.user.update.yaml
- packages/go/openapi/src/schemas/model.auth-secret.yaml
- packages/go/openapi/src/schemas/model.auth-token.yaml
- packages/go/openapi/src/schemas/model.permission.yaml
- packages/go/openapi/src/schemas/model.role.yaml
- packages/go/openapi/src/schemas/model.saml-provider.yaml
- packages/go/openapi/src/schemas/model.saml-sign-on-endpoint.yaml
- packages/go/openapi/src/schemas/model.user.yaml
Added endpoint defs for:
- auth
- permissions
- roles
- tokens
- bh-users
This PR addresses: BED-4141 / BED-4557
> BED-4557: added auth and user endpoints to openapi spec

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/cypher.graphs.cypher.yaml
- packages/go/openapi/src/paths/cypher.saved-queries.id.yaml
- packages/go/openapi/src/paths/cypher.saved-queries.yaml
- packages/go/openapi/src/paths/graph.graph-search.yaml
- packages/go/openapi/src/paths/graph.graphs.edge-composition.yaml
- packages/go/openapi/src/paths/graph.graphs.shortest-path.yaml
- packages/go/openapi/src/paths/graph.pathfinding.yaml
- packages/go/openapi/src/paths/search.available-domains.yaml
- packages/go/openapi/src/paths/search.search.yaml
- packages/go/openapi/src/schemas/model.domain-selector.yaml
- packages/go/openapi/src/schemas/model.saved-query.yaml
- packages/go/openapi/src/schemas/model.search-result.yaml
- packages/go/openapi/src/schemas/model.unified-graph.edge.yaml
- packages/go/openapi/src/schemas/model.unified-graph.graph.yaml
- packages/go/openapi/src/schemas/model.unified-graph.node.yaml
Added endpoint definitions to open api spec for:
- cypher
- graph
- search
This PR addresses: BED-4141 / BED-4559
> BED-4559: added grapher, cypher, and search endpoints to openapi spec

- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/data-quality.ad-domains.id.data-quality-stats.yaml
- packages/go/openapi/src/paths/data-quality.azure-tenants.id.data-quality-stats.yaml
- packages/go/openapi/src/paths/data-quality.clear-database.yaml
- packages/go/openapi/src/paths/data-quality.completeness.yaml
- packages/go/openapi/src/paths/data-quality.platform.id.data-quality-stats.yaml
- packages/go/openapi/src/paths/datapipe.analysis.yaml
- packages/go/openapi/src/paths/datapipe.datapipe.status.yaml
- packages/go/openapi/src/schemas/model.ad-data-quality-aggregation.yaml
- packages/go/openapi/src/schemas/model.ad-data-quality-stat.yaml
- packages/go/openapi/src/schemas/model.azure-data-quality-aggregation.yaml
- packages/go/openapi/src/schemas/model.azure-data-quality-stat.yaml
Added endpoint definitions to open api spec for:
- datapipe
- data-quality
This PR addresses: BED-4141 / BED-4560
> BED-4560: add data related endpoints to open api spec

- cmd/ui/src/components/LoginForm/LoginForm.tsx
- cmd/ui/src/components/LoginViaSAMLForm/LoginViaSAMLForm.tsx
- cmd/ui/src/views/DisabledUser.tsx
This will fix the button styles in the login page. 
This PR addresses: BED-4608
There was a regression in the styles applied to the login buttons when they were swapped for the DoodleUI button in the dark mode PR.
Styles were verified visually; See screenshots below.
> fix: login button styles

- cmd/ui/src/App.tsx
- cmd/ui/src/components/LoginForm/LoginForm.tsx
- cmd/ui/src/components/LoginViaSAMLForm/LoginViaSAMLForm.tsx
- cmd/ui/src/rendering/programs/edge-label.ts
- cmd/ui/src/rendering/programs/node-hover.ts
- cmd/ui/src/rendering/programs/node-label.ts
- cmd/ui/src/rendering/utils/utils.ts
- cmd/ui/src/styles/general.scss
- cmd/ui/src/utils.ts
- cmd/ui/src/views/DisabledUser.tsx
- cmd/ui/src/views/Explore/ExploreSearch/CypherSearch.tsx
- cmd/ui/src/views/Explore/GraphView.tsx
- cmd/ui/src/views/Explore/utils.ts
- packages/javascript/bh-shared-ui/src/components/AssetGroupEdit/AssetGroupEdit.tsx
- packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.test.tsx
- packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.tsx
- packages/javascript/bh-shared-ui/src/components/AssetGroupMemberList/AssetGroupMemberList.tsx
- packages/javascript/bh-shared-ui/src/components/GroupManagementContent/GroupManagementContent.tsx
- packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
- packages/javascript/bh-shared-ui/src/constants.ts
- packages/javascript/bh-shared-ui/src/utils/icons.ts
- packages/javascript/bh-shared-ui/src/views/Explore/InfoStyles/Pane.tsx
This changeset contains updates to the styling changes that were made for dark mode.
This PR addresses: BED-4588
Now that we've cut the rc for v5.13.0 we have different environments to view these changes in which more people have eyes on and with varying states of data which render different components. We want to patch anything we've missed with our first pass of dark mode before releasing the new BH version.
- Database …
> fix: misc. updates to styles

- packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/WindowsAbuse.tsx
The windows abuse description for `SyncedToEntraUser` (new edge) Edge Panel.
This PR addresses: BED-4444
The windows abuse description was copy pasted from `SyncedToADUser` and hadnt been updated.
> Bed 4444: Fix windows abuse content

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
This PR bumps the included SharpHound version to `v2.5.4`. This build includes a number of fixes for bugs found during testing.
* Include the latest fixes for this release.
* Verified the correct version is listed on the Download Collectors page
> BED-4636 Bump SharpHound version to v2.5.4

- packages/go/openapi/doc/openapi.json
- packages/go/openapi/src/openapi.yaml
- packages/go/openapi/src/paths/auth.saml.providers.id.yaml
- packages/go/openapi/src/paths/config.config.yaml
- packages/go/openapi/src/paths/tokens.tokens.yaml
- packages/javascript/bh-shared-ui/src/constants.ts
Fixed some incorrect API tags
Also a few rogue linter changes in a ts file
This PR addresses: BED-4667
> fix: BED-4667 - fix incorrect openapi tags

- cmd/api/src/config/config.go
This thing never got used and as part of BED-4688 I'd like to remove it.
Don't live with broken windows.
No test needed. It's not used.
> chore: BED-4688 - clean up an old unusued configuration element

- cmd/api/src/database/saved_queries.go
Hot fix. Updated db function to pull from the right table.
Quick fix for updating db table
Unit tests pass.  Screenshots attached.
[response_1723839033521.json](https://github.com/user-attachments/files/16641378/response_1723839033521.json)
[response_1723839051105.json](https://github.com/user-attachments/files/16641379/response_1723839051105.json)
[response_1723839064078.json](https://github.com/user-attachments/files/16641382/response_1723839064078.json)
[response_1723839077717.json](https://github.com/user-attachments/files/16641383/response_17238 …
> updated table

- README.md
Updates README.md to more clearly communicate how to install and upgrade BloodHound CE. Previously, the one-liner could result in users not getting the latest version of BloodHound if the command was run multiple times in a row due to how Docker image caching works.
Insure users know how to install and upgrade BloodHound consistently to have the latest version.
Validated instructions locally.
- …
> BED-4720 - Update installation/upgrade docs

- cmd/ui/src/App.test.tsx
Fixes a silent error happening but not breaking the <Inner /> component test. 
This PR addresses: BED-4738
This error doesnt effect the test directly, however it added noise to the UI testing in CI and locally. The error came from a child of the Inner component. Thank you @urangel for the spelunking help here!
Tests pass without erroring
> Bed 4738: fix silent error in <Inner /> test

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
we have a new version of azurehound and sharphound going into this release so needed to bump the versions for each …
> bump hound versions for RC

- parca.yaml
Added missing license to parca.yaml
Linked to BED-4797 general maintenance for release
No testing needed.
> chore: add license to file

- cmd/api/src/database/agi.go
- cmd/api/src/database/audit.go
- cmd/api/src/database/auth.go
- cmd/api/src/database/file_upload.go
- cmd/api/src/database/saved_queries.go
- cmd/api/src/model/saved_queries_test.go
- packages/go/graphschema/ad/ad.go
- packages/go/graphschema/azure/azure.go
- packages/go/graphschema/common/common.go
- parca.yaml
- tools/docker-compose/api.Dockerfile
Pass in multiple values to GORM `.Where` clauses
This PR addresses: BED-4775
The GORM `.Where` method is variadic, expecting multiple arguments to be passed in for positional arguments.
Simply passing in the filter parameters in with `...` allows for the method to properly expand the slice and place the positional arguments where needed.
I created a single `saved_query` that I will use to query for
I started BHCE with `SB_LOG_LEVEL=debug just bh-debug`
When hitting the endpoint on `main`
We can inspect the console for additional information on how GORM is building our query
When checking out this branch and executing the same query, we can properly use multiple predicates
- …
> BED-4775 fixed multiple predicate SQL building error.

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Bump AzureHound for release
This PR addresses: BED-4803
Bump AzureHound for RC
Tested locally
> BED-4803 hound bump

- README.md
We have received multiple issue reports recently related to deploying BloodHound CE with insufficient system resources. This PR adds minimum recommended system specs to deploy the application.
This PR addresses: BED-4854
Markdown preview
> BED-4854 add system requirements to README

- cmd/api/src/database/migration/migrations/v6.0.0.sql
- cmd/ui/src/App.tsx
- packages/go/analysis/azure/tenant.go
- packages/javascript/bh-shared-ui/src/components/HelpTexts/Contains/Abuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/Contains/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
This PR merges the staging branch for `v6.0.0` back into `main`
Staging branches should be merged back into `main` after release. …
> chore: merge v6.0.0 release branch

- cmd/api/src/api/v2/analysisrequest.go
Fixes an error format
This PR addresses: https://specterops.atlassian.net/browse/BED-4944
Tested using bruno
> Fix: Error in RequestAnalysis when scheduled analysis is set

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Updates SharpHound to the newest version
This PR addresses: https://specterops.atlassian.net/browse/BED-4949
> chore: update collectors

- cmd/api/src/api/v2/analysisrequest.go
- cmd/api/src/database/datapipestatus.go
- cmd/api/src/database/datapipestatus_test.go
- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
See title
This PR addresses: https://specterops.atlassian.net/browse/BED-4951
Tested during RC
> Merge stage 6.1.0 back into main

- packages/go/analysis/ad/ad.go
Added the following assets to the default Tier Zero / high value asset group:
- AdminSDHolder (container): Permissions applies to Domain Admins and other privileged principals.
- Distributed COM Users (group): Vulnerable to remote compromise of users on DCs via coerce + NTLM relay attacks.
- Performance Log Users (group): Similar remote compromise risk on DCs.
- DnsAdmins (group): Controls DNS, enabling relay attacks (even Kerberos).
This PR addresses: BP-1111
The assets that have direct/indirect control over the AD environment should be tagged as Tier Zero by default.
Uploaded this dataset: 
[20231208161111_BloodHound.zip](https://github.com/user-attachments/files/17661410/20231208161111_BloodHound.zip)
- Assigned myself to …
> BP-1111 feat: more default T0 nodes

- cmd/api/src/api/constant.go
- cmd/api/src/api/v2/attack_path.go
This adds some constants needed for the BHE implementation of the Posture API Changes in #953.
This PR addresses: BED-4894
No testable logic.
> BED-4894: Posture API Implementation

- packages/go/analysis/hybrid/hybrid.go
- packages/go/analysis/post_integration_test.go
This was a missed integration test for BED-4954.
Missing regression validation. Good opportunity to knowledge share and close a coverage gap.
Test is as written.
> chore: BED-4954 - provide formal integration test to cover ticket

- cmd/api/src/model/samlprovider.go
- packages/go/analysis/post_integration_test.go
- packages/go/graphschema/ad/ad.go
- packages/go/graphschema/azure/azure.go
- packages/go/graphschema/common/common.go
Adds some changes from the prep for code review functionality that were missing.
This PR addresses: BED-4403
After running prep for code review the changeset in CE was dirty so am pushing these changes up.
Non material changes.
> chore: prep review changes

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
See title
This PR addresses: https://specterops.atlassian.net/browse/BED-5095
> Update SharpHound to v2.5.9

- cmd/api/src/api/tools/pg.go
- packages/go/dawgs/drivers/pg/pg_integration_test.go
- packages/go/dawgs/drivers/pg/query/format.go
- packages/go/dawgs/drivers/pg/query/sql/schema_up.sql
- packages/go/dawgs/drivers/pg/statements.go
Close out the v6.2.3 staging branch as per the checklist in BED-5092.
This version was released.
> BED-5092 - Merge stage/v6.2.3

- packages/go/analysis/ad/queries.go
Update the `FetchForeign*()` and `CreateForeignEntityMembership*Delegate()` methods to fall back to trying the `ObjectID` property when the `DomainSID` property is missing on the domain node.
This PR addresses: BED-4841
The Foreign Members list fails to load on a domain missing `DomainSID` because the endpoints return a 500 error.
1. Loaded the AD example data
2. Queried for `match (n:Domain) return n`
3. Verified that none of the domains show an error for the Foreign Members section
- Code comments …
> BED-4841: fix: fall back to ObjectID when DomainSID is missing while loading foreign members

- packages/go/cypher/models/pgsql/translate/translator.go
These functions were re-added during a merge of a long lived hotfix branch from December.
Clean up linting.
> chore: BED-5260 - remove unused functions

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Update SharpHound to the latest version
This PR addresses: BED-5259
> feat: update SharpHound to v2.5.13

- .github/config/integration.config.json
- cmd/api/src/api/tools/pg_test.go
- cmd/api/src/config/default.go
- cmd/api/src/migrations/graph.go
- cmd/api/src/migrations/manifest.go
- cmd/api/src/test/integration/utils/integration-config.json
- local-harnesses/integration.config.json.template
Moving integration test configurations to PostgreSQL.
In line with our move to PG we're starting with testing infrastructure.
> BED-5294 - Move Integration Test Configurations to PG

- cmd/ui/src/ducks/global/actions.ts
- packages/javascript/bh-shared-ui/src/components/GroupManagementContent/GroupManagementContent.tsx
- packages/javascript/bh-shared-ui/src/views/DataQuality/DataSelector/DataSelector.tsx
changes from codegen / linting
This PR addresses: BED-5207
pain
pain
> Bed 5207 impact exposure findings

- .github/workflows/reusable.docker-content-trust.yml
> cd: update environment variables

- .github/workflows/reusable.build-container-image.yml
> ci: pull submodules on checkout

- cmd/api/src/analysis/ad/adcs_integration_test.go
- cmd/api/src/analysis/ad/ntlm_integration_test.go
- cmd/api/src/analysis/ad/post.go
- packages/go/analysis/ad/adcs.go
- packages/go/analysis/ad/adcscache.go
- packages/go/analysis/ad/ntlm.go
Fixes an issue introduced in the RelayNTLMtoADCS work
Tests broken
Ran tests locally
> Fix breakage in ADCS integration tests in BHE

- docs/hc/en-us/categories/resources.mdx
- docs/hc/en-us/get-started/bloodHound-community-edition-quickstart.mdx
- docs/hc/en-us/get-started/bloodHound-enterprise-quickstart.mdx
- docs/mint.json
As part of the Mintlify doc revamp, this PR updates the information architecture, including a new Resources section. 
This PR addresses: [#1085](https://github.com/SpecterOps/BloodHound/issues/1085)
Tested locally with Mintlify for broken links and broken site
- Chore
- Docs
I have read the CLA Document and I hereby sign the CLA
> Update information architecture

- cmd/ui/src/components/MainNav/MainNavData.tsx
- packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/Download.tsx
- packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/index.ts
- packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
Added download collectors to nav and changed order
This PR addresses: [BED-5379](https://specterops.atlassian.net/browse/BED-5379)
Manually
[BED-5379]: https://specterops.atlassian.net/browse/BED-5379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BED-5379: Added download collectors to nav and changed order

- packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
- packages/javascript/bh-shared-ui/src/components/Navigation/SubNav.tsx
In this PR we address the following:
- Made the underline color same as text in the active route in the admin nav for both light and dark mode
- Took the opportunity (and made the above fix easier) to clean up styling and item structure in SubNav to match up MainNav
- Added scroll to admin nav
- Sneaked in a fix for the main nav that only needed to add text underline on hover but it was changing the text color which produced a contrast issue in dark mode
This PR addresses: [BED-5395](https://specterops.atlassian.net/browse/BED-5395)
Manually/Visually
For the issue of the Global Side Nav:
Before:
After:
- …
> BED-5895:  Underline color same as text color in active route in admin nav

- packages/go/dawgs/graph/types.go
- packages/python/beagle/beagle/plan/yarn.py
- tools/docker-compose/api.Dockerfile
This updates the base image used in building the API to use a newer version of alpine that has up to date dependencies which are more secure.
This PR addresses: BED-5399
This is being done for security hygiene. 
> chore: update containers base images

- packages/go/cypher/models/pgsql/translate/building.go
- packages/go/cypher/models/pgsql/translate/function.go
- packages/go/cypher/models/pgsql/translate/projection.go
- packages/go/cypher/models/pgsql/translate/query.go
- packages/go/cypher/models/pgsql/translate/relationship.go
- packages/go/cypher/models/pgsql/translate/tracking_test.go
- packages/go/cypher/models/pgsql/translate/translator.go
- packages/go/graphschema/ad/ad.go
- packages/go/graphschema/azure/azure.go
- packages/go/graphschema/common/common.go
- packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/BHELogo.tsx
- packages/javascript/bh-shared-ui/src/hooks/useApiVersion.tsx
- packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.tsx
`just prepare-for-codereview`
This PR addresses: BED-5406 `just prepare-for-codereview`
`just prepare-for-codereview`
`just prepare-for-codereview`
`just prepare-for-codereview`
`just prepare-for-codereview`
- Chore `just prepare-for-codereview`
- `just prepare-for-codereview`
- `just prepare-for-codereview`
- `just prepare-for-codereview`
> just prepare-for-codereview

- cmd/api/src/database/migration/migrations/v7.1.0.sql
Closes BED-5267
Adds the `tier_management_engine` feature flag. The flag is not enabled or user updateable.
This PR addresses: BED-5267
While this flag is not enabled or updateable as it is being added, it will enable local development of this new feature set. 
The migration was confirmed to execute locally:
```
bhe=# select *  from feature_flags where key='tier_management_engine';
id |          created_at           |          updated_at           |          key           |          name          |                                description                                | enabled | user_updatable
----+-------------------------------+-------------------------------+------------------------+------------------------+---------------------------------------------------------------------------+ …
```
> feat: adds the `tier_management_engine` feature flag

- packages/go/graphschema/ad/ad.go
- packages/go/graphschema/azure/azure.go
- packages/go/graphschema/common/common.go
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/CoerceAndRelayNTLMToADCS.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/Composition.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/CoerceAndRelayNTLMToLDAP.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/CoerceAndRelayNTLMToLDAPS.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/WindowsAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/CoerceAndRelayNTLMToSMB.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/Composition.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/General.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/LinuxAbuse.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/Opsec.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/References.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/WindowsAbuse.tsx
Creates new edge texts for NTLM relay edges
https://specterops.atlassian.net/browse/BED-5032
https://specterops.atlassian.net/browse/BED-5027
https://specterops.atlassian.net/browse/BED-5037
- Code comments (GoDocs / …
> New edge texts for NTLM Relay Edges

- .github/actions/build-container-image/action.yml
> ci: build amd64 and arm64 images

- .github/actions/build-container-image/action.yml
- .github/workflows/reusable.build-container-image.yml
> ci: login to container registries only when creds are available

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> ci: use github actions cache

- tools/docker-compose/api.Dockerfile
Merge back from last release branch.
> Merge Stage v7.1.1

- cmd/ui/src/components/GraphButtons/GraphButtons.test.tsx
- cmd/ui/src/components/GraphButtons/GraphButtons.tsx
- cmd/ui/src/views/Explore/GraphView.tsx
- cmd/ui/src/views/Explore/GraphViewV2.tsx
- Added the functionality that builds exportToJson data in the GraphViewV2 component that is handling deep linking
- Updated the disabled functionality for the Export functionality as a prop instead of being inside the GraphButtons component
- Fixed tests related to GraphButtons component
This PR addresses: [BED_5538](https://specterops.atlassian.net/browse/BED-5538)
Manually tested exporting graph data in different situations. All existing tests passed. …
> BED-5538: Support Export Graph data functionality in deep linking

- cmd/ui/src/hooks/useInitialEnvironment/useInitialEnvironment.test.tsx
- cmd/ui/src/hooks/useInitialEnvironment/useInitialEnvironment.tsx
- cmd/ui/src/mocks/browser.ts
- cmd/ui/src/views/GroupManagement/GroupManagement.tsx
- cmd/ui/src/views/QA/QA.tsx
- packages/javascript/bh-shared-ui/rollup.config.js
- packages/javascript/bh-shared-ui/src/components/GroupManagementContent/GroupManagementContent.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/RelayTargets.tsx
Fixes follow bugs:
- initial environment changing on window refocus
- missing member counts
- circular dependency and non duplicated dependency from RelayTargets
This PR addresses: BED-5591
Manual tests
> BED-5591: GroupManagement missing member counts (and some bugs)

- .github/workflows/build-ui.yml
- .github/workflows/ci.yml
- .github/workflows/run-tests.yml
- .github/workflows/static-code-analysis.yml
- .github/workflows/vuln-scan.yml
Update BHCE actions configuration to run actions regardless of branch rules.
This PR addresses: BED-5602
> ci: run checks for PRs against stage

- cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.tsx
- packages/javascript/bh-shared-ui/rollup.config.js
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/RelayTargets.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/RelayTargets.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/RelayTargets.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/RelayTargets.tsx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
- packages/javascript/bh-shared-ui/src/components/index.ts
> fix: RelayTargets accordion crash

- docs/resources/release-notes/v7-2-0.mdx
Descriptions are hard..
This PR addresses: BED-5560
Local env.
> BED-5560 Fix Rel Notes Nit

- docs/get-started/quickstart/community-edition-quickstart.mdx
> Bhce install via bloodhound cli rather than with ghost.ly link via DockerHub

- examples/docker-compose/docker-compose.yml
- examples/helm/values.yaml
- tools/docker-compose/neo4j.Dockerfile
This PR addresses: [BED-4145](https://specterops.atlassian.net/browse/BED-4145)
This upgrade is necessary to address container vulnerabilities present in lower versions.
The changes were tested by running the application locally and performing a file upload to verify functionality.
[BED-4145]: …
> chore(docker): Upgrade Neo4j base image to version 4.4.42

- tools/docker-compose/api.Dockerfile
Update SH to current version v2.6.2
> chore: version SH bump

- docs/get-started/quickstart/community-edition-quickstart.mdx
Added update instructions to QuickStart documentation
> Added update instructions to QuickStart documentation

- cmd/api/src/database/migration/migrations/v7.3.0.sql
The migration needs to be idempotent-- add "if exists" / "if not exists" conditionals where needed
This PR addresses: [BED-5637]
Shoutout to guy incognito, the goat of PR review
- Read the …
> BED-5637: idempotent migration fix

- packages/javascript/bh-shared-ui/src/components/DocumentationLinks.tsx
Correct AzureHound CE documentation link
This PR addresses: https://specterops.atlassian.net/browse/BED-5709
Localhost
> [BED-5709] Correct AzureHound CE documentation link

- dockerfiles/bloodhound.Dockerfile
Update SharpHound version for docker container build.
This PR addresses: https://specterops.atlassian.net/browse/BED-5710
> [BED-5710] Update SH Foss version ref to 2.6.2

- docs/resources/release-notes/overview.mdx
Removes an unnecessary link.
This PR addresses: BED-5710
Locally
> BED-5710: Remove errant release note link

- docs/get-started/quickstart/community-edition-quickstart.mdx
Updates quickstart docs for improved accuracy of commands on Windows
closes: BED-5731
mintlify local
> docs: BED-5731 Fix windows installer docs

- rfc/rfc-template.md
Created an RFC template
https://specterops.atlassian.net/browse/BED-5693
Documentation only
> BED-5693: Create an RFC template for use as a starting point when creating an RFC

- cmd/api/src/database/migration/migrations/schema.sql
fixes: BED-5733
Mark the DarkMode flag as non-editable
BED-5733
> fix(migrations): DarkMode feature flag as non-editable

- cmd/api/src/database/migration/migrations/v7.3.0.sql
Creates migration to update feature flags for NTLM GA
This PR addresses: https://specterops.atlassian.net/browse/BED-5622
> BED-5622: NTLM GA

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Bumps Sharphound versions for release
> chore: bump sharphound versions for release

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
> chore: update sharphound collectors to 2.6.5

- cmd/api/src/migrations/manifest.go
- cmd/api/src/migrations/migrations_test.go
- cmd/api/src/test/integration/harnesses.go
Delete's all SMBSigning values from computers 
https://specterops.atlassian.net/browse/BED-5786
> Delete all false smbsigning values

- docs/collect-data/ce-collection/azurehound.mdx
- docs/install-data-collector/install-sharphound/create-gmsa.mdx
A community member identified errant escape characters in code blocks. Get those fixed up for accuracy.
Resolves BED-5850
Mintlify local dev
Current:
New:
> docs: BED-5850 Fix unintended escape characters in codeblocks

- docs/docs.json
- docs/get-started/quickstart/community-edition-quickstart.mdx
- docs/resources/edges/add-member.mdx
- docs/resources/edges/add-self.mdx
- docs/resources/edges/allowed-to-act.mdx
- docs/resources/edges/force-change-password.mdx
- docs/resources/edges/has-session.mdx
- docs/resources/edges/owns.mdx
- docs/resources/edges/sql-admin.mdx
- docs/resources/edges/write-account-restrictions.mdx
- docs/resources/edges/write-owner.mdx
- packages/javascript/bh-shared-ui/src/components/HelpTexts/SameForestTrust/References.tsx
Rip out additional references to old docs site
Resolves BED-5873
Validated in mintlify local
> docs: BED-5873 Clean up addl refs to old support site

- cmd/api/src/api/v2/assetgrouptags.go
- cmd/api/src/api/v2/assetgrouptags_test.go
- packages/go/openapi/doc/openapi.json
- packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.selectors.yaml
- packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.test.tsx
Resolves https://specterops.atlassian.net/browse/BED-5848
Unit tests updated to verify function
> BED-5848: API task Add `counts` query param to return member counts

- cmd/api/src/database/migration/migrations/v7.4.0.sql
Updated migration to make EA of tier management user updatable
This PR implements BED-5884. This will allow for early access to phase 1 of the tiering management engine.
Validated in DBeaver locally
> BED-5884 - migration for tier management early access

- packages/javascript/bh-shared-ui/src/views/TierManagement/Cypher/Cypher.tsx
- packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.test.tsx
- packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx
Fixes a couple of rendering issues with the cypher preview and the Objects list in Tier Management Details page.
Resolves BED-5895
The Cypher Preview was not changing query values consistently when clicking on a different selector which is now fixed. The Objects list would a variable number of objects from the previous list based on the counts of the current and previous selector. Lists should be accurate with this change.
See screencapture below
Previous:
https://github.com/user-attachments/assets/a9725091-8b16-4b74-94af-3665b2764a5f
With fixes:
https://github.com/user-attachments/assets/6801c809-4d15-495c-aca3-55587fc99518 …
> fix: cypher preview rerender and members list rendering

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
SharpHound version bump to v2.6.6
Resolves [BED-5562](https://specterops.atlassian.net/browse/BED-5562)
- All new and existing tests …
> Kstrader/sh_version bump v2.6.6

- packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.tsx
Refactored the profile page to remove redundant code.
Updated description for user profile.
Resolves [ BED-5791]
To provide more context and clear up possible confusion.
> refactor user profile, update description

- cmd/api/src/database/migration/migrations/v7.5.0.sql
- cmd/api/src/go.mod
- cmd/ui/src/views/DatabaseManagement/DatabaseManagement.test.tsx
- cmd/ui/src/views/DatabaseManagement/DatabaseManagement.tsx
Small update to verbiage within the Data Management page. "Proceed" has been updated to "Delete".
Resolves BED-5775
Provides clarity for the user that this action will DELETE their data.
Tested visually and ran test suite.
> BED-5775 data management update delete button

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Version Bumping SH to v2.6.7
Resolves https://specterops.atlassian.net/browse/BED-5989
> BED-5435 sh version bump

- packages/javascript/bh-shared-ui/src/routes/index.tsx
Resolves BED-6109
Updates default view to Summary view
> BED-6109 zone management default view

- packages/go/analysis/azure/queries.go
This simply adds principals of the AZRoleEligible edge to the list of default T0 assets
Resolves: BED-6122
I ingested an AzureHound payload locally and started the app off `main` and then again off this branch.
I then ran a Cypher query in both instances to ensure that the start nodes in the `AZRoleEligible` edge were marked as T0 and could not be added via the Group Management page
Note the diamond icons on the start nodes
Before:
After:
- Added/updated …
> BED-6122: T0 Tagging AZRoleEligible Principals

- .vscode/settings.json
- packages/go/stbernard/command/command.go
- packages/go/stbernard/command/tag/tag.go
Adds a new tag command to allow us to replace a beagle feature needed for release
BED-6227 - Release Ticket
Release pipeline breakage requires this update
Ran manually to validate outputs
> chore: new tag command for stbernard to allow us to generate tag outputs

- packages/go/analysis/ad/membership.go
Resolves BED-6284
Memory pressure resolution for group membership.
Local tests pass.
> fix (analysis): BED-6284 - do not hydrate entity properties for group membership crawling

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Bump AzureHound from version 2.6.0 to 2.7.0
Resolves: BED-6384
Testing instructions on BHE equivalent PR
> Bed-6384: AzureHound 2.7.0 Release Bump

- packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.test.tsx
- packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.tsx
- packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/QuerySearchFilter.tsx
- Relabel Pre-built Queries component header to Saved Queries
- Relabel Owned to Personal in the Source dropdown list
Resolves BED-6490
Updated copy to reduce confusion.  Especially surrounding the term 'Owned' which is used in other contexts within the application.  
Manually tested in local environment.  
Updated unit test.
All tests passing.  
- …
> BED-6490--Copy Update

- packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Save/TagForm/TagForm.test.tsx
- packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Save/TagForm/TagForm.tsx
Uses dirty fields for updating a tag.
Resolves BED-6489
Updating tags was sending information that was not changed.
Unit test was added.
> fix(agt): tag update request dirty fields

- dockerfiles/bloodhound.Dockerfile
- tools/docker-compose/api.Dockerfile
Increase the version of SharpHound to the latest version. 
Resolves BED-6506
> Bump Sharphound to Latest Version
